<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">What Mkomigbo is, why it exists, and what it stands for.</p>';
echo '<h2>What is Mkomigbo?</h2>';
echo '<p>Mkomigbo is an open knowledge platform dedicated to preserving, documenting, and sharing the history, culture, language, and heritage of the Igbo people of West Africa — and the broader African experience that connects them to the world.</p>';
echo '<p>The name draws from the Igbo language — carrying the sense of gathering knowledge from the forest. A metaphor for the deep, living, rooted nature of what we collect and protect.</p>';
echo '<h2>Why We Built This</h2>';
echo '<p>Igbo history is one of the richest in African history. Yet it remains fragmented — scattered across colonial archives, oral traditions, academic papers, diaspora memories, and community knowledge that risks being lost with each generation.</p>';
echo '<p>We built Mkomigbo because knowledge about a people belongs to that people. It should be freely accessible, honestly documented, and built to last.</p>';
echo '<h2>Our Principles</h2>';
echo '<ul>';
echo '<li><strong>Honesty</strong> — we document what happened, not what is comfortable</li>';
echo '<li><strong>Accessibility</strong> — all content is free and open to everyone</li>';
echo '<li><strong>Community</strong> — built with contributors from inside the community</li>';
echo '<li><strong>Depth</strong> — we prefer thorough, sourced content over quick summaries</li>';
echo '<li><strong>Continuity</strong> — we build for the long term, not for trends</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/about/overview/">Overview</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/about/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/about/people/">Contributors</a>';
echo '</div></div>';
