<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">An overview of the Mkomigbo platform — what it contains and how it is organized.</p>';
echo '<h2>The Knowledge Library</h2>';
echo '<p>Mkomigbo is organized around 19 subject areas, each covering a distinct dimension of Igbo and African life. Each subject contains an introduction, overview, key topics, people, and sources — structured to give both a quick entry point and deep research capability.</p>';
echo '<h2>19 Subject Areas</h2>';
echo '<ul>';
echo '<li><strong>History</strong> — timelines, migrations, kingdoms, and turning points</li>';
echo '<li><strong>Slavery</strong> — the Atlantic trade, internal systems, and abolition</li>';
echo '<li><strong>People</strong> — notable communities and identities</li>';
echo '<li><strong>Culture</strong> — arts, customs, festivals, and values</li>';
echo '<li><strong>Religion</strong> — traditional spirituality and belief systems</li>';
echo '<li><strong>Esoterism</strong> — cosmology, metaphysics, and spiritual practice</li>';
echo '<li><strong>Tradition</strong> — rites, norms, and communal frameworks</li>';
echo '<li><strong>Language</strong> — Igbo language, orthography, and learning</li>';
echo '<li><strong>Struggles</strong> — resistance movements and modern activism</li>';
echo '<li><strong>Biafra</strong> — the war, its causes, aftermath, and memory</li>';
echo '<li><strong>Nigeria</strong> — politics, society, and the Igbo experience</li>';
echo '<li><strong>Resistance</strong> — IPOB and contemporary activism in context</li>';
echo '<li><strong>Africa</strong> — continental context and connected histories</li>';
echo '<li><strong>United Kingdom</strong> — diaspora, history, and community life</li>';
echo '<li><strong>Europe</strong> — migration and diaspora contexts</li>';
echo '<li><strong>Arabs</strong> — historical connections and relations</li>';
echo '</ul>';
echo '<h2>AWAG — Africa Weekly Activities Guide</h2>';
echo '<p>Alongside the knowledge library, Mkomigbo hosts AWAG — a practical seasonal calendar for African communities covering farming, fishing, trading, herding, healing, and community life. 13 communities live across 9 ecological zones. Works offline. Installable on any device.</p>';
echo '<h2>Platforms</h2>';
echo '<p>Mkomigbo also hosts a growing set of community platforms — blog, forum, gallery, media library, podcast, and more — all connected to the subject library.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/">Browse Subjects</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/awag/">Open AWAG</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/platforms/">View Platforms</a>';
echo '</div></div>';
