<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>The Arc of Post-War Igbo Resistance</h2>';

echo '<h3>I. The Aftermath: 1970–1983</h3>';
echo '<p>The immediate post-war period was one of suppression rather than resistance. The federal government\'s "No victor, no vanquished" policy was a political formula that concealed a systematic programme of Igbo marginalisation. The abandoned property policy dispossessed Igbo of homes and businesses across Nigeria. The twenty-pound bank limit wiped out middle-class Igbo savings. Federal reconstruction bypassed the southeast. The Nigerian Army, purged of its Igbo officer corps after 1966, remained a Hausa-Fulani-dominated institution. The civil service was similarly restructured.</p>';
echo '<p>Igbo political response in this period was primarily one of rebuilding through commerce — the remarkable economic recovery of the Igbo in the 1970s, through trade, construction, and the informal economy, was itself a form of resistance: a refusal to remain economically prostrate. The Igbo proverb <em>onye wetara oji wetara ndu</em> — "he who brings kola brings life" — captures something of this: the insistence on engaging the world, on trading, on building, even from the ruins of defeat.</p>';

echo '<h3>II. Military Dictatorship and Civil Society: 1983–1999</h3>';
echo '<p>The return of military rule in 1983 produced a new context for Igbo resistance. The pro-democracy movements of the late 1980s and 1990s — the Campaign for Democracy, the National Democratic Coalition, the human rights lawyers and journalists who maintained opposition under Babangida and Abacha — were pan-Nigerian in composition but drew heavily on Igbo and Yoruba civil society traditions. Igbo lawyers, academics, and journalists were disproportionately represented in the pro-democracy movement.</p>';
echo '<p>The annulment of the June 12, 1993 election — won by Moshood Abiola — united southern Nigerians across ethnic lines in opposition to northern military rule. For Igbo political actors, this moment demonstrated both the possibility of cross-ethnic solidarity and its limits: when Abiola\'s Yoruba supporters eventually accepted his death in detention and the transition to civilian rule under Obasanjo (himself Yoruba), Igbo interests were again marginalised in the settlement.</p>';
echo '<p>The execution of Ken Saro-Wiwa in 1995 — and the broader Niger Delta environmental justice struggle — demonstrated that resistance to the Nigerian state\'s alliance with extractive corporations was possible and internationally resonant. Saro-Wiwa\'s methods — international lobbying, media strategy, legal action — established a template that later Igbo activists would draw on.</p>';

echo '<h3>III. The Emergence of IPOB: 1999–2017</h3>';
echo '<p>The return to civilian rule in 1999 did not deliver the structural changes Igbo political actors had sought. The Obasanjo presidency (1999–2007) was dominated by a Yoruba president with close ties to northern military networks; the Yar\'Adua presidency (2007–2010) and the Jonathan presidency (2010–2015) — Jonathan being the first president from the Niger Delta — were periods of partial Igbo inclusion that failed to address structural marginalisation.</p>';
echo '<p>Nnamdi Kanu launched Radio Biafra from London in 2009 and founded IPOB in 2012. The movement grew rapidly, drawing on the frustrations of a generation of young Igbo who had grown up after the war but inherited its unresolved grievances. IPOB\'s social media presence, its Radio Biafra broadcasts, and its mass mobilisation capacity made it the most significant Igbo political organisation of the 21st century within a few years of its founding.</p>';
echo '<p>Kanu\'s arrest in 2015, his detention, and his release on bail in 2017 transformed him from a radio broadcaster into a martyr figure. His return to his family compound in Afaraukwu, where he was greeted by enormous crowds, demonstrated IPOB\'s popular base. Operation Python Dance — the Nigerian Army\'s deployment to the southeast in September 2017, which included an attack on Kanu\'s family compound — drove him into exile and temporarily decapitated the movement\'s visible leadership.</p>';

echo '<h3>IV. Fracture and Continuation: 2017–2023</h3>';
echo '<p>The period after Operation Python Dance was one of internal IPOB fracture and continued Nigerian state violence. The Eastern Security Network (ESN), established by IPOB in 2020 ostensibly to protect Igbo communities from Fulani herdsmen attacks, became a source of controversy: its operations overlapped with those of criminal groups, and the Nigerian military\'s operations against it produced significant civilian casualties. The sit-at-home orders — originally called on specific dates — were extended to every Monday in the southeast, producing sustained economic paralysis and enforcement violence that fell on ordinary Igbo people.</p>';
echo '<p>Kanu\'s extraordinary rendition from Kenya in June 2021 — seized by Kenyan security forces and handed to Nigerian authorities in a operation that his lawyers argued violated both Kenyan and international law — returned him to Nigerian detention. His trial before the Federal High Court in Abuja has proceeded slowly, with repeated adjournments and security restrictions that have made his legal representation difficult.</p>';
echo '<p>The 2023 presidential election introduced a new dimension to Igbo political resistance. Peter Obi — former Governor of Anambra State, running on the Labour Party ticket — attracted extraordinary cross-ethnic support, particularly from young Nigerians, in what became known as the "Obidient" movement. His official result (25% of the vote, third place) was disputed by his supporters, who alleged massive electoral fraud. Whether the Obidient movement represents a new direction for Igbo political energy — engagement rather than separatism — or a temporary detour remains to be seen.</p>';

echo '<h3>V. Cultural Resistance: The Permanent Underground</h3>';
echo '<p>Alongside the political and armed forms of resistance documented above runs a continuous stream of cultural resistance that is less visible but no less significant. Igbo literature — from Chinua Achebe\'s foundational challenge to the colonial narrative in <em>Things Fall Apart</em> (1958) to Chimamanda Ngozi Adichie\'s <em>Half of a Yellow Sun</em> (2006) and <em>Americanah</em> (2013) — has consistently asserted Igbo humanity, complexity, and historical agency against both colonial and post-colonial misrepresentation. Igbo music, film (Nollywood, which is disproportionately Igbo in its creative workforce), and fashion have created a global cultural presence that the Nigerian state has been unable to marginalise.</p>';
echo '<p>The maintenance of Igbo language and cultural institutions in the diaspora — the town unions, the age-grade associations, the Igbo language schools, the cultural festivals — represents a form of resistance that operates below the level of political visibility but sustains the community that political resistance draws on. You cannot have a Biafran movement without Igbo people who remain Igbo. The cultural infrastructure that maintains Igbo identity is therefore not separate from resistance — it is its foundation.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/struggles/overview/">→ Struggles</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/overview/">→ Biafra</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/nigeria/overview/">→ Nigeria</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/history/overview/">→ History</a>';
echo '</div>';
echo '</div>';