<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Figures of Resistance</h2>';
echo '<h3>Nnamdi Kanu (b. 1967)</h3>';
echo '<p>Nnamdi Kanu is the defining figure of 21st-century Igbo resistance and its most polarising. Born in Isiama Afaraukwu, Abia State, he studied in the United Kingdom and built Radio Biafra from London into a global Igbo political broadcast that the Nigerian government found threatening enough to pressure UK authorities to shut down. His founding of IPOB in 2012 and its growth into a mass movement demonstrated an organisational and media capacity that the Nigerian political establishment consistently underestimated. His arrest in 2015, his release on bail in 2017, his flight after Operation Python Dance attacked his family compound, and his extraordinary rendition from Kenya in 2021 are the chapters of a political biography that his supporters read as martyrdom and his critics read as recklessness. His ongoing trial in Abuja on charges including terrorism and treasonable felony is one of the most significant political trials in contemporary Nigerian history.</p>';
echo '<h3>Ralph Uwazurike (b. 1961)</h3>';
echo '<p>Ralph Uwazurike founded the Movement for the Actualisation of the Sovereign State of Biafra (MASSOB) in 1999 — the predecessor organisation to IPOB and the first significant post-war Biafran independence movement. A lawyer by training, Uwazurike built MASSOB on a platform of non-violent resistance, drawing explicitly on Gandhian civil disobedience principles. MASSOB\'s activities — flying the Biafran flag, issuing Biafran identity cards, organising sit-at-home strikes — provoked repeated Nigerian security crackdowns. Uwazurike himself spent years in detention. He eventually fell out with Kanu and IPOB over the question of violence — maintaining a commitment to non-violence that IPOB\'s subsequent trajectory has not shared. His contribution to the contemporary self-determination movement is foundational and underacknowledged.</p>';
echo '<h3>Peter Obi (b. 1961)</h3>';
echo '<p>Peter Obi represents a different model of Igbo political resistance: engagement within the Nigerian federal system combined with a technocratic critique of how that system has been run. As Governor of Anambra State from 2006 to 2014, he built a reputation for fiscal discipline — returning Anambra to solvency, investing in education and infrastructure, and refusing the personal enrichment that characterises most Nigerian gubernatorial tenures. His 2023 presidential campaign on the Labour Party ticket mobilised a cross-ethnic coalition of young Nigerians — the "Obidient" movement — that demonstrated the electoral potential of an Igbo candidate presenting a credible governance programme. His official result of 25% of the vote was disputed by his supporters, who alleged massive electoral fraud. Whether the movement he catalysed becomes a permanent political formation will be one of the defining questions of Igbo politics in the 2020s.</p>';
echo '<h3>Chimamanda Ngozi Adichie (b. 1977)</h3>';
echo '<p>Chimamanda Ngozi Adichie is the most significant Igbo cultural figure of her generation and one of the most significant African writers in the world. Her inclusion in a Resistance subject requires explanation: her work performs the most fundamental act of resistance available to a writer — it insists on the full humanity and complexity of the people it depicts. <em>Half of a Yellow Sun</em> (2006) placed the Biafra War at the centre of global literary attention in a way that no political speech could have achieved. Her TED talks — "The Danger of a Single Story" (2009) and "We Should All Be Feminists" (2012) — have reached hundreds of millions of viewers and shaped global conversations about representation and identity in ways that no Igbo political organisation has managed. She is, in the most precise sense, a resistance figure.</p>';
echo '<h3>Wole Soyinka (b. 1934)</h3>';
echo '<p>Wole Soyinka is Yoruba, not Igbo — but his inclusion in the Resistance subject is justified by his consistent advocacy for Igbo rights and his position as Nigeria\'s most significant intellectual voice for political accountability. During the Biafra War, Soyinka was imprisoned by the federal government for two years in solitary confinement — punishment for his attempts to negotiate a ceasefire. His memoir of that imprisonment, <em>The Man Died</em> (1972), is one of the great documents of resistance to military power in African literature. His Nobel Prize (1986) gave him an international platform that he has consistently used to hold the Nigerian state accountable — for the Biafra War, for military dictatorship, for the execution of Saro-Wiwa, for the treatment of IPOB. He is the pan-Nigerian voice that takes Igbo political grievances seriously precisely because he is not Igbo.</p>';
echo '</div>';