<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Five Sites of Resistance</h2>';

echo '<h3>1. IPOB: The Self-Determination Movement</h3>';
echo '<p>The Indigenous People of Biafra is simultaneously the most significant and most contested Igbo political organisation of the 21st century. Its core demand — a referendum on Biafran independence conducted under international supervision — is legally grounded in the right of self-determination recognised in international law, including the UN Charter and the International Covenant on Civil and Political Rights. Its methods have ranged from media agitation and mass rallies to sit-at-home orders enforced with violence and the establishment of the Eastern Security Network, which the Nigerian government has designated a terrorist organisation.</p>';
echo '<p>The internal contradictions of IPOB are significant. The sit-at-home orders that IPOB imposes — originally on specific dates, extended to every Monday in the southeast — have caused enormous economic damage to the communities IPOB claims to represent. Schools have closed. Markets have shuttered. Businesses have relocated to other regions. The violence used to enforce the sit-at-home — by groups claiming IPOB affiliation, some of which appear to have criminal rather than political motivations — has killed civilians and driven investment away from the southeast. The movement\'s popular resonance is real; the costs it imposes on ordinary Igbo life are also real. Both things are true simultaneously.</p>';
echo '<p>The Nigerian state\'s response — military operations, proscription, the detention and trial of Kanu — has not delegitimised IPOB in the eyes of its supporters. If anything, state violence has reinforced the movement\'s narrative: that the Nigerian state is incapable of engaging Igbo political grievances through dialogue and responds to them only with force. This dynamic — movement provocation, state violence, increased radicalisation — is the central political trap of the contemporary southeast.</p>';

echo '<h3>2. Ohanaeze Ndigbo: Institutional Resistance</h3>';
echo '<p>Ohanaeze Ndigbo — the apex Igbo socio-cultural organisation — represents a different tradition of resistance: institutional engagement within the Nigerian federal system. Founded in 1976, Ohanaeze advocates for Igbo interests through dialogue with the federal government, through lobbying, through the appointment of its representatives to federal commissions and advisory bodies, and through public statements on matters affecting the Igbo. It has consistently opposed IPOB\'s separatist agenda while acknowledging the legitimacy of the underlying grievances.</p>';
echo '<p>Ohanaeze\'s limitations are those of any organisation that operates within a system it seeks to reform. Its access to federal power depends on its willingness to work within federal structures; its credibility with the Igbo base depends on its willingness to challenge those structures. This tension has produced a history of Ohanaeze statements that acknowledge Igbo marginalisation while stopping short of the structural demands that would actually address it. Its relationship with IPOB has been consistently hostile — Ohanaeze has condemned IPOB violence and supported Kanu\'s prosecution — but this position has damaged its credibility with the sections of Igbo youth who see Ohanaeze as a collaborationist organisation.</p>';

echo '<h3>3. The 2023 Labour Party Campaign: Cross-Ethnic Resistance</h3>';
echo '<p>Peter Obi\'s 2023 presidential campaign on the Labour Party ticket was the most significant demonstration of Igbo political potential within the Nigerian federal system since independence. Obi — a former two-term Governor of Anambra State with a reputation for fiscal discipline and effective governance — attracted support across ethnic and regional lines that no previous Igbo presidential candidate had achieved. The "Obidient" movement, organised primarily through social media, mobilised young Nigerians who were simultaneously frustrated with the two dominant parties (APC and PDP) and attracted to Obi\'s technocratic, anti-corruption message.</p>';
echo '<p>Obi\'s official result — approximately 6.1 million votes, 25% of the total, third place behind Tinubu (APC) and Abubakar (PDP) — was disputed by his campaign and by independent observers who documented extensive irregularities. The election tribunal and subsequent appeals upheld Tinubu\'s victory. Whether the Obidient movement represents a sustainable political formation or a one-cycle phenomenon remains to be seen. What it demonstrated is that Igbo political energy is not exhausted by the separatist/engagement binary — that a candidate presenting a vision of reformed Nigerian governance could mobilise Igbo voters and attract cross-ethnic support simultaneously.</p>';

echo '<h3>4. Diaspora Activism: The International Dimension</h3>';
echo '<p>The Igbo diaspora — concentrated in the United Kingdom, the United States, Canada, and continental Europe — has been a consistent source of financial support, political lobbying, and media amplification for Igbo resistance movements. IPOB\'s Radio Biafra was built from London. IPOB\'s international lobbying at the UN Human Rights Council and in the United States Congress has been conducted primarily by diaspora activists. The diaspora\'s financial remittances to families in the southeast have partly offset the economic damage caused by sit-at-home orders and security operations.</p>';
echo '<p>The diaspora\'s relationship to the resistance movements it supports is complicated by distance. Diaspora activists can call for sit-at-home strikes without bearing their economic costs. They can support IPOB\'s most confrontational positions without living under the security operations those positions provoke. This distance produces a political dynamic in which the most radical positions are often held by those with the least to lose from their consequences — a structural feature of diaspora politics that is not unique to the Igbo but is particularly acute given the costs that sit-at-home enforcement imposes on southeast communities.</p>';

echo '<h3>5. Cultural Resistance: Literature, Film, and Language</h3>';
echo '<p>The most durable form of Igbo resistance has been cultural. Chinua Achebe\'s <em>Things Fall Apart</em> (1958) — the most widely read African novel in the world, with over 20 million copies sold in 57 languages — performed an act of cultural resistance that no military campaign could have achieved: it placed the Igbo at the centre of a narrative that European colonialism had constructed around European protagonists. It did this not through polemic but through the creation of a fictional world so fully realised that its humanity was undeniable. Every reader who finishes <em>Things Fall Apart</em "> has been changed, however slightly, in their understanding of what colonialism did and to whom.</p>';
echo '<p>Chimamanda Ngozi Adichie has continued this tradition in the 21st century, with <em>Half of a Yellow Sun</em> (2006) placing the Biafra War at the centre of global literary attention and <em>Americanah</em> (2013) examining race, migration, and Igbo identity in the contemporary world. Nollywood — the Nigerian film industry centred largely in Lagos but with disproportionate Igbo creative input — has created a global African popular culture that reaches audiences across the continent and in the diaspora. The maintenance of Igbo language schools, cultural festivals, and community organisations in the diaspora sustains the cultural identity from which all other forms of resistance draw.</p>';
echo '</div>';