<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">The transatlantic slave trade did not happen to Africa. It happened inside Africa — inside its politics, its trade networks, its religious institutions, and its social hierarchies. The Igbo were not only victims of the trade. They were also, in specific and documented ways, its instruments. This subject holds both truths simultaneously.</p>';
echo '<h2>The Scale of the Crime</h2>';
echo '<p>Between 1500 and 1900, approximately 12.5 million Africans were captured, transported across the Atlantic, and enslaved in the Americas. Of these, an estimated 10.7 million survived the Middle Passage. They and their descendants built the economies of Brazil, the Caribbean, and the American South. The wealth generated by their forced labour funded the industrial revolution in Britain, France, and the United States. Eric Williams demonstrated in <em>Capitalism and Slavery</em> (1944) what European economic historians spent the next eighty years attempting to qualify: that the profits of enslaved African labour were not incidental to European modernity but constitutive of it.</p>';
echo '<p>The Bight of Biafra — the stretch of Atlantic coast corresponding to modern southeastern Nigeria — was one of the most active slaving zones in the entire Atlantic system. Approximately 1.6 million enslaved people were exported from this region, the vast majority of them Igbo. This makes the Igbo one of the largest single-language groups in the entire African diaspora — larger than the Yoruba, larger than the Akan, comparable only to the Bantu-speaking groups of Central Africa. The consequences of this dispersal — for Igbo population, Igbo social structures, and Igbo collective memory — have never been fully reckoned with.</p>';
echo '<h2>How Igbo People Were Enslaved</h2>';
echo '<p>Igbo people were enslaved through multiple mechanisms, and the mechanisms matter because they complicate the simple victim-perpetrator narrative that both European and African accounts of the trade have sometimes preferred. Wars between communities produced captives who could be sold. The Aro trading network — centred on the Aro Chukwu oracle at Arochukwu — operated a sophisticated system in which the oracle\'s "judgments" produced enslaved people who were channelled to coastal ports at Calabar, Bonny, and Brass. Kidnapping — <em>igba ama</em> in Igbo, literally "to seize a person" — was widespread and feared. Debt and judicial punishment within Igbo society itself could result in enslavement, though internal Igbo slavery differed fundamentally in character from the chattel slavery of the Atlantic system.</p>';
echo '<p>The Aro role in the trade is the most historically significant and the most uncomfortable. The Aro people were Igbo — they spoke Igbo, they were part of Igbo cultural space — and they built the infrastructure through which hundreds of thousands of Igbo people were delivered to the Atlantic trade. The oracle\'s authority was real: communities across Igboland sent disputes to Arochukwu for judgment, and those judged guilty by the oracle could be enslaved. The Aro did not invent the trade. They adapted existing Igbo religious and commercial institutions to meet external demand. But the adaptation was their own, and its consequences fell on their own people.</p>';
echo '<h2>The Osu System</h2>';
echo '<p>Slavery existed within Igbo society in forms distinct from the Atlantic trade. The <em>ohu</em> — domestic slaves — occupied a low but not entirely fixed social position; their children could sometimes achieve free status. The <em>osu</em> — individuals and their descendants dedicated to a deity — occupied a permanently stigmatised position that was not exactly slavery but shared slavery\'s hereditary character and social exclusion. The osu system predates the Atlantic trade and is not a product of it. But the Atlantic trade intensified the social stratifications that the osu system expressed, and the system\'s persistence into the present — affecting marriage, social participation, and community belonging in some Igbo communities today — is a live political issue rather than a historical curiosity.</p>';
echo '<h2>Navigate the Subject</h2>';
echo '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px;margin:16px 0;">';
$sections = [
  ['/subjects/slavery/overview/','🗺️ Overview','Before the Atlantic trade, the Middle Passage, Igbo in the Americas, abolition, reparations'],
  ['/subjects/slavery/topics/','🏛️ Five Sites of Enslavement','The Aro network, Igbo Landing, the Bight of Biafra, abolition, the osu system'],
  ['/subjects/slavery/people/','👤 People','Olaudah Equiano, the Igbo Landing group, Frederick Douglass, G. Ugo Nwokeji, Chinua Achebe'],
  ['/subjects/slavery/sources/','📚 Sources','What to read — primary sources, Igbo-specific scholarship, general Atlantic trade history'],
];
foreach($sections as [$href,$title,$desc]) {
  echo '<a href="'.$href.'" style="display:block;padding:14px;border:1px solid #e5e7eb;border-radius:12px;text-decoration:none;color:inherit;background:#fff;transition:box-shadow .12s;" onmouseover="this.style.boxShadow=\'0 4px 16px rgba(0,0,0,.09)\'" onmouseout="this.style.boxShadow=\'\'">';
  echo '<div style="font-weight:800;font-size:.95rem;color:#111;margin-bottom:4px;">'.$title.'</div>';
  echo '<div style="font-size:.82rem;color:#6b7280;line-height:1.4;">'.$desc.'</div>';
  echo '</a>';
}
echo '</div>';
echo '<h2>Our Approach</h2>';
echo '<p>This subject does not sanitise the trade or its Igbo dimensions. It does not reduce the Igbo to victims, but it does not minimise their victimisation. It holds the complexity that the historical record requires: that the same people could be simultaneously the largest single group exported from the Bight of Biafra and the builders of the trading infrastructure that facilitated that export. That the osu system is both an internal Igbo tradition and a form of hereditary social exclusion that demands honest examination. This subject is cross-linked with <a href="/subjects/history/intro/">History</a>, <a href="/subjects/struggles/intro/">Struggles</a>, and <a href="/subjects/europe/intro/">Europe</a>.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/overview/">→ Africa</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/arabs/overview/">→ Arabs</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/europe/overview/">→ Europe</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/resistance/overview/">→ Resistance</a>';
echo '</div>';
echo '</div>';