<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>The Broad History of Slavery and the Igbo</h2>';

echo '<h3>I. Before the Atlantic Trade</h3>';
echo '<p>Slavery was not introduced to West Africa by Europeans — it existed in various forms in African societies for centuries before Atlantic contact. Within Igbo society, the distinction between <em>ohu</em> (domestic slaves) and free people was real but more permeable than the chattel slavery of the Americas. Enslaved people could accumulate property, participate in community life to varying degrees, and their children could sometimes achieve free status. The <em>osu</em> — individuals dedicated to a deity — occupied a distinct and more permanently stigmatised position. Neither form of internal Igbo slavery was chattel slavery in the Atlantic sense: the enslaved were not legally property, could not be sold across the ocean, and retained cultural and linguistic continuity with their communities.</p>';
echo '<p>The trans-Saharan and Indian Ocean slave trades — operating for centuries before the Atlantic trade — had already drawn some West Africans into external slavery networks, though their impact on the Bight of Biafra region was less direct than on the Sahel and East African coast. What distinguished the Atlantic trade was its scale, its racial character, and its permanence: Atlantic slavery created a new social category — the racialised slave — in which African descent itself became the marker of unfreedom.</p>';

echo '<h3>II. The Atlantic Trade Transforms Everything</h3>';
echo '<p>The arrival of European demand for enslaved labour changed the scale and character of slavery in West Africa entirely. The Bight of Biafra region, which had not been a major slave-exporting zone in the early Atlantic trade, became one of its most active by the 18th century. The Aro trading network — which had previously traded in goods across Igboland — expanded and reoriented toward the Atlantic slave trade. Communities that had previously enslaved small numbers found external markets offering high prices for captives. Wars became more frequent and more oriented toward capturing people for sale. Kidnapping — previously a social crime — became a commercial enterprise.</p>';
echo '<p>The scale of the resulting export is staggering. The Slave Voyages Database, the most comprehensive scholarly record of the Atlantic trade, documents approximately 1.6 million people exported from the Bight of Biafra between 1650 and 1850. The overwhelming majority were Igbo. In the peak decades of the 18th century, the Bight of Biafra was exporting 20,000-30,000 people annually. This was not a marginal or peripheral experience for Igbo society — it was a catastrophe that depopulated villages, disrupted agricultural production, militarised social relations, and left a demographic scar that shaped Igboland for generations.</p>';

echo '<h3>III. The Middle Passage</h3>';
echo '<p>The transatlantic voyage — the Middle Passage — was a system of calculated terror. Enslaved people were packed into ships at densities designed to maximise cargo while accepting a calculable level of mortality — a mortality that the slave trade insurance industry priced and insured. Disease, dehydration, violence, and suicide killed between 10 and 20 percent of those who boarded. Those who survived arrived in the Americas physically broken, their names replaced, their languages forbidden, their communities destroyed, their identities reduced to the racial category that Atlantic slavery had invented.</p>';
echo '<p>Igbo captives were noted by contemporary observers for their responses to the Middle Passage. They were described as particularly prone to suicide — the practice of drowning themselves rather than accept enslavement was documented on multiple occasions, most famously at Dunbar Creek, Georgia, in 1803. Whether this represents a cultural pattern or simply the observers\' tendency to notice Igbo captives specifically is a question historians have debated. What is clear is that the resistance to enslavement — individual and collective, on the ship and after landing — was a dimension of the Igbo experience in the Atlantic trade that contemporary accounts consistently noted.</p>';

echo '<h3>IV. Igbo in the Americas</h3>';
echo '<p>Igbo people enslaved in the Americas created communities, preserved cultural practices, and left traces that survive to the present. In the coastal regions of South Carolina and Georgia — the Sea Islands — the Gullah people preserved more African cultural continuity than almost any other African-American community, and Igbo linguistic and cultural elements are documented in their traditions. In Virginia, where Igbo captives arrived in large numbers through the Chesapeake Bay trade, Igbo cultural influences can be traced in place names and folk practices. In Jamaica and Trinidad, Igbo cultural memory survived in oral tradition, music, and religious practice.</p>';
echo '<p>The growing field of African diaspora genealogy — accelerated by DNA testing that can identify West African regional origins — is recovering Igbo ancestry in diaspora communities across the Americas. This recovery matters: it connects living people to a specific cultural heritage and challenges the historical amnesia that Atlantic slavery enforced. It also creates new forms of connection between Igbo communities in Nigeria and their diaspora descendants — connections that the Mkomigbo platform is specifically designed to support.</p>';

echo '<h3>V. Abolition and Its Limits</h3>';
echo '<p>Britain abolished the slave trade in 1807 and slavery in its colonies in 1833. The United States abolished slavery in 1865 after a civil war in which 620,000 soldiers died. France abolished slavery in its colonies in 1848. These legal abolitions did not end the consequences of slavery. The wealth extracted from enslaved labour had already funded the industrialisation of the West. The communities that produced the enslaved remained impoverished and colonised — indeed, the abolition of the slave trade was followed almost immediately by the intensification of colonial extraction in Africa. The freed enslaved peoples of the Americas received no reparations, no land, and no structural support. Their descendants continue to bear the consequences of slavery in systems of racial inequality that persist to the present day.</p>';
echo '<p>The reparations debate — whether Britain, France, the United States, and other slave-trading and slave-holding powers owe reparations to the descendants of the enslaved and to Africa — is one of the most significant moral and political questions of the 21st century. The Caribbean Community (CARICOM) has advanced a formal reparations claim. African states have raised the question at the African Union. Britain has consistently refused, while acknowledging the trade\'s horror in terms that its own historians regard as inadequate. The debate touches questions of historical responsibility, intergenerational justice, and the ongoing structural consequences of slavery that no financial settlement alone can address — but that no honest accounting of the present can ignore.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/overview/">→ Africa</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/arabs/overview/">→ Arabs</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/europe/overview/">→ Europe</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/struggles/overview/">→ Struggles</a>';
echo '</div>';
echo '</div>';