<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>The Enslaved, the Abolitionists, and the Scholars</h2>';
echo '<h3>Olaudah Equiano (c.1745-1797)</h3>';
echo '<p>Olaudah Equiano is the most significant Igbo voice in the history of the Atlantic slave trade and one of the most significant voices in the history of abolition. Born in what is now Anambra State — he describes his home village of Essaka with details that correspond to recognisable Igbo customs — he was kidnapped as a child of approximately eleven, transported to the coast, sold across the Atlantic, enslaved in Barbados, then Virginia, then purchased by a Royal Navy officer who renamed him Gustavus Vassa. He eventually purchased his own freedom in 1766 and settled in Britain.</p>';
echo '<p>His autobiography — <em>The Interesting Narrative of the Life of Olaudah Equiano</em> (1789) — is a work of extraordinary rhetorical and political sophistication. It is simultaneously a spiritual autobiography, a travel narrative, a commercial account, and the most powerful abolitionist argument of its era: the argument from lived experience. The book sold thousands of copies, went through nine British editions in his lifetime, and was submitted to Parliament in support of the abolition of the slave trade. A scholarly controversy initiated by Vincent Carretta questions whether Equiano was actually born in Africa or in South Carolina. The debate has not been resolved. What is not in dispute is that Equiano had intimate knowledge of Igbo culture, described it with accuracy and affection, and identified himself as Igbo throughout his adult life. Whether or not he was born in Igboland, he was the Igbo voice that the world heard first.</p>';
echo '<h3>The Igbo Landing Group (1803)</h3>';
echo '<p>The Igbo men and women who walked into Dunbar Creek, Georgia, on 8 June 1803 are unnamed in the historical record. Their names were not recorded because the insurance claim that documented their deaths required only their number and their commercial value. They appear in the archive as a financial loss. They appear in oral tradition as an act of collective refusal that has been remembered and honoured for two centuries. What we know: approximately 75 Igbo captives were on the vessel <em>York</em>, owned by John Couper and Thomas Spalding. During the transfer from ship to shore, they overturned the transport vessel. The two white crew members drowned. The Igbo survivors walked into the water. The creek was thereafter called Dunbar Creek. The Gullah communities of St. Simons Island preserved the memory across two centuries. This platform honours the unnamed dead by naming what they did: they chose freedom on their own terms.</p>';
echo '<h3>Frederick Douglass (1818-1895)</h3>';
echo '<p>Frederick Douglass was not Igbo — he was born into slavery in Maryland and did not know his African origins. But his work belongs in this subject because he documented and argued against the same system that consumed Igbo captives, and because his methods — the published memoir, the speaking tour, the political lobbying, the appeal to the moral principles that the slave-holding society claimed to hold — established a template that Igbo abolitionists including Equiano had pioneered a generation earlier. His three autobiographies are among the most important documents in American history. His 1852 speech "What to the Slave Is the Fourth of July?" is the most devastating critique of American hypocrisy on slavery that the 19th century produced. He is included here as part of the African diaspora that the Bight of Biafra trade helped create.</p>';
echo '<h3>G. Ugo Nwokeji (contemporary)</h3>';
echo '<p>G. Ugo Nwokeji is the leading modern historian of the Igbo experience in the Atlantic slave trade. His <em>The Slave Trade and Culture in the Bight of Biafra: An African Society in the Atlantic World</em> (2010) is the most detailed and analytically sophisticated scholarly study of how and why so many Igbo people were enslaved, the mechanisms of the Aro trading network, the cultural practices of the Bight of Biafra region, and the trade\'s long-term consequences for Igbo society. It is essential reading for serious students of this subject and represents the kind of African-centred scholarship that the Mkomigbo platform aspires to document and extend.</p>';
echo '<h3>Chinua Achebe on Slavery and the Osu</h3>';
echo '<p>Chinua Achebe addressed the legacy of slavery in Igbo society in two distinct but related ways. <em>Things Fall Apart</em> (1958) depicts the precolonial Igbo social order — including its internal hierarchies, its ohu slaves, and its osu — with a realism that neither romanticises nor condemns. Okonkwo\'s household includes enslaved people; their presence is unremarked because it is ordinary. This is not apologetics for slavery; it is historical honesty. <em>No Longer at Ease</em> (1960) places the osu system at the centre of a contemporary tragedy — a young man destroyed by his family\'s refusal to allow him to marry a woman of osu descent. Together, the two novels constitute the most important literary examination of internal Igbo slavery and its legacy that exists in any language. Achebe did not resolve the question of the osu system; he made it impossible to ignore.</p>';
echo '</div>';