<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Essential references for the study of slavery and its Igbo dimensions.</p>';
echo '<h2>Primary Sources</h2>';
echo '<ul>';
echo '<li><strong>Olaudah Equiano</strong> — <em>The Interesting Narrative of the Life of Olaudah Equiano</em> (1789). The essential primary source. Available free online.</li>';
echo '<li><strong>Slave Voyages Database</strong> — slavevoyages.org — the most comprehensive database of transatlantic slave trade records, searchable by origin region, port, and destination.</li>';
echo '</ul>';
echo '<h2>Igbo and Bight of Biafra</h2>';
echo '<ul>';
echo '<li><strong>G. Ugo Nwokeji</strong> — <em>The Slave Trade and Culture in the Bight of Biafra</em> (2010). The definitive modern study.</li>';
echo '<li><strong>Paul Lovejoy and David Richardson</strong> — multiple articles on the Bight of Biafra slave trade.</li>';
echo '<li><strong>Adiele Afigbo</strong> — work on the Aro trading network and its role in the slave trade.</li>';
echo '</ul>';
echo '<h2>General Atlantic Slave Trade</h2>';
echo '<ul>';
echo '<li><strong>Hugh Thomas</strong> — <em>The Slave Trade</em> (1997). The most comprehensive single-volume history.</li>';
echo '<li><strong>Marcus Rediker</strong> — <em>The Slave Ship: A Human History</em> (2007). The Middle Passage experience in detail.</li>';
echo '<li><strong>Eric Williams</strong> — <em>Capitalism and Slavery</em> (1944). The foundational work on the economic relationship between slavery and British industrialization.</li>';
echo '</ul>';
echo '<h2>Igbo Diaspora in the Americas</h2>';
echo '<ul>';
echo '<li><strong>Michael A. Gomez</strong> — <em>Exchanging Our Country Marks</em> (1998). African ethnic identities in the Americas, including Igbo.</li>';
echo '<li><strong>Sylviane Diouf</strong> — <em>Slavery\'s Exiles</em> (2014). On maroon communities and their African roots.</li>';
echo '</ul>';
echo '<h2>The Osu System</h2>';
echo '<ul>';
echo '<li><strong>Chinua Achebe</strong> — <em>No Longer at Ease</em> (1960). The essential literary treatment.</li>';
echo '<li>Various articles in <em>Africa: Journal of the International African Institute</em> on the osu caste.</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/slavery/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/slavery/overview/">Overview</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/slavery/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/slavery/people/">People</a>';
echo '</div></div>';
