<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Igbo grammar — how the language is built and how sentences work.</p>';
echo '<h2>Nouns</h2>';
echo '<p>Igbo nouns do not change form for plural — context and number words indicate plurality. "Ụlọ" means both "house" and "houses." To specify: "ụlọ abụọ" (two houses), "ụlọ ndị a" (these houses).</p>';
echo '<p>Nouns often have a noun prefix "a-/i-/ọ-/u-" that belongs to the word: "ọgbọ" (age-mate), "ihe" (thing), "ụlọ" (house), "aka" (hand).</p>';
echo '<h2>Pronouns</h2>';
echo '<ul>';
echo '<li><strong>M / Mụ</strong> — I / me</li>';
echo '<li><strong>Gị</strong> — you (singular)</li>';
echo '<li><strong>Ọ</strong> — he / she / it (no gender distinction)</li>';
echo '<li><strong>Anyị</strong> — we (exclusive — not including the person spoken to)</li>';
echo '<li><strong>Anyị / Ànyị</strong> — we (inclusive)</li>';
echo '<li><strong>Ụnụ</strong> — you (plural)</li>';
echo '<li><strong>Ha</strong> — they / them</li>';
echo '</ul>';
echo '<h2>Verbs and Aspect</h2>';
echo '<p>Igbo verbs mark aspect — whether an action is complete or ongoing — rather than tense. The same verb root takes different forms:</p>';
echo '<ul>';
echo '<li><strong>ọ rịa ihe</strong> — he eats food (habitual/ongoing)</li>';
echo '<li><strong>ọ rị ihe</strong> — he ate food / he has eaten food (complete)</li>';
echo '<li><strong>ọ na-arị ihe</strong> — he is eating food (progressive)</li>';
echo '</ul>';
echo '<h2>Questions</h2>';
echo '<p>Yes/no questions are formed by tone change on the final syllable or by adding "ọ bụ ezie?" (is it true?). Information questions use question words:</p>';
echo '<ul>';
echo '<li><strong>Kedu?</strong> — How? / What? / Where? (general question)</li>';
echo '<li><strong>Kedu ka ọ dị?</strong> — How is it? / How are things?</li>';
echo '<li><strong>Onye?</strong> — Who?</li>';
echo '<li><strong>Gịnị?</strong> — What?</li>';
echo '<li><strong>Ebe?</strong> — Where?</li>';
echo '<li><strong>Mgbe?</strong> — When?</li>';
echo '<li><strong>Maka gịnị?</strong> — Why?</li>';
echo '</ul>';
echo '<h2>Negation</h2>';
echo '<p>Negation uses "adịghị" (is not / does not) or "ọ bụghị" (it is not):</p>';
echo '<ul>';
echo '<li><strong>Adịghị mma</strong> — It is not well / Not good</li>';
echo '<li><strong>Ọ bụghị ya</strong> — It is not him/her/it</li>';
echo '<li><strong>Arịghị m ihe</strong> — I did not eat</li>';
echo '</ul>';
echo '<h2>Copula — "Ọ bụ"</h2>';
echo '<p>"Ọ bụ" is the copula (to be) in Igbo — equivalent to "it is" or "he/she/it is":</p>';
echo '<ul>';
echo '<li><strong>Ọ bụ Emeka</strong> — It is Emeka / He is Emeka</li>';
echo '<li><strong>Ọ bụ Igbo</strong> — He/she is Igbo</li>';
echo '<li><strong>Ọ bụ ihe ọma</strong> — It is a good thing</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/topics/">Daily Usage</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/sources/">Resources</a>';
echo '</div></div>';
