<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Igbo Grammar: How the Language is Built</h2>';

echo '<h3>I. Nouns</h3>';
echo '<p>Igbo nouns do not inflect for number or gender — there is no grammatical distinction between masculine and feminine, and plural is indicated by context, number words, or demonstratives rather than by changing the noun\'s form. "Ụlọ" means both "house" and "houses." To specify: "ụlọ abụọ" (two houses), "ụlọ ndị a" (these houses). Nouns often carry a noun prefix (a-, i-, ọ-, u-) that is part of the word itself: "ọgbọ" (age-mate), "ihe" (thing), "ụlọ" (house), "aka" (hand). These prefixes are not grammatical markers in the European sense; they are part of the word\'s phonological form.</p>';
echo '<p>Nouns in Igbo carry tonal information that can change the word\'s meaning. "Àkà" (direction/side) differs from "aka" (hand) only in the tone of the first vowel. Tone is therefore not merely phonological — it is lexical, carrying meaning the way spelling does in English. This means that a learner who ignores Igbo tones is, in effect, learning a different language from the one being spoken.</p>';

echo '<h3>II. Pronouns</h3>';
echo '<p>Igbo has a full set of personal pronouns that also carry tonal and aspectual information. The basic forms are: <em>m / mụ</em> (I/me), <em>gị</em> (you singular), <em>ya</em> (he/she/it — Igbo does not distinguish gender in the third person singular), <em>anyị</em> (we exclusive — not including the person spoken to), <em>anyi</em> (we inclusive — including the person spoken to), <em>ụnụ</em> (you plural), <em>ha</em> (they/them). The distinction between exclusive and inclusive first person plural — "we not including you" versus "we including you" — is a feature that English does not have and that marks Igbo as more precise in certain social contexts.</p>';

echo '<h3>III. Verbs and Aspect</h3>';
echo '<p>Igbo verbs mark aspect rather than tense — they indicate whether an action is complete or ongoing, not when it occurred. This is a fundamental difference from European languages and one of the features that makes Igbo grammar initially counterintuitive for English speakers. "Ọ rịrị ihe" (he/she ate food — completed action) differs from "ọ na-eri ihe" (he/she is eating food — ongoing action). The time reference is established by context, adverbs, or discourse structure, not by the verb form itself.</p>';
echo '<p>The verb in Igbo is the most morphologically complex element of the sentence. It can be extended by aspect markers, object pronouns incorporated into the verb, and directional particles. The verb "bia" (come) can become "bịara" (came — completed), "na-abịa" (is coming — progressive), "abịala" (has come — perfect), and "ga-abịa" (will come — prospective). These forms involve tonal changes as well as segmental changes, making the verb system one of the most challenging aspects of Igbo for learners.</p>';

echo '<h3>IV. The Serial Verb Construction</h3>';
echo '<p>One of the most distinctive features of Igbo grammar — shared with other Niger-Congo languages — is the serial verb construction: multiple verbs follow each other in sequence without conjunctions, each contributing to the overall meaning of the predicate. "O gara ụlọ zuo ihe" — she went home fetched something (she went home and fetched something). "Ya were ego tuo ya" — take money pay him (pay him with money). In English, these would require conjunctions (and, with, in order to); in Igbo, the verbs simply follow each other, with tonal and aspectual adjustments marking the relationships between them.</p>';
echo '<p>The serial verb construction is not merely a grammatical curiosity — it reflects a different way of conceptualising events. Where English sees actions connected by logical relations (and, because, in order to), Igbo sees a single complex action decomposed into its component movements. Understanding serial verbs is key to understanding how Igbo speakers think about events and causation.</p>';

echo '<h3>V. Sentence Structure and Discourse</h3>';
echo '<p>Basic Igbo sentence structure is Subject-Verb-Object, like English: "Emeka rị ihe" (Emeka ate food). But Igbo discourse — the way sentences connect into conversations and texts — differs significantly from English. Topic-comment structure is prominent: a topic is established first, then a comment is made about it. Focus constructions — emphasising a particular element of the sentence — use tonal and syntactic devices that have no direct English equivalent. Questions are formed differently depending on whether they seek a yes/no answer, a specific piece of information, or a choice between alternatives.</p>';
echo '<p>Igbo also has a rich system of pragmatic particles and discourse markers — words and sounds that signal the speaker\'s attitude, signal the beginning or end of a conversational turn, or request confirmation from the listener. These are among the hardest elements of Igbo to learn from written materials alone, because they are primarily features of spoken discourse rather than written grammar.</p>';
echo '</div>';