<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Learning resources, grammars, and tools for Igbo language study.</p>';
echo '<h2>Beginner Resources</h2>';
echo '<ul>';
echo '<li><strong>Igbo Wikibooks</strong> — free online beginner course at en.wikibooks.org/wiki/Igbo</li>';
echo '<li><strong>Ụlọ Akwụkwọ Igbo</strong> — YouTube channels teaching conversational Igbo</li>';
echo '<li><strong>Ikoikoigbo.com</strong> — online Igbo dictionary with audio pronunciation</li>';
echo '<li><strong>Igbo123.com</strong> — structured beginner lessons with audio</li>';
echo '</ul>';
echo '<h2>Grammar References</h2>';
echo '<ul>';
echo '<li><strong>F.C. Ogbalu</strong> — <em>Igbo Language and Culture</em>. Standard school grammar.</li>';
echo '<li><strong>Emenanjo E.N.</strong> — <em>Elements of Modern Igbo Grammar</em>. University-level reference.</li>';
echo '<li><strong>Kay Williamson</strong> — <em>Igbo-English Dictionary</em> (1972). Scholarly dictionary with grammar notes.</li>';
echo '</ul>';
echo '<h2>Proverbs and Oral Literature</h2>';
echo '<ul>';
echo '<li><strong>F.C. Ogbalu</strong> — <em>Ilu Igbo</em>. The standard collection of 1,000+ Igbo proverbs with English translations.</li>';
echo '<li><strong>Chinua Achebe</strong> — proverbs embedded throughout <em>Things Fall Apart</em> with context.</li>';
echo '</ul>';
echo '<h2>Apps and Digital Tools</h2>';
echo '<ul>';
echo '<li><strong>Igbo phrases apps</strong> — available on Android and iOS</li>';
echo '<li><strong>Google Translate</strong> — Igbo is now supported with basic translation</li>';
echo '<li><strong>Igbo keyboard apps</strong> — for typing characters like ị, ọ, ụ on mobile devices</li>';
echo '</ul>';
echo '<h2>For Children</h2>';
echo '<ul>';
echo '<li><strong>Chinua Achebe</strong> — <em>Chike and the River</em> (1966). Igbo cultural context for young readers.</li>';
echo '<li><strong>Igbo children\'s books</strong> — growing collection available through diaspora publishers</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/overview/">Grammar</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/topics/">Daily Usage</a>';
echo '</div></div>';
