<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Igbo in Daily Life</h2>';

echo '<h3>1. Greetings: The Moral Architecture of Conversation</h3>';
echo '<p>Greetings in Igbo are not optional social pleasantries — they are moral obligations. Passing someone without greeting is not merely impolite; it signals a breakdown of the social contract, a refusal to acknowledge the other person\'s humanity. The Igbo greeting system is elaborate, context-sensitive, and carries more social information than its English equivalents.</p>';
echo '<p>Basic time-of-day greetings: <em>Ụtụtụ ọma</em> (good morning), <em>Ehihie ọma</em> (good afternoon), <em>Anyasị ọma</em> (good evening). But these are supplemented by situation-specific greetings: <em>Nnọọ</em> (welcome — to someone arriving), <em>Daalu</em> (thank you / well done — one of the most versatile words in Igbo), <em>Ndewo</em> (respectful greeting — particularly to elders), <em>Kedu</em> (how are you — central and western Igbo), <em>Ọ dị mma</em> (I am fine — the standard response). The choice of greeting signals the speaker\'s awareness of context, their respect for the person being greeted, and their social competence.</p>';
echo '<p>Greetings also mark activities: <em>Daalu ọrụ</em> (well done for your work — said to someone working), <em>Daalu nri</em> (well done for the food — said to someone cooking or eating), <em>Daalu ije</em> (well done for the journey — said to a traveller). These activity-specific greetings acknowledge the other person\'s effort and presence in a way that English\'s generic "hi" does not.</p>';

echo '<h3>2. Names and Their Meanings</h3>';
echo '<p>Igbo names are a compressed theology, philosophy, and biography. They encode the circumstances of birth, the parents\' relationship to the divine, the family\'s aspirations, and the community\'s values in a form that the named person carries through life. Understanding Igbo names is understanding Igbo worldview in miniature.</p>';
echo '<p>Theophoric names — names that reference <em>Chukwu</em> (God) or <em>Chi</em> (personal divine force): <em>Chukwuemeka</em> (God has done great things), <em>Chukwuebuka</em> (God is greatest), <em>Chidinma</em> (God is good), <em>Chidiebere</em> (God is merciful), <em>Chikamara</em> (God knows best), <em>Ifeanyi</em> (nothing is like God). Names referencing the father: <em>Nnaemeka</em> (father has done great things), <em>Nnabugwu</em> (father is honour). Names referencing circumstances of birth: <em>Mgbeke</em> (born on Eke market day), <em>Nwafor</em> (child of Afor market day), <em>Obiageli</em> (one who came to enjoy wealth). Names expressing philosophical positions: <em>Nwosu</em> (people are important), <em>Nkiruka</em> (the future is greater), <em>Adaeze</em> (daughter of a king).</p>';
echo '<p>The naming system also includes names given at different stages of life: childhood names, names earned through title-taking, praise names given by admirers, and names adopted in old age. A person\'s full name — including all these layers — is a biography of their achievements and social relationships.</p>';

echo '<h3>3. Proverbs: The Currency of Igbo Rhetoric</h3>';
echo '<p>Chinua Achebe wrote: "Among the Igbo the art of conversation is regarded very highly, and proverbs are the palm-oil with which words are eaten." This is not merely a poetic observation — it is a description of how Igbo rhetorical practice works. Proverbs (<em>ilu</em>) are cited in courts, at meetings, in negotiations, at ceremonies, and in everyday conversation as authoritative references. They carry legal, ethical, and philosophical weight.</p>';
echo '<p>Selected proverbs with translations and commentary: <em>Onye wetara oji wetara ndụ</em> (He who brings kola brings life) — the foundational statement of Igbo hospitality and the significance of the kola nut ritual. <em>Egbe bere ugo bere; nke si ibe ya ebena nku kwa ya</em> (Let the kite perch and let the eagle perch; whichever denies the other permission to perch, let its wing break) — a statement of the principle of live-and-let-live, of political pluralism. <em>Onye kwe, chi ya ekwe</em> (If a person agrees, their chi agrees) — the Igbo account of the relationship between human will and spiritual destiny. <em>Ọ bụ oge onye okenye nwụọ ka ụlọ ọ gbaa ọkụ</em> (When an elder dies, a library burns) — the value placed on oral knowledge and the elder as its custodian.</p>';

echo '<h3>4. Code-Switching: Igbo in the Contemporary World</h3>';
echo '<p>The language of everyday life in contemporary Igboland — and in the diaspora — is rarely pure Igbo. It is a fluid mixture of Igbo, Nigerian Pidgin, English, and in some contexts Yoruba, that switches registers and languages mid-sentence in patterns that linguists call code-switching. Understanding this mixture is essential to understanding how Igbo is actually used today.</p>';
echo '<p>Code-switching is not a sign of linguistic incompetence. It is a sophisticated communicative strategy that signals social identity, adjusts register to context, fills lexical gaps (particularly for modern concepts and objects), and manages the social relationships between speakers of different linguistic backgrounds. A young Igbo professional in Lagos may speak Igbo with their parents, Pidgin with colleagues at work, English in formal meetings, and a fluid mixture of all three with friends — all within the same day. Each switch carries social meaning.</p>';
echo '<p>The diaspora adds further complexity. Second-generation Igbo in the UK or USA often have receptive competence in Igbo (they understand it) but limited productive competence (they cannot easily speak it). Their Igbo is often mixed with significant English vocabulary, simplified in grammatical complexity, and different in tone from the Igbo spoken in Igboland. This diaspora Igbo is not degraded Igbo; it is Igbo adapting to a new context, as languages always do.</p>';

echo '<h3>5. Igbo Language Revitalisation: Practical Strategies</h3>';
echo '<p>Igbo language revitalisation — reversing the decline of Igbo transmission across generations — is one of the most important cultural projects of the contemporary Igbo community. The practical strategies being employed include: community language schools in diaspora cities (London, Houston, Toronto, Atlanta) that teach children Igbo on weekends; YouTube channels and podcast series that teach conversational Igbo to diaspora adults; social media communities that commit to Igbo-language communication; apps that gamify Igbo vocabulary learning; and institutional programmes at the University of Nigeria Nsukka and other universities that train Igbo language teachers.</p>';
echo '<p>The most effective revitalisation strategies share certain features: they prioritise spoken Igbo over written Igbo (the spoken language is the living language); they use culturally meaningful content (proverbs, names, greetings, songs) rather than decontextualised grammar exercises; they connect language learning to cultural identity (learning Igbo is learning to be Igbo); and they create communities of practice in which learners can use the language with each other, not just with teachers. Language is social; it cannot be revitalised in isolation.</p>';
echo '</div>';