<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Igbo in daily life — conversations, social situations, and common expressions.</p>';
echo '<h2>Greetings — The Foundation of Igbo Social Life</h2>';
echo '<p>Greetings in Igbo are not optional pleasantries — they are moral obligations. Passing someone without greeting is considered rude and antisocial. The type of greeting varies by time of day, relative age, and social context:</p>';
echo '<ul>';
echo '<li><strong>Ụtụtụ ọma</strong> — Good morning</li>';
echo '<li><strong>Ehihie ọma</strong> — Good afternoon</li>';
echo '<li><strong>Anyasị ọma</strong> — Good evening</li>';
echo '<li><strong>Ọ dịịrị gị mma</strong> — How has your day been? (lit: has it been well for you?)</li>';
echo '<li><strong>I meela</strong> — Well done / You have done well</li>';
echo '<li><strong>Nnọọ</strong> — Welcome (said to a visitor)</li>';
echo '<li><strong>Daalu ọbia gị</strong> — Thank you for coming</li>';
echo '</ul>';
echo '<h2>At the Market</h2>';
echo '<ul>';
echo '<li><strong>Ole ego?</strong> — How much?</li>';
echo '<li><strong>Ọ dị ọnụ ike</strong> — It is too expensive</li>';
echo '<li><strong>Denye ya ọnụ</strong> — Reduce the price</li>';
echo '<li><strong>A ga m azụta ya</strong> — I will buy it</li>';
echo '<li><strong>A chọghị m</strong> — I do not want it</li>';
echo '<li><strong>Nye m</strong> — Give me</li>';
echo '<li><strong>Daalụ</strong> — Thank you</li>';
echo '</ul>';
echo '<h2>Family and Kinship Terms</h2>';
echo '<ul>';
echo '<li><strong>Nna</strong> — Father</li>';
echo '<li><strong>Nne</strong> — Mother</li>';
echo '<li><strong>Nna ochie</strong> — Grandfather</li>';
echo '<li><strong>Nne ochie</strong> — Grandmother</li>';
echo '<li><strong>Nwa</strong> — Child</li>';
echo '<li><strong>Nwanne</strong> — Sibling / Kinsperson</li>';
echo '<li><strong>Di</strong> — Husband</li>';
echo '<li><strong>Nwunye</strong> — Wife</li>';
echo '<li><strong>Ụmụnna</strong> — Patrilineage / Extended family (male line)</li>';
echo '<li><strong>Ụmụada</strong> — Daughters of the lineage</li>';
echo '</ul>';
echo '<h2>Food and Eating</h2>';
echo '<ul>';
echo '<li><strong>Ji</strong> — Yam (the most important food in Igbo culture)</li>';
echo '<li><strong>Ofe</strong> — Soup / Stew</li>';
echo '<li><strong>Ofe onugbu</strong> — Bitter leaf soup</li>';
echo '<li><strong>Ofe oha</strong> — Ora leaf soup</li>';
echo '<li><strong>Ofe egusi</strong> — Melon seed soup</li>';
echo '<li><strong>Garị</strong> — Processed cassava (staple food)</li>';
echo '<li><strong>Ọjị</strong> — Kola nut (ritual significance)</li>';
echo '<li><strong>Mmanya ọcha</strong> — Palm wine (lit: white drink)</li>';
echo '<li><strong>Rie ihe</strong> — Eat food</li>';
echo '<li><strong>Ụọ m agụọ m oyi</strong> — I am hungry / thirsty</li>';
echo '</ul>';
echo '<h2>Common Expressions and Proverbs</h2>';
echo '<ul>';
echo '<li><strong>Onye wetara oji wetara ndụ</strong> — He who brings kola brings life</li>';
echo '<li><strong>Egbe bere, ugo bere</strong> — Let the kite perch, let the eagle perch (live and let live)</li>';
echo '<li><strong>Onye kwe, chi ya ekwe</strong> — When a person agrees, their chi agrees (willpower matters)</li>';
echo '<li><strong>Aka nri kwọọ aka ekpe, aka ekpe akwọọ aka nri</strong> — The right hand washes the left, the left washes the right (mutual support)</li>';
echo '<li><strong>Ihe onye metara ya</strong> — What one has done to oneself (you reap what you sow)</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/overview/">Grammar</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language2/sources/">Resources</a>';
echo '</div></div>';
