<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">The broad sweep of African history — civilizations, trade, colonization, independence, and the contemporary continent.</p>';
echo '<h2>The Oldest Human Story</h2>';
echo '<p>Africa is the origin of humanity. Every human being alive today descends from ancestors who lived in Africa. The genetic, archaeological, and fossil evidence is unambiguous: Homo sapiens emerged in Africa approximately 300,000 years ago, and from Africa spread to populate every other continent. This is not merely a historical fact but a philosophical one: Africa is not peripheral to human history — it is its source.</p>';
echo '<p>Africa is also the world\'s second largest continent by area (30.37 million km²) and second most populous (1.4 billion people). It contains 54 recognized countries, approximately 2,000 languages, and extraordinary ecological diversity — from the Sahara desert to the Congo rainforest, from the East African Rift Valley savannah to the Cape of Good Hope. No single narrative can encompass Africa\'s diversity; what follows is an orientation, not a summary.</p>';
echo '<h2>Pre-Colonial African Civilizations</h2>';
echo '<p>One of the most persistent myths of colonial historiography was the claim that Africa had no history before European contact — that it was a "dark continent" of stateless peoples without civilization. This claim was false and self-serving. Africa had sophisticated states, complex trade networks, great cities, advanced metallurgy, philosophical traditions, and artistic achievements thousands of years before European contact.</p>';
echo '<h3>Ancient Africa</h3>';
echo '<ul>';
echo '<li><strong>Kemet (Ancient Egypt)</strong> — c. 3100–30 BCE; one of the world\'s first and most enduring civilizations; the pyramids, the Great Sphinx, hieroglyphic writing, advanced mathematics and medicine, the Book of the Dead. Egypt\'s African identity — its connections to sub-Saharan Africa through Nubia and the Nile corridor — has been contested by Eurocentric scholarship but is affirmed by genetics, archaeology, and the ancient Egyptians\' own self-description.</li>';
echo '<li><strong>Nubia / Kush</strong> — c. 2500 BCE–350 CE; the civilization of the upper Nile; at its height (c. 750–650 BCE), Nubian pharaohs (the 25th dynasty) ruled all of Egypt; remarkable pyramids survive at Meroe in modern Sudan</li>';
echo '<li><strong>Axum (Ethiopia)</strong> — c. 100–940 CE; one of the great civilizations of the ancient world; controlled trade between the Roman Empire and India through the Red Sea; adopted Christianity in the 4th century CE — making Ethiopia one of the world\'s oldest Christian nations; the obelisks of Axum are among Africa\'s greatest monuments</li>';
echo '</ul>';
echo '<h3>Medieval and Early Modern African States</h3>';
echo '<ul>';
echo '<li><strong>Mali Empire</strong> (c. 1235–1600) — West Africa; at its height the wealthiest state in the world; Mansa Musa\'s 1324 pilgrimage to Mecca — during which he distributed so much gold that it caused inflation across North Africa and the Middle East — is the most documented demonstration of African wealth in the medieval period; the city of Timbuktu was a center of Islamic scholarship with universities attracting students from across the Muslim world</li>';
echo '<li><strong>Songhai Empire</strong> (c. 1464–1591) — West Africa; succeeded Mali as the dominant Sahelian power; Askia Muhammad\'s reign (1493–1528) saw the empire at its greatest extent; fell to Moroccan invasion</li>';
echo '<li><strong>Great Zimbabwe</strong> (c. 1100–1450) — southern Africa; a stone-walled city that was the capital of a sophisticated trading state controlling the gold trade between interior Africa and the Swahili coast; European colonizers refused to believe Africans had built it — a denial disproved by modern archaeology</li>';
echo '<li><strong>Kongo Kingdom</strong> (c. 1390–1914) — Central Africa (modern DRC, Angola, Congo); a highly organized state with a sophisticated administrative system; converted to Christianity in 1491; its ruler (Manikongo) was treated as an equal by Portuguese kings; devastated by the Atlantic slave trade</li>';
echo '<li><strong>Benin Kingdom</strong> (c. 1180–1897) — southwestern Nigeria; famous for its bronze castings, which represent among the finest metalwork in the world; the Obas of Benin maintained a sophisticated court culture; the kingdom was destroyed by a British "punitive expedition" in 1897 which looted thousands of bronzes now held in Western museums</li>';
echo '<li><strong>Oyo Empire</strong> (c. 1400–1836) — Yoruba, southwestern Nigeria; at its height controlled a large territory through a sophisticated cavalry-based military; a major power in the Atlantic slave trade</li>';
echo '<li><strong>Kanem-Bornu</strong> (c. 700–1900) — Lake Chad region; one of the longest-surviving states in African history; connected to trans-Saharan trade routes</li>';
echo '<li><strong>Swahili City-States</strong> (c. 900–1500) — East African coast; Mombasa, Kilwa, Zanzibar, Sofala; cosmopolitan trading cities connecting the African interior to Arabia, Persia, India, and China; predominantly Muslim; the Swahili language and culture emerged from this Indian Ocean commercial world</li>';
echo '<li><strong>Ethiopian Empire</strong> — continuous from ancient Axum through the Solomonic dynasty (1270–1974); the only African state to defeat a European colonial power in battle (Battle of Adwa, 1896, defeating Italy); Haile Selassie\'s reign (1930–1974) and his assassination of the Pan-African movement are central to modern African history</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/topics/">Key Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/people/">Key Figures</a>';
echo '</div></div>';
