<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Key figures in African history — leaders, intellectuals, and freedom fighters.</p>';
echo '<h2>Ancient and Medieval Africa</h2>';
echo '<ul>';
echo '<li><strong>Mansa Musa (c. 1280–1337)</strong> — Emperor of Mali; the wealthiest individual in human history by some estimates; his 1324 hajj to Mecca — accompanied by 60,000 men and 500 slaves each carrying gold — announced Africa\'s wealth to the world</li>';
echo '<li><strong>Queen Nzinga (1583–1663)</strong> — Queen of Ndongo and Matamba (modern Angola); fought the Portuguese slave trade for four decades; a brilliant military and diplomatic strategist; one of the great African resistance leaders of any era</li>';
echo '<li><strong>Shaka Zulu (c. 1787–1828)</strong> — founder of the Zulu Kingdom; transformed a small chieftaincy into the most powerful state in southern Africa through military innovation; his legacy is complex — admired for military genius, criticized for brutal methods</li>';
echo '</ul>';
echo '<h2>Anti-Colonial Resistance</h2>';
echo '<ul>';
echo '<li><strong>Yaa Asantewaa (c. 1840–1921)</strong> — Queen Mother of Ejisu (Ashanti, Ghana); led the Ashanti uprising against British rule in 1900 (the "War of the Golden Stool"); captured and exiled; a symbol of female African resistance</li>';
echo '<li><strong>Samori Touré (c. 1830–1900)</strong> — West African leader who built a large empire and resisted French colonization for 16 years (1882–1898); ultimately captured and exiled; grandfather of Sékou Touré</li>';
echo '<li><strong>Menelik II (1844–1913)</strong> — Emperor of Ethiopia who defeated Italy at the Battle of Adwa (1896) — the only African victory against a European colonial power in the Scramble for Africa; his victory made Ethiopia a symbol of African dignity and independence</li>';
echo '</ul>';
echo '<h2>Independence Leaders</h2>';
echo '<ul>';
echo '<li><strong>Kwame Nkrumah (1909–1972)</strong> — Ghana; architect of Ghanaian independence and Pan-Africanism; his vision of a United States of Africa was never realized but remains inspirational</li>';
echo '<li><strong>Jomo Kenyatta (c. 1897–1978)</strong> — Kenya; imprisoned by the British for his role in the Mau Mau uprising; became Kenya\'s first President; his book <em>Facing Mount Kenya</em> (1938) is a landmark in African anthropology</li>';
echo '<li><strong>Julius Nyerere (1922–1999)</strong> — Tanzania; one of Africa\'s most respected leaders; developed the philosophy of Ujamaa (African socialism); voluntarily stepped down from power in 1985; his intellectual integrity set a standard rarely matched in African politics</li>';
echo '<li><strong>Patrice Lumumba (1925–1961)</strong> — Congo; murdered 12 weeks after independence with Western complicity; became a martyr of African liberation</li>';
echo '<li><strong>Nelson Mandela (1918–2013)</strong> — South Africa; imprisoned 27 years for opposing apartheid; emerged to lead South Africa\'s transition to democracy; his moral authority and commitment to reconciliation made him the most celebrated African political figure of the late 20th century</li>';
echo '</ul>';
echo '<h2>Intellectuals and Writers</h2>';
echo '<ul>';
echo '<li><strong>Cheikh Anta Diop (1923–1986)</strong> — Senegal; historian who argued for the African origin of Egyptian civilization; his work is the foundation of Afrocentric scholarship</li>';
echo '<li><strong>Frantz Fanon (1925–1961)</strong> — Martinique/Algeria; psychiatrist and philosopher whose <em>The Wretched of the Earth</em> (1961) is the foundational text of post-colonial theory and anti-colonial politics</li>';
echo '<li><strong>Chinua Achebe (1930–2013)</strong> — Nigeria/Igbo; the most celebrated African novelist; see the Culture and History sections for full treatment</li>';
echo '<li><strong>Wole Soyinka (b. 1934)</strong> — Nigeria/Yoruba; first African Nobel Laureate in Literature (1986); playwright, poet, and intellectual; imprisoned during the Biafran war for attempting to mediate</li>';
echo '<li><strong>Ngugi wa Thiong\'o (b. 1938)</strong> — Kenya; novelist and theorist who abandoned English to write in Gikuyu as a political act; his <em>Decolonising the Mind</em> (1986) is essential reading on language and colonial power</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/overview/">Overview</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/sources/">Sources</a>';
echo '</div></div>';
