<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Figures of African History</h2>';
echo '<h3>Mansa Musa (c.1280–1337)</h3>';
echo '<p>Mansa Musa, Emperor of the Mali Empire, is the most documented demonstration of African wealth and political power in the medieval world. His 1324 hajj to Mecca — accompanied by a retinue estimated at 60,000 people, 500 slaves each carrying a staff of gold, and 100 camels each carrying 300 pounds of gold dust — was not merely a religious pilgrimage but a political statement. He distributed so much gold along the route that he caused inflation in Egypt and across North Africa that persisted for more than a decade. He built mosques in Cairo. He brought back Arab architects who designed the Djinguereber mosque in Timbuktu, which stands to this day. His reign represents the height of an empire that controlled the trans-Saharan gold trade, sustained one of the world\'s great centres of Islamic scholarship, and demonstrated that African political and economic sophistication was, in the 14th century, comparable to or exceeding that of any contemporary state in the world.</p>';
echo '<h3>Queen Nzinga (1583–1663)</h3>';
echo '<p>Nzinga Mbande, Queen of Ndongo and Matamba in what is now Angola, was the most significant African female military and diplomatic leader of the early modern period. She spent four decades navigating between negotiation and armed resistance against Portuguese colonial pressure with extraordinary skill — converting to Christianity as a diplomatic manoeuvre, then leading military resistance when diplomacy failed, building military alliances with the Dutch against the Portuguese, and creating a warrior kingdom in Matamba that resisted Portuguese colonisation until after her death. She was in her seventies when she negotiated a peace treaty with Portugal from a position of strength. Her life represents a form of African female leadership — combining military command, diplomatic sophistication, religious flexibility, and political will — that colonial historiography systematically suppressed and that African feminism has been recovering.</p>';
echo '<h3>Patrice Lumumba (1925–1961)</h3>';
echo '<p>Patrice Lumumba was the first Prime Minister of the Democratic Republic of Congo and the most significant martyr of African independence. In his independence speech — delivered in the presence of King Baudouin of Belgium — he gave an unrehearsed account of what colonialism had actually done: the forced labour, the humiliations, the killings, the theft. It was the most honest speech delivered at any African independence ceremony, and it made him a marked man. Twelve weeks after independence, he was overthrown in a coup supported by Belgium and the CIA, arrested, transferred to Katanga province, and murdered by Katangese forces with Belgian officers present. Belgium returned his tooth — the only physical remnant of his body — to his family in 2022, 61 years after his murder. Lumumba\'s significance is not primarily what he achieved but what his murder reveals: that Belgium and the United States decided within weeks of Congolese independence that his vision of genuine sovereignty was incompatible with their interests, and they destroyed him. The pattern — African leader with genuine independence agenda, Western intervention, replacement with compliant client — was repeated across the continent in the 1960s.</p>';
echo '<h3>Thomas Sankara (1949–1987)</h3>';
echo '<p>Thomas Sankara was President of Burkina Faso from 1983 to 1987 — four years in which he attempted to demonstrate that African governance could be honest, competent, anti-corruption, feminist, and oriented toward the governed. He renamed his country from Upper Volta to Burkina Faso ("Land of Upright People"), implemented Africa\'s first comprehensive vaccination programme, promoted women\'s rights, reduced government corruption, planted millions of trees, and refused World Bank and IMF structural adjustment loans on the grounds that accepting them meant accepting the creditors\' political conditions. He was assassinated at 37 in a coup backed by France and Côte d\'Ivoire. His legacy has become the central reference point for a generation of African youth activists. His statement "He who feeds you controls you" has become the intellectual foundation of a new generation of African economic nationalism.</p>';
echo '<h3>Wangari Maathai (1940–2011)</h3>';
echo '<p>Wangari Maathai was a Kenyan environmental activist, academic, and politician who founded the Green Belt Movement in 1977 — a grassroots organisation that mobilised Kenyan women to plant trees, combat deforestation, and resist the land alienation that was destroying both the environment and rural communities\' livelihoods. She was arrested multiple times by the Moi government, beaten, and imprisoned for her activism. She was awarded the Nobel Peace Prize in 2004 — the first African woman to receive it. She is included in this subject because she represents a form of African political resistance rooted in environmental consciousness, women\'s organising, and the connection between ecological health and political freedom that standard narratives of African independence and Pan-Africanism consistently marginalise. The Africa that Maathai defended was not an abstraction but a landscape, and the people she organised were not a political vanguard but rural women with hoes.</p>';
echo '<h3>Chinua Achebe (1930–2013)</h3>';
echo '<p>Chinua Achebe belongs in the Africa subject as much as in any Igbo subject because his argument was always continental. <em>Things Fall Apart</em> (1958) was written in response to the colonial representation of Africa in European literature — specifically Joseph Conrad\'s <em>Heart of Darkness</em> (1899), which Achebe called "a thoroughgoing racist novel." His counter was not an argument but a novel: a fictional world so fully realised that it made Conrad\'s Africa impossible to sustain. <em>Things Fall Apart</em> has sold over 20 million copies in 57 languages. It is taught in secondary schools on every continent. Its argument — that Africans had complex, coherent, sophisticated societies before colonialism arrived — has reached more people than any political speech, any academic paper, any UN resolution. Achebe did with fiction what political Pan-Africanism attempted with institutions: he changed what the world believed about Africa.</p>';
echo '</div>';