<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Essential references for African history and pan-Africanism.</p>';
echo '<h2>African History</h2>';
echo '<ul>';
echo '<li><strong>John Reader</strong> — <em>Africa: A Biography of the Continent</em> (1997). The most accessible comprehensive single-volume history of Africa.</li>';
echo '<li><strong>Basil Davidson</strong> — <em>Africa in History</em> (1966, rev. 1991). The pioneering popular history that challenged colonial myths about African statelessness.</li>';
echo '<li><strong>UNESCO General History of Africa</strong> (8 volumes, 1981–1993). The most comprehensive scholarly history of Africa; written by African historians.</li>';
echo '<li><strong>Philip Curtin et al.</strong> — <em>African History: From Earliest Times to Independence</em> (1995). Standard academic introduction.</li>';
echo '</ul>';
echo '<h2>Pre-Colonial Civilizations</h2>';
echo '<ul>';
echo '<li><strong>D.T. Niane</strong> — <em>Sundiata: An Epic of Old Mali</em> (1965). The founding epic of the Mali Empire.</li>';
echo '<li><strong>Ibn Battuta</strong> — <em>Travels in Asia and Africa</em> (14th century). The greatest medieval traveler\'s account of West and East African states.</li>';
echo '<li><strong>David Conrad and Barbara Frank</strong> — <em>Status and Identity in West Africa: Nyamakalaw of Mande</em> (1995).</li>';
echo '</ul>';
echo '<h2>The Slave Trades</h2>';
echo '<ul>';
echo '<li><strong>Hugh Thomas</strong> — <em>The Slave Trade</em> (1997). Comprehensive history of the Atlantic slave trade.</li>';
echo '<li><strong>Paul Lovejoy</strong> — <em>Transformations in Slavery</em> (1983). The standard academic history of African slavery.</li>';
echo '<li><strong>Slave Voyages Database</strong> — slavevoyages.org — comprehensive free database.</li>';
echo '</ul>';
echo '<h2>Colonialism</h2>';
echo '<ul>';
echo '<li><strong>Adam Hochschild</strong> — <em>King Leopold\'s Ghost</em> (1998). The definitive popular account of Congo atrocities under Leopold II.</li>';
echo '<li><strong>Walter Rodney</strong> — <em>How Europe Underdeveloped Africa</em> (1972). The foundational text of African dependency theory.</li>';
echo '<li><strong>Frantz Fanon</strong> — <em>The Wretched of the Earth</em> (1961). The canonical text of anti-colonial theory. Free: <a href="https://archive.org/search?query=fanon+wretched+earth" target="_blank" rel="noopener">archive.org</a></li>';
echo '</ul>';
echo '<h2>Pan-Africanism and Independence</h2>';
echo '<ul>';
echo '<li><strong>W.E.B. Du Bois</strong> — <em>The Souls of Black Folk</em> (1903). Foundational Pan-Africanist text. Free: <a href="https://sacred-texts.com/afr/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '<li><strong>Kwame Nkrumah</strong> — <em>Africa Must Unite</em> (1963). The Pan-Africanist vision for continental unity.</li>';
echo '<li><strong>Cheikh Anta Diop</strong> — <em>The African Origin of Civilization</em> (1974). Afrocentric historical revisionism at its most scholarly.</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/topics/">Topics</a>';
echo '</div></div>';
