<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Key topics in African history — the slave trade, colonization, independence, and pan-Africanism.</p>';
echo '<h2>The Trans-Saharan and Atlantic Slave Trades</h2>';
echo '<p>Africa\'s encounter with the slave trade was not a single event but a series of overlapping catastrophes spanning more than a millennium:</p>';
echo '<ul>';
echo '<li><strong>The Trans-Saharan slave trade</strong> (c. 650–1900 CE) — Arab merchants transported an estimated 17 million Africans across the Sahara and the Red Sea to North Africa, the Middle East, and the Persian Gulf over 1,300 years. This trade is less well-documented than the Atlantic trade but comparable in scale over its much longer duration. Enslaved Africans in the Arab world were used as soldiers, servants, concubines, and agricultural laborers. The trade intensified during periods of high Arab demand and continued in parts of the Sahel into the early 20th century.</li>';
echo '<li><strong>The Atlantic slave trade</strong> (c. 1500–1870) — approximately 12.5 million Africans were transported to the Americas; 10.7 million survived the Middle Passage. The economic consequences for Africa were catastrophic: entire coastal societies were reorganized around slave raiding and trading; wars between African states became more frequent and more oriented toward capturing people for sale; agricultural and craft production was disrupted; population growth was stunted. The Bight of Biafra alone exported approximately 1.6 million people.</li>';
echo '</ul>';
echo '<h2>The Berlin Conference and Colonization</h2>';
echo '<p>The Berlin Conference of 1884–1885 was convened by Otto von Bismarck to regulate European competition for African territory. Representatives of 14 European states (and the USA) divided Africa among themselves without the participation of a single African. The "Scramble for Africa" that followed was the most rapid and comprehensive territorial seizure in human history: by 1914, only Ethiopia and Liberia remained independent. The rest of Africa — over 30 million square kilometers — was under European colonial rule.</p>';
echo '<p>Colonization involved:</p>';
echo '<ul>';
echo '<li><strong>Military conquest</strong> — often achieved through the technological advantage of the Maxim gun against African armies armed with older weapons; but African resistance was often fierce and prolonged (the Zulu at Isandlwana 1879, the Ethiopians at Adwa 1896, the Igbo Ekumeku resistance 1898–1911, the Herero uprising in German South West Africa 1904–1908)</li>';
echo '<li><strong>Economic extraction</strong> — colonial economies were designed to extract raw materials (rubber, cotton, palm oil, minerals, timber) for export to Europe; African labor was coerced through taxation (forcing Africans to earn cash by working for colonial enterprises), land alienation, and direct forced labor</li>';
echo '<li><strong>Administrative restructuring</strong> — existing African political systems were either destroyed or co-opted through "indirect rule" (governing through existing elites, as in northern Nigeria) or replaced with entirely new administrative structures</li>';
echo '<li><strong>Cultural assault</strong> — missionary Christianity and Islam spread rapidly under colonial conditions; African languages were marginalized in education and administration; indigenous knowledge systems were dismissed as primitive</li>';
echo '</ul>';
echo '<h2>The Congo: The Worst of Colonialism</h2>';
echo '<p>The Congo Free State (1885–1908) under Belgian King Leopold II represents the most extreme case of colonial atrocity. Leopold\'s personal colony — run as a private enterprise — extracted rubber through a system of terror: Congolese villages were given rubber quotas; failure to meet quotas resulted in the severing of hands (children\'s hands were particularly targeted as proof of rubber-quota enforcement); an estimated 10 million people died from murder, starvation, and disease under Leopold\'s rule. The Congo atrocities, exposed by journalists and campaigners including E.D. Morel and Roger Casement, generated the first international human rights campaign and forced Belgium to take over the colony in 1908 — though Belgian rule remained exploitative.</p>';
echo '<h2>Independence Movements (1950s–1970s)</h2>';
echo '<p>African independence came in waves:</p>';
echo '<ul>';
echo '<li><strong>Libya</strong> 1951 — first sub-Saharan African state to gain independence in the post-war era</li>';
echo '<li><strong>Ghana</strong> 1957 — under Kwame Nkrumah; the first sub-Saharan African state to achieve independence; Nkrumah\'s declaration "Ghana is free forever!" electrified the continent</li>';
echo '<li><strong>Guinea</strong> 1958 — Sékou Touré chose independence over French Community membership; France responded by stripping Guinea of everything movable, including phone books</li>';
echo '<li><strong>The Year of Africa — 1960</strong> — 17 African states achieved independence in a single year, including Nigeria, Senegal, Ivory Coast, Cameroon, Congo, and Mali</li>';
echo '<li><strong>East Africa</strong> — Tanzania 1961, Uganda 1962, Kenya 1963</li>';
echo '<li><strong>Southern Africa</strong> — the last to be decolonized; Angola and Mozambique 1975 (after Portuguese revolution); Zimbabwe 1980; Namibia 1990; South Africa ended apartheid 1994</li>';
echo '</ul>';
echo '<h2>Pan-Africanism</h2>';
echo '<p>Pan-Africanism — the intellectual and political movement asserting the unity of African peoples worldwide — is one of the most important political philosophies of the 20th century. Its key figures:</p>';
echo '<ul>';
echo '<li><strong>W.E.B. Du Bois (1868–1963)</strong> — African-American scholar who organized the first Pan-African Congress (1919) and developed the intellectual framework of Pan-Africanism; he died in Ghana as a Ghanaian citizen</li>';
echo '<li><strong>Marcus Garvey (1887–1940)</strong> — Jamaican Black nationalist who built the largest Black mass movement in history (UNIA — Universal Negro Improvement Association); "Africa for the Africans"; his prophecy about a Black king being crowned in Africa inspired Rastafari</li>';
echo '<li><strong>Kwame Nkrumah (1909–1972)</strong> — first Prime Minister and President of Ghana; the leading pan-Africanist of the independence era; advocated African unity and a United States of Africa; overthrown in 1966</li>';
echo '<li><strong>Patrice Lumumba (1925–1961)</strong> — first Prime Minister of the Congo; murdered with Belgian and CIA involvement 12 weeks after independence; his assassination became a symbol of the neo-colonial forces working against African independence</li>';
echo '<li><strong>Cheikh Anta Diop (1923–1986)</strong> — Senegalese historian who argued that ancient Egyptian civilization was Black African in origin and foundation; his work sparked decades of controversy and significantly influenced Afrocentric scholarship</li>';
echo '<li><strong>Thomas Sankara (1949–1987)</strong> — President of Burkina Faso (1983–1987); the "African Che Guevara"; implemented radical anti-corruption, feminist, and environmentalist policies; assassinated in a coup backed by France and neighboring Ivory Coast; his legacy has experienced a significant revival among African youth</li>';
echo '</ul>';
echo '<h2>Contemporary Africa</h2>';
echo '<p>Today\'s Africa is a continent of extraordinary contradiction: extraordinary natural wealth and persistent poverty; demographic youth and political gerontocracy; technological leapfrogging (mobile money, internet connectivity) and infrastructure deficit; democratic progress and authoritarian backsliding. The African Union (established 2002) represents the institutional expression of Pan-Africanist ideals, though its effectiveness remains limited. China\'s growing economic presence — through infrastructure investment, trade, and loans — has reshaped African geopolitics in ways whose long-term consequences are still unfolding.</p>';
echo '<p>For the Igbo specifically, Africa is not merely context but connection. The Igbo diaspora spans the continent — Igbo communities in South Africa, Ghana, Cameroon, Equatorial Guinea, and elsewhere. The questions that animate Igbo political life — sovereignty, resource control, ethnic rights, the relationship between indigenous peoples and post-colonial states — are African questions, shared by hundreds of millions across the continent.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/overview/">Overview</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/africa/people/">Key Figures</a>';
echo '</div></div>';
