<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Five Sites of African History</h2>';

echo '<h3>1. Pre-Colonial Civilisations: What Europe Did Not Want to Know</h3>';
echo '<p>The systematic misrepresentation of pre-colonial Africa as stateless, primitive, and ahistorical was not an error — it was a political project. Colonial rule required a justification, and the justification required the claim that Africans were incapable of self-governance. This claim was false, and the evidence of its falsity was visible to anyone who looked: the elaborate court culture of the Benin Kingdom, whose bronzes are among the finest metalwork in the world; the university at Timbuktu, whose manuscript libraries held hundreds of thousands of volumes in mathematics, astronomy, jurisprudence, and theology; the administrative sophistication of the Kongo Kingdom, whose rulers corresponded with Portuguese kings as equals; the military innovation of the Zulu Kingdom, whose impi formations defeated British forces at Isandlwana in 1879.</p>';
echo '<p>The recovery of this history — by African historians, by the UNESCO General History of Africa project, by archaeologists working at Great Zimbabwe and Jenne-jeno and Meroe — is not merely academic. It is political. It challenges the foundational claim of colonialism: that European rule was necessary because Africans could not govern themselves. The evidence does not support that claim. The Igbo specifically had, before colonialism, a sophisticated system of decentralised governance — the village assembly, the age-grade system, the women\'s institutions — that the British found illegible precisely because it did not conform to the European model of centralised statehood. Illegibility was not evidence of absence.</p>';

echo '<h3>2. The Berlin Conference: Drawing Lines on Bodies</h3>';
echo '<p>The Berlin Conference of 1884-1885 is the most consequential meeting in African history that no African attended. Convened by Otto von Bismarck to prevent European competition for African territory from producing a European war, it produced the "Scramble for Africa" — the rapid colonisation of the entire continent except Ethiopia and Liberia. The borders that the European powers drew at Berlin and in subsequent treaties were not lines on empty maps: they were lines drawn through existing political systems, ethnic communities, trade networks, and ecological zones. The Igbo, for instance, found themselves inside the British "protectorate" of Southern Nigeria — sharing a colonial entity with the Yoruba, the Hausa-Fulani, the Efik, the Ijaw, and dozens of other peoples whose political traditions, religions, and languages were as different from each other as French from Finnish.</p>';
echo '<p>The post-colonial African state inherited these colonial borders — a decision affirmed by the Organisation of African Unity in 1963 on the principle that border revision would produce endless conflict. The decision was probably pragmatically correct. Its costs are also real: the Nigerian state that the Igbo inhabit is a colonial artefact whose internal contradictions — between north and south, Muslim and Christian, oil-producing minorities and federal majority — were not produced by African agency but by European cartography. Understanding contemporary African political conflicts requires understanding that most African states are not the expressions of existing communities but the containers into which existing communities were compelled to fit.</p>';

echo '<h3>3. The Congo: Colonialism at Its Worst</h3>';
echo '<p>The Congo Free State (1885-1908) under Belgian King Leopold II is the extreme case that reveals what colonialism was — not in its most enlightened self-presentation but in its structural reality. Leopold\'s personal colony — run as a private enterprise for the extraction of rubber and ivory — operated through a system of organised terror. Congolese villages were given rubber quotas. Failure to meet quotas was punished by the severing of hands — documented in photographs that shocked European and American public opinion when they were published. Children\'s hands were collected as proof that the punishment had been carried out. An estimated 10 million people died from murder, starvation, and disease under Leopold\'s rule between 1885 and 1908 — approximately half the pre-colonial population of the Congo.</p>';
echo '<p>The Congo atrocities are important not as an aberration but as an illustration. What made the Congo exceptional was not the violence — comparable violence occurred in German South West Africa, in the Belgian Congo after 1908, in French Equatorial Africa, in British Kenya — but the documentation. E.D. Morel\'s journalism, Roger Casement\'s consular reports, and the photographs of severed hands produced the first international human rights campaign, forcing Belgium to take over the colony from Leopold in 1908. The campaign also demonstrated something that African activists from that era to the present have consistently argued: that the violence of colonialism is not visible unless someone with access to European media and European audiences decides to document it.</p>';

echo '<h3>4. Thomas Sankara and the Politics of Dignity</h3>';
echo '<p>Thomas Sankara — President of Burkina Faso from 1983 to 1987 — represents a dimension of African political history that is neither the pre-colonial past nor the independence-era leadership of Nkrumah and Nyerere, but the generation that inherited independence and attempted to make it real. Sankara renamed his country from Upper Volta (a colonial designation) to Burkina Faso ("Land of Upright People"), implemented Africa\'s first comprehensive vaccination programme, planted millions of trees to combat desertification, promoted women\'s rights in a context where female genital mutilation and forced marriage were common, reduced government salaries (including his own) and corruption, and refused structural adjustment loans from the World Bank and IMF on the grounds that accepting them meant accepting the creditors\' political conditions.</p>';
echo '<p>He was assassinated in October 1987 in a coup backed by France and Côte d\'Ivoire\'s Félix Houphouët-Boigny. He was 37. His legacy — suppressed for decades — has experienced a massive revival among African youth in the 21st century, who see in his four years of governance a demonstration that African leadership can be honest, competent, and oriented toward the governed rather than toward external patrons. His famous statement — "He who feeds you controls you" — captures the dependency analysis that he turned into policy. He is included in this subject not because he was the most important African leader but because he represents what African political possibility has looked like when it has been most seriously attempted.</p>';

echo '<h3>5. Pan-Africanism: The Unfinished Project</h3>';
echo '<p>Pan-Africanism — the intellectual and political movement asserting the unity of African peoples worldwide — is the most significant political philosophy produced by the African experience of slavery, colonialism, and diaspora. Its intellectual origins are in the Caribbean and the United States — in the writings of Edward Wilmot Blyden, W.E.B. Du Bois, Marcus Garvey, and Aimé Césaire — and its political expression was taken up by continental African leaders including Kwame Nkrumah, Julius Nyerere, and Sékou Touré. Its institutional expression is the African Union, successor to the Organisation of African Unity (1963).</p>';
echo '<p>Pan-Africanism as a political programme has not achieved its central goal — the political unification of Africa, or at minimum a common market with genuine economic integration. The African Union remains institutionally weak, underfunded, and dependent on external donors for its peacekeeping and development operations. The dream of a United States of Africa that Nkrumah articulated remains unrealised. What Pan-Africanism has achieved is more diffuse but no less significant: it has created a framework through which African peoples across the globe understand their shared history and their shared stake in African political futures; it has produced an intellectual tradition of extraordinary richness and rigour; and it has sustained, across more than a century of defeat and marginalisation, the argument that Africa\'s story is not over and that its people\'s capacity for self-determination has not been exhausted by the violence done to it.</p>';
echo '</div>';