<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Nigeria: From Colonial Creation to the Present</h2>';

echo '<h3>I. The Colonial Creation (1861–1960)</h3>';
echo '<p>Nigeria did not exist before British colonialism. The territory that became Nigeria was home to hundreds of distinct political communities — the Sokoto Caliphate and its constituent emirates in the north; the Oyo Empire, the Benin Kingdom, and dozens of smaller Yoruba states in the southwest; the Igbo village assemblies and the Nri Kingdom in the southeast; the Efik trading states of the Cross River; the Ijaw communities of the Niger Delta; the Tiv, the Kanuri, the Nupe, and two hundred other peoples across the middle belt and beyond. These communities had their own political systems, their own legal traditions, their own languages, and their own histories of interaction — sometimes cooperative, sometimes violent — that predated British presence by centuries.</p>';
echo '<p>The 1914 amalgamation that created "Nigeria" — named after the Niger River by the journalist Flora Shaw, later Lady Lugard — was an administrative convenience, not a political act of community formation. Lord Lugard\'s "indirect rule" system preserved existing political structures (especially in the north, where the emirate system was highly compatible with British administrative needs) while subordinating them to British authority. The south was administered differently — more directly, with greater missionary and educational penetration. By 1960, when independence came, Nigeria was a single administrative entity with two radically different political cultures, three regionally dominant ethnic groups, and no shared civic tradition that could hold them together.</p>';

echo '<h3>II. Independence and the First Republic (1960–1966)</h3>';
echo '<p>Nigeria became independent on 1 October 1960 under a parliamentary federal system with three regions — North, East, and West — each dominated by its major ethnic group. The First Republic was structurally unstable from its beginning. Regional governments competed for federal resources and federal appointments. The 1962 Action Group crisis — in which Awolowo was arrested for treasonable felony and the Western Region was placed under a state of emergency — demonstrated that the federal government could be weaponised against political opponents. The 1963–64 census controversy, in which the north claimed a population majority that southerners disputed, established demographic manipulation as a tool of political competition. The 1964–65 federal elections were marked by widespread violence and fraud.</p>';
echo '<p>By January 1966, the civilian order had lost legitimacy. The coup of 15 January 1966 — led by a group of predominantly Igbo majors, killing the Prime Minister (Balewa), the Northern Premier (Ahmadu Bello), and the Western Premier (Akintola) but leaving the Eastern Premier (Okpara) and most Igbo senior officers alive — was experienced in the north as an Igbo coup. Whether it was — the evidence for ethnic motivation is mixed — it was perceived as one, and that perception drove what followed: the counter-coup of July 1966, the pogroms of September-October 1966, and the logic that led to Biafra.</p>';

echo '<h3>III. Military Rule and the Civil War (1966–1979)</h3>';
echo '<p>The Gowon government (1966–1975) that emerged from the July counter-coup faced the immediate challenge of Igbo secession. The Aburi Accord of January 1967 — which proposed a loose confederation — was repudiated by the federal government under pressure from northern officers and British advisers. Biafra declared independence on 30 May 1967. The war that followed lasted thirty months and produced between one and three million deaths, the majority from the federal food blockade. The war ended in January 1970 with Biafra\'s collapse.</p>';
echo '<p>Post-war Nigeria was transformed by oil. The 1970s oil boom — Nigeria\'s oil revenues multiplied by a factor of ten between 1970 and 1980 — created a federal government of enormous resources and enormous corruption. Gowon was overthrown in 1975 by Murtala Muhammed, who was assassinated in 1976 and succeeded by Obasanjo, who handed power to a civilian government (Shagari) in 1979. The Second Republic lasted until 1983, when Buhari staged another coup. Babangida followed in 1985, ruling until 1993 through a period of sustained corruption and political manipulation. His annulment of the June 12, 1993 election — won by Moshood Abiola — produced the worst political crisis since the civil war. Abacha seized power, ruled through terror and looting until his death in 1998, and was succeeded by Abdulsalami Abubakar, who supervised the transition to civilian rule in 1999.</p>';

echo '<h3>IV. The Fourth Republic (1999–present)</h3>';
echo '<p>The return to civilian rule in 1999 under Olusegun Obasanjo (1999–2007) began a period of continuous democratic governance that has now lasted over 25 years — longer than any previous civilian period in Nigerian history. But the quality of that democracy has been consistently poor: elections are regularly marred by violence, fraud, and manipulation; the judiciary is compromised; the Independent National Electoral Commission (INEC) has never fully established its independence from the ruling party; and the rotation of power between north and south — the informal agreement that has structured presidential succession — has not resolved the ethnic arithmetic that drives Nigerian politics.</p>';
echo '<p>The Yar\'Adua presidency (2007–2010) was cut short by his illness and death. Jonathan (2010–2015) was the first president from the Niger Delta, and his administration was marked by significant corruption and the rise of Boko Haram. Buhari (2015–2023) was a return to northern Muslim leadership, marked by authoritarian tendencies, the worsening of Boko Haram, and the emergence of herdsmen attacks on farming communities across the Middle Belt and southeast. The 2023 election — in which Peter Obi\'s Labour Party candidacy attracted unprecedented cross-ethnic youth support — demonstrated both the frustration with the APC-PDP duopoly and the structural limits of that frustration within the existing electoral framework.</p>';

echo '<h3>V. The Igbo Question: Unresolved</h3>';
echo '<p>Fifty years after the end of the Biafra War, the structural conditions that produced it have not been resolved. The Igbo have not held the presidency since Aguiyi-Ironsi\'s six months in 1966 (before his assassination). Federal infrastructure investment in the Southeast has been consistently below the national average. The Nigerian Army remains dominated by northern officers. Oil revenues from the Niger Delta — much of which is in Igbo and Ijaw territory — are distributed by a formula that disadvantages producing states. The wounds of the war — the abandoned property, the twenty-pound bank limit, the federal reconstruction that bypassed the Igbo heartland — have never been honestly acknowledged by the Nigerian state.</p>';
echo '<p>The IPOB movement, the sit-at-home orders, and the continuing resonance of Biafran nationalism fifty years after the war\'s end are all expressions of this unresolved situation. They are not the cause of Igbo marginalisation; they are its consequence. Understanding Nigeria requires understanding this: that the Nigerian state has a debt to the Igbo people that it has not paid, and that the Igbo people know it.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/overview/">→ Biafra</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/pogrom/overview/">→ Pogrom</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/history/overview/">→ History</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/resistance/overview/">→ Resistance</a>';
echo '</div>';
echo '</div>';