<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Figures in Nigerian Political Life</h2>';
echo '<h3>Nnamdi Azikiwe (1904–1996)</h3>';
echo '<p>The father of Nigerian nationalism and the most celebrated Igbo political figure of the 20th century. Educated in the United States, Azikiwe founded the West African Pilot newspaper (1937), the NCNC political party, and became Nigeria\'s first President (1963–1966). His pan-African vision connected Nigerian independence to the broader African struggle for dignity and self-determination. His displacement by the 1966 coup removed from Nigerian politics its most significant proponent of genuine federalism and inter-ethnic solidarity. His later life — supporting Biafra, then reconciling with Nigeria — reflects the impossible position of a man who had imagined a Nigeria that never quite materialised.</p>';
echo '<h3>Obafemi Awolowo (1909–1987)</h3>';
echo '<p>The dominant Yoruba political figure of the 20th century and Nigeria\'s most intellectually sophisticated politician. As Premier of the Western Region (1954–1959), he established free primary education, the first television station in Africa, and a model of regional development that remains the benchmark for Nigerian governance. As federal Finance Commissioner during the civil war, he is associated with the economic policies that devastated Igbo post-war recovery: the twenty-pound bank limit, the revenue allocation formula, the withholding of reconstruction funds from the southeast. His alleged statement that starvation was a legitimate weapon of war is disputed but has defined his legacy in Igbo memory. He is simultaneously one of Nigeria\'s greatest statesmen and, for many Igbo, an architect of their post-war suffering.</p>';
echo '<h3>Yakubu Gowon (b.1934)</h3>';
echo '<p>Military Head of State from 1966 to 1975, Gowon presided over the Biafra War and the subsequent oil boom. His "No Victor, No Vanquished" post-war policy was a genuine attempt at reconciliation but was undermined by the economic policies his government implemented. He was overthrown in 1975 while attending an OAU summit in Kampala. His legacy is irreducibly complex: the man who held Nigeria together and the man under whose government millions of Igbo civilians starved.</p>';
echo '<h3>Sani Abacha (1943–1998)</h3>';
echo '<p>Military Head of State from 1993 to his death in 1998, Abacha represents the nadir of Nigerian governance. He looted an estimated $3–5 billion from the Nigerian treasury, imprisoned political opponents including Moshood Abiola, and executed Ken Saro-Wiwa and eight other Ogoni activists. The Swiss government has returned several hundred million dollars of his looted funds to Nigeria; billions more remain scattered across bank accounts worldwide. He died in June 1998 — possibly assisted by associates who feared what his continued rule would bring. His death produced relief across Nigeria and opened the path to the 1999 democratic transition.</p>';
echo '<h3>Peter Obi (b.1961)</h3>';
echo '<p>Former Governor of Anambra State (2006–2014) and Labour Party presidential candidate in 2023, Peter Obi represents the most significant attempt by an Igbo political figure to compete for federal power within the democratic system since Azikiwe. His reputation for fiscal discipline and anti-corruption governance in Anambra provided a credible contrast with the APC and PDP candidates. His 2023 campaign — which attracted the "Obidient" movement of young, cross-ethnic Nigerians — demonstrated that Igbo political energy could be channelled toward federal engagement rather than separatism. His disputed official result (25% of the vote, third place) and the subsequent legal proceedings have left his political future unresolved but his significance in reshaping the terms of Igbo political participation is already evident.</p>';
echo '</div>';