<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Topics in Nigerian Politics and Society</h2>';

echo '<h3>1. Ethnic Federalism: The Structural Problem</h3>';
echo '<p>Nigeria\'s federal structure has always been organised around ethnic blocs. The original three regions — North, East, West — corresponded to Hausa-Fulani, Igbo, and Yoruba dominance. Gowon\'s division into 12 states (1967) — announced on the eve of Biafran secession to dilute the Eastern Region\'s Igbo majority — and subsequent expansions (now 36 states plus the FCT) were intended to dilute regional power but instead multiplied ethnic competition at a smaller scale. Every new state creation generated new ethnic minorities demanding their own state. Every federal appointment is scrutinised for its ethnic arithmetic. Every policy debate is filtered through the question of who benefits by ethnicity.</p>';
echo '<p>The result is a system in which ethnic identity is the primary resource of political mobilisation and in which the interests of the state as a whole — in efficient governance, in honest public finance, in the provision of public goods — are systematically subordinated to the interests of ethnic blocs competing for federal resources. This is not simply the result of bad political choices; it is built into the structure of a federation in which the federal government controls the oil revenues that make all other economic activity secondary.</p>';

echo '<h3>2. Oil and the Resource Curse</h3>';
echo '<p>Oil transformed Nigeria after its discovery in commercial quantities in 1958. By the 1970s, oil revenues constituted over 80% of federal income. This created a "resource curse" — a rentier state in which political power equals control of oil revenues rather than management of a productive economy. Agriculture — which had employed the majority of Nigerians and earned the majority of export revenue before oil — collapsed as the naira appreciated and imports became cheaper than domestic production. Manufacturing never developed beyond import substitution. The civil service became a patronage machine funded by oil rents rather than a professional bureaucracy funded by tax revenue.</p>';
echo '<p>The structural consequences of oil dependency have distorted Nigerian politics and economics for six decades. They create a zero-sum competition for federal revenue in which every ethnic group\'s gain is perceived as another\'s loss. They make honest government economically irrational — controlling the distribution of oil rents is more lucrative than any productive activity, so political power attracts the most talented and ambitious people away from the private sector. And they make the Niger Delta communities — on whose land the oil sits — simultaneously the source of national wealth and the most polluted, underdeveloped, and politically marginalised communities in the country.</p>';

echo '<h3>3. Boko Haram and the Security Crisis</h3>';
echo '<p>Boko Haram — the Islamist insurgency that has operated in northeastern Nigeria since approximately 2009 — is one of the most significant security challenges Nigeria has ever faced. Having killed tens of thousands of people, displaced millions, and destroyed the economies of northeastern Nigeria, northern Cameroon, and Niger, it represents the most extreme expression of the failure of the Nigerian state to deliver development, justice, and security to its northern periphery.</p>';
echo '<p>Boko Haram is not simply a religious movement. It is the product of the specific failure of the Maiduguri region — extreme poverty, high youth unemployment, the collapse of traditional livelihoods, the corruption of local religious and political elites, and the Nigerian Army\'s brutal and counterproductive responses to early Boko Haram activity (including the extrajudicial killing of its founder Mohammed Yusuf in 2009). For the Igbo, Boko Haram matters primarily as evidence of the Nigerian state\'s fundamental incapacity — its inability to provide the basic security and development that justify the existence of a state — and as context for understanding why the IPOB movement argues that the Igbo would be better served by their own state.</p>';

echo '<h3>4. The Herdsmen Crisis</h3>';
echo '<p>The conflict between Fulani herdsmen and farming communities — across the Middle Belt and increasingly into the southeast — has become one of the most significant sources of violence in Nigeria, killing more people annually than Boko Haram. The conflict is driven by the destruction of traditional grazing routes through agricultural expansion, climate change reducing northern pasture, and the arming of herdsmen (partly with weapons from the collapse of Libya after 2011). It has been exploited by political actors who frame it as ethnic or religious conflict, and the federal government\'s failure to protect farming communities has been interpreted — especially in the southeast, where herdsmen attacks have increased significantly — as deliberate policy rather than incapacity.</p>';

echo '<h3>5. The 2023 Election and What It Demonstrated</h3>';
echo '<p>The 2023 presidential election was the most consequential in Nigeria\'s democratic history. Peter Obi — former Governor of Anambra State, running on the Labour Party ticket — attracted unprecedented cross-ethnic support, particularly from young Nigerians, in what became known as the "Obidient" movement. His candidacy demonstrated that Igbo political energy could be mobilised for federal engagement rather than separatism, and that a Nigerian candidate presenting a credible governance programme could attract support across ethnic lines.</p>';
echo '<p>The election\'s conduct — marked by extensive irregularities, delayed INEC result uploads, and collation processes that many observers found opaque — and the subsequent tribunal and Supreme Court decisions upholding Tinubu\'s victory have left a significant portion of Nigerian civil society, particularly young people, convinced that the electoral system cannot deliver democratic change. Whether this conviction produces renewed separatist pressure (in the southeast), further disengagement from the political process, or the construction of new political formations is one of the defining questions of the coming decade.</p>';
echo '</div>';