<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>The Structure of Igbo Traditional Life</h2>';

echo '<h3>I. The Political Tradition: Stateless Democracy</h3>';
echo '<p>The most distinctive feature of Igbo traditional political organisation is its radical decentralisation. "Igbo enwe eze" — the Igbo have no king — is not merely a historical fact but a philosophical statement about how the Igbo understand legitimate authority. Power in Igbo tradition is distributed, negotiated, and earned — not inherited or seized. This is not a failure to achieve statehood; it is a different and sophisticated solution to the problem of political organisation, one that the British colonial administration found so illegible that they invented warrant chiefs to replace it.</p>';
echo '<p>In most Igbo communities, governance operated through the <em>oha na eze</em> — the assembly of the people and titled men, where decisions were made by consensus in public deliberation; <em>ndị isi ọfọ</em> — lineage heads who held the <em>ọfọ</em> staff of ancestral authority; age grades (<em>otu ọgbọ</em>) — the executive arms of community governance that implemented decisions, maintained infrastructure, and enforced norms; title societies — earned statuses that conferred specific rights and voices in governance; and the <em>dibia</em> — spiritual authority whose pronouncements carried weight in judicial and social matters. None of these institutions required a hereditary ruler. All of them required demonstrated competence and moral standing.</p>';

echo '<h3>II. The Ethical Framework: Ofo, Ogu, and Chi</h3>';
echo '<p>Igbo traditional ethics is built on three foundational concepts. <em>Ọfọ</em> — the ancestral staff held by lineage heads and title holders — represents the authority of the ancestors and the obligation to act with integrity. He who holds <em>ọfọ</em> speaks with ancestral authority; he who holds it while acting unjustly invokes ancestral punishment on himself. <em>Ogu</em> — clean hands, a clear conscience — is the personal ethical standard that makes <em>ọfọ</em> authority legitimate. "Onye nwere ọfọ na ogu" — he who has <em>ọfọ</em> and clean hands — is the person whose authority is genuine because their conduct is clean.</p>';
echo '<p>The <em>chi</em> — every person\'s personal spiritual force — completes the ethical framework by introducing the dimension of individual destiny. The <em>chi</em> is not a deterministic fate but a conversation: "Onye kwe, chi ya ekwe" — if a person agrees, their chi agrees. Success reflects alignment between the person\'s choices and their chi\'s potential; failure may reflect misalignment that ritual can address. This is not fatalism — it is a sophisticated account of the relationship between individual agency, community expectation, and forces beyond individual control.</p>';

echo '<h3>III. The Social Institutions</h3>';
echo '<p>Igbo social life is organised through overlapping institutions that create a dense web of obligation and belonging. The <em>umunna</em> — the patrilineage — is the primary unit of social identity: you are, before anything else, a member of your father\'s lineage, with all the obligations and protections that membership entails. The <em>ụmụada</em> — the daughters of the lineage — are not simply women who have married out; they retain formal authority in their natal community, return for major ceremonies, and exercise judicial power in lineage disputes that their husbands cannot exercise. This dual institution — <em>umunna</em> and <em>ụmụada</em> — means that every Igbo person belongs to two communities simultaneously: the one they were born into and the one they married into.</p>';
echo '<p>Age grades (<em>otu ọgbọ</em>) cut across lineage lines, creating solidarity between age cohorts that balances lineage loyalty. All boys born within a defined period are members of the same age grade; they progress through life together, taking on collective responsibilities — maintaining paths and markets, providing labour for community projects, policing social norms — that no individual lineage could perform alone. The age grade is simultaneously a mutual aid society, a labour organisation, a social network, and a political institution.</p>';

echo '<h3>IV. The Ritual Calendar</h3>';
echo '<p>Igbo traditional life is structured by a ritual calendar that marks agricultural cycles, ancestral commemorations, and community transitions. The four-day market week — Eke, Orie, Afo, Nkwo — provides the basic temporal grid. The agricultural year overlays this with seasonal markers: planting season, the growing season, the harvest. The New Yam Festival (<em>Iwa Ji</em> or <em>Iri Ji</em>) marks the harvest\'s beginning and is the most important communal celebration in the Igbo calendar. Masquerade festivals mark transitions — funerals, title-taking ceremonies, the beginning and end of the farming year. The ancestral feast (<em>ịkwa mmụọ</em>) maintains the connection between the living and the dead.</p>';

echo '<h3>V. Tradition and Change</h3>';
echo '<p>Igbo tradition is not a museum piece. It is a living system that has adapted continuously — to the arrival of Islam in neighbouring regions, to Portuguese traders on the coast, to British colonialism, to Christian missionary activity, to the civil war, to urban migration, and to diaspora dispersal. What has changed is the form; what has endured is the underlying logic: authority must be earned, not inherited; wealth must be shared, not hoarded; the dead must be honoured, not forgotten; the community\'s decisions must be made by the community, not imposed from outside. These are not merely Igbo values. They are arguments about how human beings should live together, and they are as urgent in the 21st century as they were in the 9th.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/culture/overview/">→ Culture</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/history/overview/">→ History</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">→ Religion</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/esoterism/overview/">→ Esoterism</a>';
echo '</div>';
echo '</div>';