<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Tradition Keepers, Elders, and Cultural Custodians</h2>';
echo '<h3>The Elder — Okenye</h3>';
echo '<p>In Igbo tradition, the elder (<em>okenye</em>) is not simply an old person — they are the repository of communal memory, the link between the living and the ancestors, and the primary authority in matters of tradition. Elders adjudicate disputes, bless ceremonies, interpret traditional law, and correct deviations from established practice. Their authority is earned through long life, demonstrated character, and formal recognition by the community. An elder who has lived badly does not command the same respect as one who has lived well. Age alone is not sufficient; character is the qualification. The elder\'s most important role is memory: in an oral tradition, the elder who remembers — who can recite the lineage\'s history, recall precedents, reproduce the words of ceremonies correctly — is a living archive. "Ọ bụ oge onye okenye nwụọ ka ụlọ ọ gbaa ọkụ" — when an elder dies, a library burns.</p>';
echo '<h3>The Dibia — Keeper of Sacred Knowledge</h3>';
echo '<p>The <em>dibia</em> is the specialist in sacred knowledge — divination, medicine, masquerade, and the negotiation of relationships between the human and spirit worlds. There are multiple types: the <em>dibia afa</em> (diviner), who reads the Igbo oracle system to diagnose problems and prescribe solutions; the <em>dibia ogwu</em> (herbalist), who uses plant-based medicine; and the <em>dibia mmọ</em> (masquerade specialist), who manages the ancestral spirit tradition. The <em>dibia</em>\'s role is not equivalent to the Western category of "witch doctor" — this translation imposes categories that obscure the <em>dibia</em>\'s actual function, which is to maintain the relationship between the human community and the spirit world. Their authority depends on their accuracy — a <em>dibia</em> whose diagnoses consistently fail loses clients and reputation. The system is empirical in its own terms.</p>';
echo '<h3>The Titled Man — Ọzọ / Nze</h3>';
echo '<p>The titled man in Igbo tradition is the closest equivalent to the full citizen in the Greek polis — someone who has earned the right to a voice in community governance through demonstrated virtue, wealth, and community support. The <em>Ọzọ</em> title is the marker of full adult male status in many Igbo communities. To take the title requires significant wealth (for the ceremonies and feasts that title-taking demands), demonstrated moral standing, community support, and the performance of specific rituals. The system is significant for what it reveals about Igbo values: achievement, not birth, confers status; wealth must be publicly demonstrated and shared; a wealthy miser cannot take title. The system rewards the combination of economic success, social generosity, and ethical conduct that Igbo culture identifies as the ideal of maturity.</p>';
echo '<h3>The Titled Woman — Lolo / Ụmụada</h3>';
echo '<p>Women\'s title systems in Igbo tradition are less well-documented but equally important. The most significant women\'s institution is the <em>ụmụada</em> — the daughters of the lineage, who retain formal authority in their natal community even after marriage. All women born into a lineage are <em>ụmụada</em> of that lineage, regardless of where they marry or how long they have been away. They return for major ceremonies, exercise specific judicial and ritual authority in lineage disputes, and serve as mediators between their natal and marital communities. The <em>ụmụada</em> institution gives women formal power in both communities they belong to — their father\'s and their husband\'s — and is one of the most significant features of Igbo gender relations that colonial and post-colonial scholarship has consistently undervalued.</p>';
echo '<h3>Victor Uchendu (1930-2017)</h3>';
echo '<p>Victor Uchendu was an Igbo anthropologist whose <em>The Igbo of Southeast Nigeria</em> (1965) became the standard introductory academic account of Igbo social organisation, religion, and culture for the English-speaking world. Born in Arondizuogu, he studied at the University of Ibadan and Northwestern University. His significance lies not only in what he wrote but in who he was: an Igbo person writing about Igbo culture from the inside, at a time when almost all anthropological accounts of African societies were written by European outsiders. He brought both scholarly rigour and cultural fluency to a subject that had previously been accessible only through colonial distortion. His work remains in print and in use.</p>';
echo '</div>';