<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Traditions in Depth</h2>';

echo '<h3>1. Mmanwu — The Masquerade Tradition</h3>';
echo '<p>The <em>Mmanwu</em> tradition is the most visible, complex, and philosophically rich institution in Igbo communal life. Masquerades are understood as <em>mmụọ</em> — spirits of the ancestors — manifesting in the physical world through initiated performers. The masquerade is not a costume; it is a theophany — a divine appearance. The performer who wears the masquerade is not the masquerade; they are the medium through which the ancestral spirit operates. This distinction is maintained with complete seriousness in traditional communities: children are told that the masquerade is a spirit, not a person in costume, and the social fiction is upheld even when everyone present knows the identity of the performer.</p>';
echo '<p>The <em>Mmanwu</em> tradition performs multiple functions simultaneously. It enforces social norms — a masquerade can publicly shame wrongdoers in ways that human authority cannot, because the ancestral spirit\'s judgment carries a different weight than any individual\'s. It celebrates community events — festivals, funerals, title ceremonies. It provides judicial authority — certain masquerades adjudicate disputes. It maintains the boundary between the sacred and the profane — women and uninitiated men are traditionally forbidden from approaching certain masquerades, a prohibition that maintains the ritual distinction between those who know the mysteries and those who do not. And it provides entertainment and social commentary — comic masquerades offer humor and irreverence that releases social tension.</p>';
echo '<p>Major Igbo masquerade types include: <em>Ijele</em> — the greatest Igbo masquerade, spectacular and stately, appearing only for the most important occasions; <em>Agaba</em> — war-like and powerful, associated with male strength; <em>Ogbodo Enyi</em> — the elephant masquerade, gentle and funerary; <em>Odo</em> — ancestral spirits of the Igbo-Eze/Nsukka area that return every two years; and <em>Ekpe</em> — the leopard society masquerade found among Efik and Cross River Igbo. Each community has its own masquerade traditions, costumes, and protocols.</p>';

echo '<h3>2. The New Yam Festival — Iwa Ji / Iri Ji</h3>';
echo '<p>The New Yam Festival is the most important communal celebration in Igbo tradition. It marks the end of the farming year and the beginning of the harvest — a moment of thanksgiving, social display, renewal, and ancestral acknowledgment. Before the New Yam Festival, no one may eat the new yams; the festival is the ritual act that makes the harvest available to the community. The first yam is offered to <em>Ala</em> — the earth goddess — and to the ancestors, before the community partakes.</p>';
echo '<p>The festival is simultaneously agricultural and political. The <em>eze ji</em> — the owner of yam, the man who controls the seed yams and sets the farming calendar — exercises a form of authority that is both practical and ritual. The competitive display of yam quality and quantity at the festival is a form of social evaluation: a man\'s yams are a measure of his industry, his family\'s prosperity, and his standing in the community. The festival\'s communal feasting, music, masquerades, and wrestling matches express the community\'s vitality and solidarity at the year\'s high point.</p>';

echo '<h3>3. Age Grades — Otu Ọgbọ</h3>';
echo '<p>The age grade system is one of the most important and least understood institutions in Igbo social life. All individuals born within a defined period — typically three to five years — are members of the same age grade. They progress through life together, and at each stage of life the age grade takes on collective responsibilities. Young age grades maintain paths, build community infrastructure, and police social norms. Middle age grades provide the executive capacity for major community decisions. Senior age grades become the council of elders that governs community affairs.</p>';
echo '<p>The age grade system is significant for several reasons. It creates solidarity that cuts across lineage lines — your age grade brothers are not your kin, but your obligations to them are real and enforced. It provides a mechanism for distributing community labour without taxation or centralised compulsion — the age grade simply fulfils its responsibilities because not doing so would shame the entire cohort. And it provides a career structure for adult life: everyone knows what responsibilities their age grade has at each stage, and there is always a next stage to aspire to. The age grade is simultaneously a mutual aid society, a labour organisation, a social network, and a political institution — and it requires no central authority to function.</p>';

echo '<h3>4. The Market and Trade Tradition</h3>';
echo '<p>The Igbo market — <em>ahịa</em> — is not merely a commercial institution. It is a social, political, and ritual institution of the first importance. Markets rotate through the four-day week: Eke market, Orie market, Afo market, Nkwo market. Each market day brings together people from multiple communities, creating a space of social encounter, information exchange, dispute resolution, and political negotiation that no single community could provide. The market is one of the primary institutions through which the Igbo world connects internally.</p>';
echo '<p>The Igbo commercial tradition — characterised by mobility, entrepreneurship, long-distance trade, and the ability to establish commercial networks in unfamiliar environments — is one of the most distinctive features of Igbo culture. It is not a modern development; it is continuous with the precolonial trading traditions documented in the archaeological record at Igbo-Ukwu and in the Aro trading network. The Igbo trader who establishes a business in Lagos, London, or Houston is operating within a cultural tradition that goes back at least a thousand years.</p>';

echo '<h3>5. Tradition in the Diaspora: What Survives, What Is Lost, What Is Invented</h3>';
echo '<p>The question of tradition in the diaspora is one of the most important and least resolved questions in contemporary Igbo cultural life. What can be maintained when the land is absent? The masquerade can be performed in a community hall in London, but it lacks the ancestral shrines, the specific landscape, and the community continuity that give it meaning in Igboland. The New Yam Festival can be celebrated in Houston, but yams must be sourced from Asian grocery stores and the farming cycle that structures the festival\'s meaning is entirely absent.</p>';
echo '<p>What survives in the diaspora is primarily the social and moral framework: the obligations of kinship, the protocols of hospitality, the ethical standards encoded in proverbs and enforced by community gossip and social pressure. Town unions, Ohanaeze branches, and age-grade associations in diaspora communities maintain these frameworks with impressive fidelity. What is most at risk is the embodied, land-rooted, seasonally-structured dimension of tradition — the dimension that requires presence in a specific place over time. The challenge of the 21st century for Igbo tradition is not whether it can survive diaspora dispersal; it demonstrably can. The challenge is what it becomes when the land is taken out of it.</p>';
echo '</div>';