<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Biafra: Causes, Course, and Consequences</h2>';

echo '<h3>I. The Colonial Foundation and the First Republic</h3>';
echo '<p>Nigeria was created by British colonialism — not by its peoples. The 1914 amalgamation joined communities with profoundly different histories, languages, religions, and political systems under a single administrative framework. The British governed the north through "indirect rule," working with the Sokoto Caliphate\'s emirate structures; they governed the south more directly, with greater missionary and educational penetration. By 1960, when independence came, the north and south had been administered differently for decades and shared no civic tradition capable of sustaining a unified democratic state.</p>';
echo '<p>The First Republic (1960–1966) demonstrated the structural instability immediately. Regional competition for federal resources produced electoral fraud, ethnic mobilisation, and political violence. The Action Group crisis (1962), the census controversy (1963–64), and the disputed federal elections of 1964–65 progressively delegitimised the civilian political order. By January 1966, the civilian order had lost the confidence of the military, and the coup that followed was widely anticipated.</p>';

echo '<h3>II. The Coups of 1966 and the Pogroms</h3>';
echo '<p>The coup of 15 January 1966 — led by a group of predominantly Igbo majors — killed the Prime Minister (Tafawa Balewa), the Northern Premier (Ahmadu Bello), the Western Premier (Akintola), and several senior northern military officers. The Eastern Premier (Okpara) and most Igbo senior officers were not killed. Whether the coup was ethnically motivated — the evidence is mixed — it was experienced in the north as an Igbo coup, and that perception drove what followed.</p>';
echo '<p>The counter-coup of 29 July 1966 was explicitly ethnic: northern officers killed Igbo officers across Nigeria, including Major-General Ironsi (who had become Head of State after the January coup) and his host, Lieutenant Colonel Fajuyi. Yakubu Gowon, a northerner from the minority Angas ethnic group, took power. In September and October 1966, Igbo civilians living in northern Nigeria were massacred in organised pogroms. Between 30,000 and 100,000 people were killed. Their property was destroyed. Their bodies were mutilated. Over a million survivors fled south. The federal government did not protect them, did not investigate the killings, and did not prosecute the perpetrators.</p>';

echo '<h3>III. The Aburi Accord and Its Repudiation</h3>';
echo '<p>The Aburi Accord of January 1967 — negotiated between Gowon and Ojukwu at Aburi, Ghana — produced an agreement for a loose confederation in which the regions would have substantial autonomy while remaining within a Nigerian framework. It was the last realistic opportunity to prevent secession. On Gowon\'s return to Lagos, the accord was repudiated under pressure from northern officers, the British High Commission, and the federal civil service. The repudiation of Aburi is the moment at which secession became Ojukwu\'s only remaining option. When Gowon announced the division of the country into twelve states in May 1967 — specifically designed to break up the Eastern Region\'s Igbo majority — Ojukwu declared Biafra on 30 May 1967.</p>';

echo '<h3>IV. The War (1967–1970)</h3>';
echo '<p>The Nigeria-Biafra War lasted thirty months. Biafra initially held its own and even made territorial advances into the Midwest Region in August 1967. But the federal military — supported by British arms and ammunition supplies and Soviet aircraft — had overwhelming advantages in numbers and materiel. Biafra\'s territory shrank progressively as federal forces advanced. By mid-1968, Biafra had been reduced to an enclave in the Igbo heartland.</p>';
echo '<p>The decisive instrument of federal victory was not military but economic: the blockade. The federal government cut off food, medicine, and supplies to the Biafran enclave. It denied landing rights to relief aircraft. It described the humanitarian crisis as Biafran propaganda. Chief Obafemi Awolowo, then federal Finance Commissioner, was widely reported to have stated that starvation was a legitimate weapon of war. The famine that resulted killed between 500,000 and 2 million people, the majority of them children. The images of kwashiorkor-afflicted Biafran children — broadcast by journalists who broke through the federal information blockade — produced the first major international humanitarian media campaign and the founding of Médecins Sans Frontières by French doctors who had served in Biafra.</p>';

echo '<h3>V. The Aftermath</h3>';
echo '<p>Ojukwu fled to Côte d\'Ivoire on 11 January 1970. Philip Effiong, Biafra\'s last leader, surrendered formally on 15 January 1970 in a speech of calm dignity. Gowon\'s "No Victor, No Vanquished" formula was a genuine attempt at reconciliation — but the economic policies that followed contradicted it. The twenty-pound limit on bank account withdrawals wiped out Igbo savings. The abandoned property policy dispossessed Igbo of property in other regions. Federal reconstruction bypassed the former Eastern Region. The oil revenues from the Niger Delta — partly in Igbo and Ijaw territory — flowed to the federal government and were distributed by formulae that disadvantaged producing states. Fifty years after the war\'s end, the structural conditions that produced it have not been resolved.</p>';
echo '</div>';