<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Leaders, Soldiers, Writers, and Witnesses</h2>';
echo '<h3>Odumegwu Ojukwu (1933-2011)</h3>';
echo '<p>Chukwuemeka Odumegwu Ojukwu is the most contested figure in the Biafran story. The son of one of Nigeria\'s wealthiest men, educated at Epsom College and Lincoln College Oxford, commissioned into the Nigerian Army, he became Military Governor of Eastern Nigeria after the July 1966 counter-coup and the leader who declared Biafran independence on 30 May 1967. His decision — taken after the failure of the Aburi Accord and in the context of mass killings of Igbo in the north — was supported by the overwhelming majority of the Igbo population. He led the Biafran war effort for two and a half years against a federal military with overwhelming advantages in numbers and materiel. He fled to Côte d\'Ivoire on 11 January 1970, was pardoned by Shagari in 1982, returned to Nigeria, and remained a charismatic political figure until his death in London in 2011. He was buried with full military honours — a belated and incomplete acknowledgment of his place in history. To his supporters he is the father of the Biafran nation; to his critics he led his people into a catastrophe that could have been avoided. The argument is not resolvable.</p>';
echo '<h3>Philip Effiong (1925-2003)</h3>';
echo '<p>Philip Effiong was Biafra\'s last leader — the man left to surrender when Ojukwu fled. His surrender speech of 15 January 1970 is one of the most remarkable documents produced by the war: calm, dignified, free of bitterness, placing the welfare of his people above all political considerations, and accepting federal authority without humiliation. He lived out the rest of his life in relative obscurity in Lagos, his contribution to ending the war with minimum further loss of life insufficiently recognised. He died in 2003.</p>';
echo '<h3>Chinua Achebe (1930-2013)</h3>';
echo '<p>Chinua Achebe served as a Biafran diplomat during the war, travelling to Europe and North America to argue the Biafran case and document the humanitarian crisis. His memoir <em>There Was a Country</em> (2012), published a year before his death, was the account he had been working toward for four decades: a literary and personal reckoning with the war, its causes, its conduct, and its aftermath, including his direct indictment of Awolowo\'s role in the famine. The memoir generated controversy in Nigeria — its honesty was experienced by some as an attack on national unity — but it is the most important literary document of the Biafran experience and an essential primary source.</p>';
echo '<h3>Chimamanda Ngozi Adichie (b.1977)</h3>';
echo '<p>Chimamanda Ngozi Adichie was born seven years after the war ended, but the war shaped her family\'s history and became the subject of her most significant novel. <em>Half of a Yellow Sun</em> (2006) — the title refers to the Biafran flag — is the most widely read fictional account of the war in any language. Its achievement is to make the war\'s human cost visible and specific — not statistics but people. It won the Orange Prize for Fiction in 2006 and has sold millions of copies worldwide, introducing the Biafran war to a generation of readers who had no previous knowledge of it.</p>';
echo '<h3>The Children of the Famine</h3>';
echo '<p>The most important witnesses to the Biafra War are those who cannot speak: the children who died of starvation during the federal blockade. Between 500,000 and 2 million people died of famine — the majority children under the age of five. Their images — photographed by journalists who broke through the federal information blockade — became the founding images of modern humanitarian media. They are not named in any official record. They have no memorial in Nigeria. The Nigerian state\'s refusal to acknowledge their deaths is the most fundamental form of the official amnesia that continues to drive Biafran political sentiment fifty years after the war. They are named here, collectively, as the most important witnesses to what the Nigeria-Biafra War actually was.</p>';
echo '</div>';