<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Essential books, films, and references for understanding Biafra.</p>';
echo '<h2>Primary Accounts</h2>';
echo '<ul>';
echo '<li><strong>Chinua Achebe</strong> — <em>There Was a Country: A Personal History of Biafra</em> (2012). The most important Igbo literary account. Essential.</li>';
echo '<li><strong>Wole Soyinka</strong> — <em>The Man Died</em> (1972). Memoir of imprisonment during the war. Essential.</li>';
echo '<li><strong>Alexander Madiebo</strong> — <em>The Nigerian Revolution and the Biafran War</em> (1980). Account by Biafra\'s army commander.</li>';
echo '<li><strong>Emeka Odumegwu-Ojukwu</strong> — <em>Biafra: Selected Speeches and Random Thoughts</em> (1969). Ojukwu\'s own words during the war.</li>';
echo '</ul>';
echo '<h2>Historical Studies</h2>';
echo '<ul>';
echo '<li><strong>John Stremlau</strong> — <em>The International Politics of the Nigerian Civil War 1967–1970</em> (1977). The standard academic account of the international dimensions.</li>';
echo '<li><strong>Adewale Ademoyega</strong> — <em>Why We Struck: The Story of the First Nigerian Coup</em> (1981). Inside account of the January 1966 coup.</li>';
echo '<li><strong>Ntieyong Akpan</strong> — <em>The Struggle for Secession 1966–1970</em> (1971). Ibibio perspective on the war.</li>';
echo '<li><strong>Auberon Waugh and Suzanne Cronje</strong> — <em>Biafra: Britain\'s Shame</em> (1969). Early indictment of British policy.</li>';
echo '</ul>';
echo '<h2>Journalism and Eyewitness Accounts</h2>';
echo '<ul>';
echo '<li><strong>Frederick Forsyth</strong> — <em>The Biafra Story</em> (1969). The most widely read contemporary account, written by a journalist sympathetic to Biafra.</li>';
echo '<li><strong>Rolf Steiner</strong> — <em>The Last Adventurer</em> (1978). Account by a mercenary who fought for Biafra.</li>';
echo '</ul>';
echo '<h2>Fiction</h2>';
echo '<ul>';
echo '<li><strong>Chimamanda Ngozi Adichie</strong> — <em>Half of a Yellow Sun</em> (2006). The most celebrated fictional account. Winner of the Orange Prize. Essential reading.</li>';
echo '<li><strong>Buchi Emecheta</strong> — <em>Destination Biafra</em> (1982). Fictional account from a female perspective.</li>';
echo '<li><strong>Flora Nwapa</strong> — <em>Never Again</em> (1975). Short novel about a woman\'s experience of the war.</li>';
echo '</ul>';
echo '<h2>Documentary Film</h2>';
echo '<ul>';
echo '<li><em>Biafra: Fighting a War with Cameras</em> — documentary on the media dimension of the conflict</li>';
echo '<li><em>The Biafra War</em> — various documentary treatments available on YouTube and streaming services</li>';
echo '</ul>';
echo '<h2>Declassified Archives</h2>';
echo '<ul>';
echo '<li>British National Archives — FCO files on Nigeria 1966–1970, now partly declassified</li>';
echo '<li>US State Department cables — available through the National Security Archive</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/overview/">Overview</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/people/">People</a>';
echo '</div></div>';
