<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Topics in the Study of Biafra</h2>';

echo '<h3>1. The 1966 Pogroms: The Root Cause</h3>';
echo '<p>Any honest account of Biafra must begin with the mass killing of Igbo in northern Nigeria in 1966. These events — which the Nigerian state has never officially acknowledged, investigated, or commemorated — are the immediate and necessary cause of Biafran secession. Igbo people who had lived in the north for decades, who had built businesses, raised families, and become integrated into northern cities, were killed in their tens of thousands in organised violence that involved, in documented cases, the participation of Nigerian Army soldiers.</p>';
echo '<p>The scale of the violence — between 30,000 and 100,000 dead, over a million displaced — makes the 1966 pogroms one of the largest episodes of ethnic violence in post-colonial African history. The federal government\'s failure to protect its Igbo citizens, to investigate the killings, or to bring any perpetrator to justice made the argument for a separate Igbo state not merely understandable but, from the Igbo perspective, essential. Biafra was not a political ambition. It was a survival response.</p>';

echo '<h3>2. The Blockade: Starvation as Policy</h3>';
echo '<p>The most contested question of the war is whether the famine was deliberate. The evidence is damning. The federal government denied food relief aircraft landing rights — specifically preventing the Red Cross, Caritas, and other humanitarian organisations from delivering food to the Biafran enclave. It described the humanitarian crisis as Biafran propaganda designed to generate international sympathy. Chief Obafemi Awolowo was widely reported to have stated that starvation was a legitimate weapon of war; the Nigerian government denied this, but the policy was consistent with the statement whether or not he made it.</p>';
echo '<p>The famine killed between 500,000 and 2 million people. The dead were overwhelmingly civilian, overwhelmingly Igbo, and overwhelmingly children. The images that reached the world — of children with distended bellies and the reddened hair of kwashiorkor, the protein deficiency disease that the famine caused — were the founding images of modern humanitarian media. They produced the first international humanitarian intervention campaign, led by figures including Bernard Kouchner, whose experience in Biafra led directly to the founding of Médecins Sans Frontières in 1971. The question of whether the famine was deliberate is not merely historical: it determines whether the Biafra War involved war crimes against the civilian population of the Biafran enclave, a question the Nigerian state has never allowed to be formally examined.</p>';

echo '<h3>3. Britain\'s Role: Arms, Diplomacy, and Oil</h3>';
echo '<p>Britain supplied the Nigerian federal government with arms, ammunition, diplomatic support, and intelligence throughout the war. The Labour government of Harold Wilson — who described the conflict as a "police action" — maintained that Nigeria\'s territorial integrity was a paramount British interest. The specific British interests at stake were explicit: Shell-BP\'s oil concessions in the Niger Delta (potentially in Biafran territory) represented enormous commercial value; the disruption of Anglo-Nigerian trade relations would damage British exports; and the precedent of successful African secession was thought to threaten British interests across the continent.</p>';
echo '<p>Britain blocked international pressure for a ceasefire. It provided diplomatic cover for the federal government\'s denial of humanitarian access. British arms shipments — documented in Parliamentary debates and in files declassified in the 2000s — were material to the federal military\'s victory. The role of British commercial interests — particularly Shell-BP — in British government calculations has been documented by historians and by the declassified files, though the full extent of the relationship remains contested. Britain\'s role in the Biafra War is one of the reasons that Igbo communities in the United Kingdom carry a specifically complicated relationship to their country of residence.</p>';

echo '<h3>4. International Response: Recognition, Relief, and the Limits of Solidarity</h3>';
echo '<p>Biafra received formal recognition from only five states: Tanzania, Zambia, Ivory Coast, Gabon, and Haiti. The Organisation of African Unity — committed to the principle of colonial borders and the territorial integrity of existing states — refused to recognise Biafra. The Soviet Union supplied the federal government with aircraft and military advisers. France — motivated partly by Gaullist anti-British sentiment, partly by commercial interests in offshore oil, and partly by genuine sympathy — provided covert support to Biafra, including weapons and diplomatic backing. China was broadly neutral. The United States, formally neutral, tilted toward the federal government.</p>';
echo '<p>The humanitarian response was more significant than the political one. The images of starving Biafran children generated the first modern humanitarian media campaign: fundraising across Europe and North America, celebrity advocacy (John Lennon returned his MBE partly in protest), and the deployment of humanitarian organisations that had not previously operated in active conflict zones. This campaign did not save Biafra — it was politically ineffective — but it created the institutional and media infrastructure for subsequent humanitarian interventions and permanently changed the relationship between conflict, media, and international civil society.</p>';

echo '<h3>5. Memory and Denial: Why Biafra Persists</h3>';
echo '<p>Fifty years after the war\'s end, Biafra persists in Igbo political consciousness with an intensity that the Nigerian state finds threatening and that the rest of the world finds puzzling. The persistence is not puzzling. It reflects the fact that the conditions that produced Biafra have not been resolved: the structural marginalisation of the Igbo within the Nigerian federal state, the absence of federal infrastructure investment in the southeast, the dominance of northern officers in the military command, and — most fundamentally — the Nigerian state\'s refusal to acknowledge, investigate, or commemorate the 1966 pogroms and the wartime famine.</p>';
echo '<p>In Nigeria\'s official history, the Biafra War is presented as a necessary defence of national unity against illegal secession. The pogroms of 1966 are not commemorated. The famine is not acknowledged as a federal policy. The twenty-pound bank limit and the abandoned property policy are not presented as punitive. This official amnesia — the imposition of a victor\'s narrative on a history in which the victor\'s conduct was, at minimum, morally complex — is itself a political act, and the Igbo refusal to accept it is a political response. IPOB, the sit-at-home orders, and the continuing resonance of Biafran nationalism are not symptoms of irrationality. They are the political expression of a people who have been told that what happened to them did not happen, and who know that it did.</p>';
echo '</div>';