<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Eastern esoteric and mystical traditions — Sufism, Tantra, Kashmir Shaivism, Kundalini, Tibetan Bön, and the inner dimensions of Eastern religion.</p>';

// SUFISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Sufism (Tasawwuf)</h2>';
echo '<p><strong>Origin:</strong> Arabia/Persia | <strong>Period:</strong> 8th–9th century CE (formalization) | <strong>Framework:</strong> Islamic monotheism — strictly Tawhid (Oneness of God) | <strong>Proselytism:</strong> Teaching within Islam; tariqa (order) initiates students | <strong>Apostasy:</strong> Carries the same weight as apostasy in Islam — potentially fatal in some jurisdictions historically; now mainly social/spiritual consequences</p>';
echo '<h3>Origin</h3>';
echo '<p>Sufism is the mystical, inner dimension of Islam — not a separate religion but an approach within Islam that seeks direct experiential knowledge (ma\'rifa) of God rather than merely formal observance of the Sharia (Islamic law). Its name derives from <em>suf</em> (Arabic: wool) — early Muslim ascetics wore simple wool garments as a rejection of worldly attachment. The 8th–9th centuries CE saw the emergence of systematic Sufi teaching: Rabia al-Adawiyya (c. 717–801), the first great female Sufi, introduced the concept of divine love (mahabbah) as the path to God; Hasan al-Basri emphasized the fear of God and ascetic withdrawal; Al-Hallaj (857–922) was executed for declaring "Ana\'l-Haqq" — "I am the Truth/God" — a statement interpreted as heretical union with the divine.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>Tawhid — Oneness</strong> — Sufism begins with strict Islamic monotheism but pushes it to its philosophical extreme: if God is truly One and Infinite, then nothing can exist outside God. The mystic consequence: all of reality is a manifestation of God\'s being. This is <em>Wahdat al-Wujud</em> — "Unity of Being" — the doctrine of Ibn Arabi (1165–1240), Sufism\'s greatest metaphysician.</li>';
echo '<li><strong>Wahdat al-Wujud (Unity of Being)</strong> — Ibn Arabi\'s central teaching: there is only one Being — God — and everything that appears to exist is a manifestation (tajalli) of God\'s self-disclosure. The world is God\'s self-expression; creation is God\'s desire to be known ("I was a Hidden Treasure and I wished to be known, so I created the world"). This is a form of mystical monism within monotheistic Islam — deeply controversial and rejected by orthodox Sunni scholars.</li>';
echo '<li><strong>The Three Stations</strong> — Sharia (outer law), Tariqa (the path, inner practice), Haqiqa (the truth, mystical reality). Most Muslims live at the Sharia level; Sufis aspire to Haqiqa through Tariqa.</li>';
echo '<li><strong>Fana and Baqa</strong> — <em>Fana</em> (annihilation of the ego self in God) and <em>Baqa</em> (subsistence in God after fana). The Sufi path aims at the dissolution of the false, separate self and its replacement by the divine reality. This is not literal death but the death of the illusion of separateness.</li>';
echo '<li><strong>The Stages (Maqamat) and States (Ahwal)</strong> — the Sufi path is mapped in stages (permanent attainments achieved by effort) and states (temporary spiritual conditions given by grace): tawba (repentance), zuhd (asceticism), sabr (patience), tawakkul (trust in God), mahabba (love), ma\'rifa (gnosis/direct knowledge), fana.</li>';
echo '<li><strong>Dhikr</strong> — "remembrance" of God; the central Sufi practice. Repetition of divine names or phrases (Allah, La ilaha illa Allah, Hu) in rhythm with the breath, individually or collectively, to dissolve the ego and open to the divine presence.</li>';
echo '</ul>';
echo '<h3>Reincarnation</h3>';
echo '<p>Mainstream Sufism, following orthodox Islam, does not teach reincarnation. Islam teaches a single human life followed by resurrection and judgment. However, certain Sufi schools — particularly those influenced by Neoplatonic and Ismaili thought — have taught forms of spiritual transmigration. Ibn Arabi\'s complex cosmology includes the soul\'s traverse of multiple levels of existence. The Druze (an offshoot of Ismaili Islam deeply influenced by Sufism) explicitly teach reincarnation. And Rumi\'s poetry repeatedly uses imagery of descent into matter and return to the divine that resonates strongly with transmigration themes, though he did not formally teach reincarnation.</p>';
echo '<h3>Karma Equivalent</h3>';
echo '<p>Islam teaches that every action has consequences measured on the Day of Judgment — a single-life karmic reckoning rather than multi-life karma. Within Sufism, the concept is spiritualized: attachment and ego create veils (hujub) between the seeker and God; virtuous action and dhikr thin and remove these veils. The consequence of wrongdoing is spiritual distance from God — a present suffering, not merely a future judgment.</p>';
echo '<h3>The Tariqa — Order and Initiation</h3>';
echo '<p>Sufi knowledge is transmitted through initiatic orders (Turuq, sing. Tariqa). The student (murid) takes initiation from a Sheikh (master) who stands in an unbroken chain (silsila) of transmission going back through previous masters to the Prophet Muhammad. The Sheikh gives the murid a wird (daily litany), teaches dhikr techniques, and guides the inner journey. Major orders include:</p>';
echo '<ul>';
echo '<li><strong>Qadiriyya</strong> — founded by Abdul Qadir al-Jilani (1077–1166); the most widespread order globally; present in Africa (including Senegal, Nigeria), Turkey, India</li>';
echo '<li><strong>Naqshbandiyya</strong> — founded in Central Asia; emphasizes silent dhikr; influential in Turkey, India, Central Asia</li>';
echo '<li><strong>Chishtiyya</strong> — Indian subcontinent; famous for music (Qawwali) as spiritual practice; Nizamuddin Auliya is the most celebrated Chishti master</li>';
echo '<li><strong>Tijaniyya</strong> — founded in Morocco 1781; the dominant Sufi order in West Africa including Senegal, Nigeria, Niger; tens of millions of followers</li>';
echo '<li><strong>Mevlevi</strong> — the "Whirling Dervishes" of Turkey; founded by followers of Rumi; the sama (whirling meditation) is their primary practice</li>';
echo '</ul>';
echo '<h3>Proselytism and Apostasy in Sufism</h3>';
echo '<p>Sufism spreads primarily through the attraction of the Sheikh\'s spiritual presence and reputation, not through aggressive proselytism. The tariqa accepts initiates who seek it. Apostasy from Islam — which Sufi practice occurs within — is treated according to classical Islamic law (historically punishable by death in some jurisdictions; in practice, consequences vary widely by country and era). A Sufi who leaves Islam faces the same consequences as any Muslim apostate. Leaving a Sufi order without leaving Islam is generally treated as a spiritual matter between the murid and Sheikh.</p>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>Rumi — Masnavi-ye Ma\'navi</strong> — the greatest Sufi poem; 25,000 verses. Free: <a href="https://sacred-texts.com/isl/masnavi/index.htm" target="_blank" rel="noopener">sacred-texts.com/isl/masnavi</a></li>';
echo '<li><strong>Al-Ghazali — Ihya Ulum al-Din (Revival of the Religious Sciences)</strong> — the most important work of Islamic mystical theology. Free: <a href="https://archive.org/search?query=ihya+ulum+al-din" target="_blank" rel="noopener">archive.org</a></li>';
echo '<li><strong>Ibn Arabi — Fusus al-Hikam (The Bezels of Wisdom)</strong>. Free: <a href="https://archive.org/search?query=fusus+al-hikam" target="_blank" rel="noopener">archive.org</a></li>';
echo '<li><strong>Al-Hallaj — Kitab al-Tawasin</strong>. Free: <a href="https://sacred-texts.com/isl/hallaj/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '</ul>';

// TANTRA
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#553c9a;">⊕ Tantra</h2>';
echo '<p><strong>Origin:</strong> India | <strong>Period:</strong> c. 500–1200 CE (classical texts) | <strong>Framework:</strong> Polytheistic/non-dual (Shakta-Shaiva primarily) | <strong>Proselytism:</strong> Guru-student transmission; not actively proselytized | <strong>Apostasy:</strong> Breaking with one\'s guru; violating initiation vows</p>';
echo '<h3>Origin</h3>';
echo '<p>Tantra (Sanskrit: "loom" or "weave" — that which extends knowledge) is not a single religion but a vast family of initiatory traditions arising in India from approximately 500 CE onward, reaching their peak between 700–1200 CE. Tantric texts (<em>Agamas</em> and <em>Tantras</em>) claimed to be revealed by Shiva or Shakti (the goddess) directly, as a path suited to the degenerate age (<em>Kali Yuga</em>) when the Vedic sacrificial path was no longer practical. Tantra spread into Buddhism (Vajrayana) and Jainism as well as the Hindu traditions.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>Non-dualism (Advaita)</strong> — in its highest philosophical expressions (especially Kashmir Shaivism), Tantra teaches that reality is non-dual: the divine Shiva-Shakti consciousness is the only reality; the apparent multiplicity of the world is the divine\'s own play (Lila) or pulsation (Spanda). There is no fundamental division between the divine and the world, spirit and matter, the sacred and the profane.</li>';
echo '<li><strong>Shakti</strong> — the divine feminine as the fundamental creative power (Shakti — "power/energy") underlying all manifestation. Shiva is the consciousness principle; Shakti is its dynamic expression. Without Shakti, Shiva is inert. The universe is Shakti\'s dance.</li>';
echo '<li><strong>The Tantric Reversal</strong> — where conventional religion sees the body, sexuality, and worldly experience as obstacles to liberation, Tantra sees them as vehicles. The very forces that bind the uninitiated can liberate the initiated. This is the core Tantric innovation: using desire, sensation, and embodied experience as paths to liberation rather than things to be suppressed.</li>';
echo '<li><strong>The Five Makaras (Panchamakara)</strong> — in certain "left-hand" Tantric paths (Vamachara), five substances beginning with the letter M are used ritually: Madya (wine), Mamsa (meat), Matsya (fish), Mudra (grain/gesture), and Maithuna (sexual union). These were deliberately transgressive — violating Brahminical purity rules to demonstrate that liberation transcends conventional morality. "Right-hand" (Dakshinachara) Tantric paths use symbolic substitutes for these substances.</li>';
echo '<li><strong>Kundalini</strong> — the divine Shakti energy lying dormant at the base of the spine (Muladhara chakra), coiled like a serpent. Tantric practice aims to awaken Kundalini and raise it through the seven chakras (energy centers) to the crown (Sahasrara), where Shakti unites with Shiva — producing liberation (moksha) and the experience of non-dual consciousness.</li>';
echo '<li><strong>Chakras</strong> — seven (or more) energy centers along the spine: Muladhara (root, survival), Svadhisthana (sacral, sexuality), Manipura (solar plexus, power), Anahata (heart, love), Vishuddha (throat, expression), Ajna (third eye, intuition), Sahasrara (crown, divine union).</li>';
echo '<li><strong>Mantra</strong> — sacred sound formulas that are the vibratory essence of specific deities or cosmic principles. Initiation into a mantra by a qualified guru is essential; the mantra is the deity in sound form.</li>';
echo '<li><strong>Yantra / Mandala</strong> — sacred geometric diagrams that are the visual form of deities; used as objects of meditation and ritual.</li>';
echo '</ul>';
echo '<h3>Reincarnation and Karma</h3>';
echo '<p>Tantra accepts the Indian understanding of reincarnation (samsara) and karma as the framework from which it offers liberation. However, Tantra\'s attitude is distinctive: rather than slowly working off karma over many lives, the initiated Tantric practitioner uses specific techniques to burn karma rapidly and achieve liberation within a single lifetime. The metaphor often used is that karma is like a pot of rice: the conventional path slowly consumes it grain by grain; Tantra sets the entire pot on fire at once. This accelerated path is why Tantra requires initiation and guru guidance — it is considered dangerous without qualified instruction.</p>';
echo '<h3>Proselytism</h3>';
echo '<p>Tantra has never been proselytized in the conventional sense. It is transmitted through the guru-student (guru-shishya) lineage. The prospective student must find a qualified guru, be accepted, and receive initiation (diksha). Without initiation, Tantric practices are considered ineffective or dangerous. The guru is considered indispensable — the tradition explicitly states that Tantra learned from books without guru initiation is worse than useless.</p>';
echo '<h3>Kashmir Shaivism</h3>';
echo '<p>The most philosophically sophisticated school of Tantra is Kashmir Shaivism (also called Trika, or Pratyabhijna — "recognition"). Developed in Kashmir between the 8th–12th centuries CE by masters including Abhinavagupta (950–1020 CE), it presents a radical non-dualism: there is only Shiva-consciousness, and the entire universe is its free self-expression. Liberation is not acquiring something new but recognizing (pratyabhijna) what one already is — pure awareness. This recognition is both intellectual and experiential, brought about through grace, inquiry, and specific practices.</p>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>Shiva Sutras</strong> (c. 9th century) — foundational text of Kashmir Shaivism. Free: <a href="https://sacred-texts.com/hin/shivasutra.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '<li><strong>Vijnanabhairava Tantra</strong> — 112 meditation techniques for direct recognition of the divine. Free: <a href="https://archive.org/search?query=vijnanabhairava+tantra" target="_blank" rel="noopener">archive.org</a></li>';
echo '<li><strong>Abhinavagupta — Tantraloka</strong> — the most comprehensive Tantric treatise. Partial translations available at <a href="https://archive.org/search?query=tantraloka+abhinavagupta" target="_blank" rel="noopener">archive.org</a></li>';
echo '</ul>';

// TIBETAN BON
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Tibetan Bön</h2>';
echo '<p><strong>Origin:</strong> Tibet/Zhang Zhung (western Tibet) | <strong>Period:</strong> Pre-Buddhist Tibet; systematic from c. 10th century CE | <strong>Framework:</strong> Polytheistic cosmology; non-dual highest teachings | <strong>Proselytism:</strong> Monastic transmission | <strong>Apostasy:</strong> Breaking monastic vows</p>';
echo '<h3>Origin</h3>';
echo '<p>Bön is the indigenous spiritual tradition of Tibet, predating the arrival of Buddhism in the 7th century CE. Its founder is the legendary Tonpa Shenrab Miwoche, said to have come from the mythical land of Olmolungring (possibly Zhang Zhung — western Tibet). Bön was largely suppressed when Buddhism became the state religion of Tibet under King Trisong Detsen (8th century CE) but survived in remote areas and experienced a major revival in the 10th–11th centuries. Today Bön is recognized by the Tibetan government-in-exile as one of Tibet\'s five major religious traditions, alongside the four schools of Tibetan Buddhism.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>The Nine Ways of Bön</strong> — Bön is organized in nine vehicles (Thegpa), ranging from the causal vehicles (divination, ritual, healing, astrology) to the result vehicles (tantric practices) to the highest — Dzogchen.</li>';
echo '<li><strong>Dzogchen — The Great Perfection</strong> — Bön\'s highest teaching; identical in structure (and disputed in origin relative to Buddhist Dzogchen) to the non-dual recognition of inherent awareness (rigpa) as the fundamental nature of mind. This is similar to Kashmir Shaivism\'s pratyabhijna — recognition of what one already is.</li>';
echo '<li><strong>The Primordial Buddha — Kuntu Zangpo</strong> — in Bön, the primordial state of pure awareness is personified as Kuntu Zangpo (Samantabhadra in Buddhism) — the "Ever Good," the blue naked figure who symbolizes primordial awareness never obscured by illusion.</li>';
echo '<li><strong>The Four Elements and the Soul</strong> — Bön cosmology includes elaborate systems of soul-concepts: the <em>la</em> (vital soul), the <em>bla</em> (life essence), the <em>yid</em> (mind), and the <em>srog</em> (life force) — each of which can be lost or damaged and must be retrieved through ritual.</li>';
echo '<li><strong>Reincarnation</strong> — Bön fully accepts reincarnation and the karmic cycle (samsara). The Bön tradition recognizes its own reincarnate masters (trulku) parallel to the Buddhist tulku system. The Menri Trizin (head of the Bön tradition) reincarnates.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Divination (Mo)</strong> — reading signs for guidance; one of Bön\'s oldest practices</li>';
echo '<li><strong>Soul retrieval</strong> — shamanic-style journeying to retrieve lost soul components</li>';
echo '<li><strong>Sky burial</strong> — shared with Tibetan Buddhism; the body offered to vultures at death</li>';
echo '<li><strong>Tantric practice</strong> — visualization of deities, mantra, mandala — structurally identical to Vajrayana Buddhism</li>';
echo '<li><strong>Dzogchen meditation</strong> — resting in the recognition of naked awareness</li>';
echo '</ul>';
echo '<h3>Key Text</h3>';
echo '<p><strong>Zhang Zhung Nyengyu</strong> — the Oral Transmission of Zhang Zhung; the Dzogchen teachings of Bön. Partial translations available through Ligmincha Institute.</p>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/topics/">Western Esoteric</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/african/">African Esoteric</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/sources/">Texts & Downloads</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/eastern/">→ Eastern Religions</a>';
echo '</div></div>';
