<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Western esoteric traditions in depth — doctrines, philosophy, practices, and the unique contribution of each to human spiritual knowledge.</p>';

// HERMETICISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#b7791f;">⊕ Hermeticism</h2>';
echo '<p><strong>Origin:</strong> Egypt/Alexandria | <strong>Period:</strong> c. 100–300 CE (texts), claiming ancient Egyptian origin | <strong>Theism:</strong> Monotheistic (emanationist) | <strong>Proselytism:</strong> None — transmitted to seekers | <strong>Apostasy:</strong> Not applicable</p>';
echo '<h3>Origin and History</h3>';
echo '<p>Hermeticism derives from the <em>Corpus Hermeticum</em> — a collection of Greek texts attributed to Hermes Trismegistus ("Thrice-Greatest Hermes"), a legendary figure identified as a synthesis of the Greek god Hermes and the Egyptian god Thoth. Modern scholarship dates these texts to the 1st–3rd centuries CE, probably produced in Alexandria where Greek philosophy and Egyptian religious thought were in active dialogue. Renaissance scholars (Ficino, Pico della Mirandola) believed them to be ancient Egyptian wisdom, older than Plato — this belief, though historically incorrect, drove their enormous influence on Renaissance magic and philosophy.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>The Seven Hermetic Principles</strong> (from the <em>Kybalion</em>, 1908, summarizing older material):</li>';
echo '<li style="list-style:none;padding-left:20px;">1. <strong>Mentalism</strong> — "The All is Mind; the Universe is Mental." Reality is fundamentally mental/consciousness.</li>';
echo '<li style="list-style:none;padding-left:20px;">2. <strong>Correspondence</strong> — "As above, so below; as below, so above." Every level of reality mirrors every other.</li>';
echo '<li style="list-style:none;padding-left:20px;">3. <strong>Vibration</strong> — "Nothing rests; everything moves; everything vibrates." Matter is condensed vibration.</li>';
echo '<li style="list-style:none;padding-left:20px;">4. <strong>Polarity</strong> — "Everything is Dual; everything has poles." Opposites are the same thing in different degrees.</li>';
echo '<li style="list-style:none;padding-left:20px;">5. <strong>Rhythm</strong> — "Everything flows, out and in; everything has its tides." Cyclical patterns govern all things.</li>';
echo '<li style="list-style:none;padding-left:20px;">6. <strong>Cause and Effect</strong> — "Every Cause has its Effect; every Effect has its Cause." Nothing happens by chance.</li>';
echo '<li style="list-style:none;padding-left:20px;">7. <strong>Gender</strong> — "Gender is in everything; everything has its Masculine and Feminine Principles." Creative polarity pervades all levels of existence.</li>';
echo '<li><strong>The One (To Hen)</strong> — the ultimate reality is a single, unknowable, infinite Mind from which all things emanate.</li>';
echo '<li><strong>The Soul\'s Ascent</strong> — the human soul descended through seven planetary spheres (Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon), acquiring characteristics from each. Gnosis enables the soul to reascend through these spheres, shedding these accretions and returning to the divine One.</li>';
echo '<li><strong>Reincarnation</strong> — explicitly taught in the Corpus Hermeticum. The soul transmigrates until it achieves gnosis and liberation from the cycle. "The soul passes into different bodies until it has completed the revolution of all the spheres." (Corpus Hermeticum, Book 10)</li>';
echo '</ul>';
echo '<h3>Uniqueness</h3>';
echo '<p>Hermeticism is unique in claiming that the human being is a microcosm containing within themselves the entire macrocosm — all planets, all divine forces, all levels of reality. The Hermetic human is thus simultaneously the lowest creature (embodied) and the highest (containing the All). This paradox — the divine trapped in matter, matter capable of becoming divine — drives the entire Hermetic project.</p>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Theurgy</strong> — ritual operations to attract divine forces; the higher magic of classical antiquity</li>';
echo '<li><strong>Astrology</strong> — reading the correspondence between celestial patterns and earthly events</li>';
echo '<li><strong>Alchemy</strong> — transformation of matter as a symbol and instrument of soul transformation</li>';
echo '<li><strong>Meditation on divine names</strong> — concentrating the mind on divine attributes to attract their influence</li>';
echo '</ul>';
echo '<h3>Key Text</h3>';
echo '<p><strong>Corpus Hermeticum</strong> — 17 Greek treatises; translated into Latin by Ficino (1463). Free download: <a href="https://sacred-texts.com/egy/herm/index.htm" target="_blank" rel="noopener">sacred-texts.com/egy/herm</a></p>';

// GNOSTICISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#553c9a;">⊕ Gnosticism</h2>';
echo '<p><strong>Origin:</strong> Syria, Egypt, Roman Empire | <strong>Period:</strong> c. 100–400 CE | <strong>Theism:</strong> Dualistic (the true God vs the Demiurge) | <strong>Proselytism:</strong> Limited — taught to initiates | <strong>Apostasy:</strong> Not formally addressed</p>';
echo '<h3>Origin</h3>';
echo '<p>Gnosticism was not a single religion but a family of related movements flourishing in the 1st–4th centuries CE, combining elements of Christianity, Judaism, Platonism, and Persian dualism. The discovery of the Nag Hammadi library in Egypt in 1945 — 52 Gnostic texts buried around 350 CE — transformed our understanding of Gnosticism from secondhand accounts by hostile Church Fathers to primary sources. Major Gnostic schools included Valentinianism, Sethianism, Manichaeism, and Marcionism.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>The True God vs the Demiurge</strong> — this is the most radical and distinctive Gnostic teaching. The material world was not created by the true, transcendent God but by an inferior being — the Demiurge (Greek: craftsman). The Demiurge is variously ignorant, arrogant, or malevolent. In some systems he is identified with the God of the Old Testament.</li>';
echo '<li><strong>Pleroma</strong> — the "Fullness" — the divine realm of true light and spirit, containing the true God and a complex hierarchy of divine beings (Aeons).</li>';
echo '<li><strong>Sophia\'s Fall</strong> — a divine being (Sophia — Wisdom) descended from the Pleroma through an act of desire or error; the Demiurge is her fallen offspring. The material world is the result of this fall.</li>';
echo '<li><strong>The Divine Spark</strong> — within certain human beings is a divine spark (pneuma — spirit) — a fragment of the true divine light trapped in matter by the Demiurge. These pneumatic (spiritual) humans can be awakened to their true origin.</li>';
echo '<li><strong>Gnosis as Salvation</strong> — salvation in Gnosticism is not through faith or works but through gnosis — direct experiential knowledge of one\'s divine origin. To know oneself truly is to know God.</li>';
echo '<li><strong>Reincarnation</strong> — most Gnostic systems taught that the soul undergoes multiple incarnations until it achieves sufficient gnosis to escape the material world and return to the Pleroma. The Demiurge and his archons (rulers) try to prevent this escape.</li>';
echo '<li><strong>Karma equivalent</strong> — not karma exactly, but the soul accumulates material entanglement through ignorance; gnosis removes this entanglement.</li>';
echo '</ul>';
echo '<h3>Attitude toward the Body and Matter</h3>';
echo '<p>Gnosticism produced two opposite ethical responses to its dualism:</p>';
echo '<ul>';
echo '<li><strong>Asceticism</strong> — since matter is evil, deny the body; fast, abstain from sex, reject worldly pleasures. (Dominant response)</li>';
echo '<li><strong>Libertinism</strong> — since the Demiurge created the body and his laws govern it, the truly spiritual person can transgress these laws freely without harm to the divine spark. (Minority response, heavily criticized by opponents)</li>';
echo '</ul>';
echo '<h3>Uniqueness</h3>';
echo '<p>Gnosticism is the most radical critique of ordinary religion from within religion\'s own framework. It does not reject God — it rejects the god of conventional religion as an impostor. The true God is transcendent beyond all description, and the material world is a prison, not a gift. This makes Gnosticism profoundly countercultural — it denies the goodness of creation, rejects the authority of the creator-god, and places individual spiritual experience above institutional religion.</p>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>The Gospel of Thomas</strong> — 114 sayings of Jesus; no narrative; gnosis-oriented. Free: <a href="https://sacred-texts.com/chr/thomas.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '<li><strong>The Gospel of Philip</strong> — Valentinian sacramental theology</li>';
echo '<li><strong>The Apocryphon of John</strong> — Sethian cosmology; the most systematic Gnostic creation account</li>';
echo '<li><strong>Pistis Sophia</strong> — extensive dialogue between Jesus and Mary Magdalene on cosmic salvation. Free: <a href="https://sacred-texts.com/chr/ps/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '</ul>';

// KABBALAH
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2b6cb0;">⊕ Kabbalah</h2>';
echo '<p><strong>Origin:</strong> Jewish mysticism, Provence and Spain | <strong>Period:</strong> 12th–13th century CE (systematic); ancient roots claimed | <strong>Theism:</strong> Monotheistic (Ein Sof — the Infinite) | <strong>Proselytism:</strong> Traditionally restricted to mature Jewish men; now widely taught | <strong>Apostasy:</strong> Within Judaism\'s framework</p>';
echo '<h3>Origin</h3>';
echo '<p>Kabbalah (Hebrew: "reception" or "tradition") is the mystical dimension of Judaism. While Jewish mysticism has ancient roots (Merkabah — "chariot" mysticism of the 1st–7th centuries CE), Kabbalah as a systematic tradition emerged in Provence and Spain in the 12th–13th centuries. The publication of the <em>Zohar</em> (c. 1280 CE) by Moses de León (attributed to the 2nd-century sage Shimon bar Yochai) established the canonical Kabbalistic text. The Lurianic Kabbalah of Isaac Luria (Safed, 16th century) represents the most influential systematic development.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>Ein Sof</strong> — "Without End" — the true nature of God, utterly unknowable, beyond all attributes, beyond being and non-being. Ein Sof cannot be described or addressed — it is the infinite ground of all existence.</li>';
echo '<li><strong>The Ten Sefirot</strong> — Ein Sof reveals itself through ten emanations (Sefirot), each representing a divine attribute: Keter (Crown), Chokhmah (Wisdom), Binah (Understanding), Chesed (Loving-kindness), Gevurah (Strength/Judgment), Tiferet (Beauty/Harmony), Netzach (Victory/Eternity), Hod (Splendor), Yesod (Foundation), Malkuth (Kingdom). The Sefirot form the Tree of Life — the map of divine and human existence.</li>';
echo '<li><strong>The Four Worlds</strong> — reality exists in four levels: Atziluth (Emanation — purely divine), Beriah (Creation), Yetzirah (Formation), Assiah (Action — the material world). The human soul partakes of all four worlds.</li>';
echo '<li><strong>Tzimtzum</strong> — Luria\'s concept of divine contraction: to create the world, Ein Sof "contracted" into itself, leaving a void (Chalal) in which creation could occur. This answers the question of how the infinite can give rise to the finite.</li>';
echo '<li><strong>Shevirat HaKelim</strong> — "Breaking of the Vessels": during creation, divine light was too intense for the vessels (Sefirot) below Keter; they shattered, scattering "sparks" (Nitzotzot) of divine light into the material world encased in "shells" (Klipot — husks of impurity).</li>';
echo '<li><strong>Tikkun Olam</strong> — "Repair of the World": the human task is to gather the scattered divine sparks through righteous action, prayer, and Torah observance, restoring the cosmic unity shattered at creation. Every human action has cosmic significance.</li>';
echo '<li><strong>The Soul (Neshamah)</strong> — the human soul has five levels: Nefesh (vital soul), Ruach (spirit), Neshamah (divine soul), Chayah (living essence), Yechidah (unique essence, unity with God). Different traditions teach different levels of soul transmigration.</li>';
echo '<li><strong>Gilgul — Reincarnation</strong> — Kabbalah teaches gilgul neshamot (transmigration of souls) as a key doctrine. Souls reincarnate to complete unfulfilled mitzvot (commandments), repair past wrongs, or achieve the spiritual level not attained in previous lives. Lurianic Kabbalah developed this into an elaborate system. The <em>Sefer HaGilgulim</em> (Book of Transmigrations) by Chaim Vital documents Luria\'s teachings on specific soul-roots and their incarnations.</li>';
echo '</ul>';
echo '<h3>Proselytism and Apostasy</h3>';
echo '<p>Traditional Kabbalah was restricted to Jewish men over 40 who had already mastered Torah and Talmud. The reasoning: Kabbalistic knowledge could be dangerous without this foundation. In the modern era, this restriction has largely dissolved — Kabbalah has been taught to non-Jews through the Kabbalah Centre (founded 1965) and through wide publication of texts. This democratization is controversial among traditional Kabbalists.</p>';
echo '<p>Apostasy in Judaism generally means leaving the Jewish faith. A Jewish Kabbalist who converts to another religion has committed apostasy (<em>shemad</em>) — though halacha still considers them Jewish by birth. The consequences within the community include social exclusion; historically, in medieval times, more severe measures. In Kabbalistic cosmology, apostasy represents a profound spiritual failure — a descent toward the Klipot (forces of impurity).</p>';
echo '<h3>Uniqueness</h3>';
echo '<p>Kabbalah is unique in providing Judaism with a detailed map of the divine inner life — a theogony (account of the divine nature) and cosmogony (account of creation) of extraordinary sophistication. It makes every human action cosmically significant through Tikkun Olam. It also provides Judaism with its most sophisticated engagement with evil — the Klipot as necessary "shells" providing boundary and the possibility of free will, not simply as malevolence.</p>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>The Zohar</strong> (c. 1280 CE) — the most important Kabbalistic text. Free: <a href="https://sacred-texts.com/jud/index.htm" target="_blank" rel="noopener">sacred-texts.com/jud</a></li>';
echo '<li><strong>Sefer Yetzirah</strong> ("Book of Formation") — ancient text on the creation of the world through the Hebrew letters and ten Sefirot. Free: <a href="https://sacred-texts.com/jud/sy/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '<li><strong>Sefer HaBahir</strong> — the first systematic Kabbalistic text, c. 12th century</li>';
echo '</ul>';

// NEOPLATONISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Neoplatonism</h2>';
echo '<p><strong>Origin:</strong> Alexandria/Rome | <strong>Period:</strong> 3rd–6th century CE | <strong>Theism:</strong> Monistic (The One beyond being) | <strong>Proselytism:</strong> Philosophical school | <strong>Apostasy:</strong> Not applicable</p>';
echo '<h3>Origin</h3>';
echo '<p>Neoplatonism is the philosophical tradition founded by Plotinus (205–270 CE) in Rome, building on Plato\'s philosophy but transforming it into a systematic metaphysics and spiritual practice. Porphyry, Iamblichus, and Proclus developed the tradition further. Neoplatonism was the last great flowering of pagan philosophy and the primary intellectual framework through which Greek thought influenced early Christianity, Islam (via Al-Farabi, Avicenna), and the Renaissance.</p>';
echo '<h3>Core Doctrine — The Three Hypostases</h3>';
echo '<ul>';
echo '<li><strong>The One (To Hen)</strong> — the absolute first principle, beyond being, beyond thought, beyond all attributes. The One does not think or will — it simply is, and from its overflowing fullness, all reality emanates. The One cannot be named or described — all language about it is metaphorical. This is strict negative theology (apophasis): God is beyond every positive attribute.</li>';
echo '<li><strong>Nous (Divine Mind / Intellect)</strong> — the first emanation from the One; pure thought thinking itself; the realm of Plato\'s Forms (archetypes); eternal, unchanging, perfect. Nous is simultaneously thinker and thought — there is no gap between the two.</li>';
echo '<li><strong>Psyche (World Soul)</strong> — the second emanation; intermediary between the eternal Nous and the temporal material world; contains individual souls as aspects of itself; gives form and life to matter.</li>';
echo '<li><strong>Matter (Hyle)</strong> — the lowest level; not evil in itself but a kind of non-being, the furthest point from the One, lacking form and reality until the World Soul organizes it.</li>';
echo '</ul>';
echo '<h3>Emanation vs Creation</h3>';
echo '<p>Crucially, Neoplatonism teaches <em>emanation</em>, not creation. The One does not choose to create — reality flows from it necessarily, as light flows from the sun without the sun choosing to shine or diminishing in the process. This distinguishes Neoplatonism from Abrahamic creation: God does not make the world from nothing by an act of will; the world flows from God\'s nature necessarily and eternally.</p>';
echo '<h3>The Soul\'s Descent and Return</h3>';
echo '<ul>';
echo '<li><strong>Descent</strong> — individual souls descend from the World Soul into matter through a process of increasing individuation and forgetting of their divine origin.</li>';
echo '<li><strong>The Path of Return (Epistrophe)</strong> — through philosophy (love of wisdom), virtue, and contemplation, the soul can reverse its descent and return, level by level, through Psyche to Nous to union with the One (henosis).</li>';
echo '<li><strong>Reincarnation</strong> — Plotinus accepted reincarnation, following Plato. Souls undergo multiple incarnations in human and animal bodies, in proportion to the virtue or vice of their previous life. The goal is to escape the cycle through philosophy and contemplation.</li>';
echo '</ul>';
echo '<h3>Uniqueness</h3>';
echo '<p>Neoplatonism provided the most rigorous philosophical account of mystical experience in the Western tradition. Plotinus described his own experiences of union with the One in the <em>Enneads</em> — among the most profound first-person accounts of mystical states in any tradition. Its concept of the One beyond being influenced every subsequent Western theology and mysticism: Christian (Augustine, Pseudo-Dionysius, Meister Eckhart), Islamic (Sufism), and Jewish (Kabbalah).</p>';
echo '<h3>Key Text</h3>';
echo '<p><strong>The Enneads</strong> by Plotinus — six groups of nine treatises; the masterwork of ancient philosophy. Free: <a href="https://sacred-texts.com/cla/plotenn/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></p>';

// ALCHEMY
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Alchemy</h2>';
echo '<p><strong>Origin:</strong> Egypt/Greece/Islamic world | <strong>Period:</strong> c. 300 BCE – 1700 CE (peak) | <strong>Theism:</strong> Varies; often Christian monotheism | <strong>Proselytism:</strong> Transmitted master to student | <strong>Apostasy:</strong> Not applicable</p>';
echo '<h3>Origin</h3>';
echo '<p>Alchemy is simultaneously a proto-chemistry, a philosophy of nature, and a spiritual practice. It originated in Hellenistic Egypt (the word derives from Arabic <em>al-kīmiyā</em>, from Greek <em>chēmeia</em>, possibly from Coptic <em>kēme</em> — the Black Land, Egypt). It developed through the Islamic golden age (Jabir ibn Hayyan / Geber, 8th–9th century) and reached its European peak in the 15th–17th centuries before being superseded by modern chemistry. However, its inner, spiritual dimension never disappeared — Jung\'s <em>Psychology and Alchemy</em> (1944) demonstrated that alchemical imagery is a direct expression of psychological transformation.</p>';
echo '<h3>The Two Levels</h3>';
echo '<p>Alchemy operated simultaneously on two levels that were understood as reflections of each other:</p>';
echo '<ul>';
echo '<li><strong>External (Exoteric) Alchemy</strong> — the actual laboratory work: attempting to transmute base metals (lead, copper) into gold or silver; discovering the Philosopher\'s Stone; creating the Elixir of Life (universal medicine/immortality).</li>';
echo '<li><strong>Internal (Esoteric) Alchemy</strong> — the transformation of the alchemist\'s own soul: purifying the base "lead" of the lower nature into the "gold" of spiritual perfection. The laboratory was a mirror of the psyche; the operations were spiritual as much as chemical.</li>';
echo '</ul>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>Prima Materia</strong> — the primordial matter underlying all substances; undifferentiated, chaotic, the starting point for all transformation. The alchemist\'s first task is to find and identify the prima materia.</li>';
echo '<li><strong>The Four Elements</strong> — Earth, Water, Fire, Air as qualities of matter; transformation occurs by changing elemental proportions.</li>';
echo '<li><strong>Sulfur, Mercury, Salt</strong> — the three alchemical principles (Paracelsus): Sulfur = soul, Mercury = spirit, Salt = body. All matter and all human beings are composed of these three principles in different proportions.</li>';
echo '<li><strong>The Philosopher\'s Stone (Lapis Philosophorum)</strong> — the supreme goal: a substance capable of transmuting any metal to gold and healing all disease. In its spiritual dimension, the Stone represents the perfected self — the gold of spiritual realization.</li>';
echo '<li><strong>The Great Work (Magnum Opus)</strong> — the alchemical process in four stages: Nigredo (blackening — putrefaction/dissolution), Albedo (whitening — purification), Citrinitas (yellowing — solar consciousness), Rubedo (reddening — the red stone, perfection/gold).</li>';
echo '<li><strong>Solve et Coagula</strong> — "Dissolve and Coagulate" — the fundamental operation: break down existing forms (solve) to release the divine essence, then reconstitute at a higher level (coagula). Death and rebirth; destruction and creation.</li>';
echo '</ul>';
echo '<h3>Reincarnation</h3>';
echo '<p>Alchemy generally operated within Christian cosmology and did not formally teach reincarnation. However, the alchemical cycle of Nigredo-Albedo-Rubedo structurally mirrors the reincarnation cycle (death-purification-rebirth), and many alchemists drew on Hermetic and Neoplatonic concepts of the soul\'s descent and return.</p>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>The Emerald Tablet (Tabula Smaragdina)</strong> — the foundational Hermetic/alchemical text; contains "As above, so below." Free: <a href="https://sacred-texts.com/alc/emerald.htm" target="_blank" rel="noopener">sacred-texts.com/alc/emerald.htm</a></li>';
echo '<li><strong>The Rosarium Philosophorum</strong> (1550) — illustrated alchemical text; Jung\'s primary source for his psychological interpretation</li>';
echo '<li><strong>Paracelsus — Collected Works</strong> — online at <a href="https://sacred-texts.com/alc/paracel/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '</ul>';

// ROSICRUCIANISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#9b2c2c;">⊕ Rosicrucianism</h2>';
echo '<p><strong>Origin:</strong> Germany | <strong>Period:</strong> 1614 CE (manifestos) | <strong>Theism:</strong> Christian monotheism (esoteric) | <strong>Proselytism:</strong> The Rosicrucians sought out the worthy, not the reverse | <strong>Apostasy:</strong> Not formally addressed</p>';
echo '<h3>Origin</h3>';
echo '<p>Rosicrucianism emerged with the publication of three anonymous German manifestos (1614–1616): the <em>Fama Fraternitatis</em>, the <em>Confessio Fraternitatis</em>, and <em>The Chymical Wedding of Christian Rosenkreutz</em>. These described a secret brotherhood founded by a legendary German knight, Christian Rosenkreutz (1378–1484), who had traveled to the East and received ancient wisdom. The manifestos caused a sensation across Europe — scholars, physicians, and spiritual seekers published hundreds of responses seeking to contact the brotherhood. Whether such a brotherhood actually existed remains debated; the manifestos may have been a literary-spiritual exercise by Johann Valentin Andreae.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>The Universal Reformation</strong> — Rosicrucianism proposed a total spiritual, scientific, and social reformation of Europe based on recovered ancient wisdom.</li>';
echo '<li><strong>Christian Esoterism</strong> — the Rose Cross combined Christian imagery (the cross — Christ\'s redemption) with alchemical/Hermetic imagery (the rose — the perfected soul; also associated with secrecy — <em>sub rosa</em>). It claimed to reveal the true inner meaning of Christianity.</li>';
echo '<li><strong>The Four Elements and Five Essences</strong> — Rosicrucian philosophy incorporated Hermetic, Neoplatonic, Kabbalistic, and alchemical elements into a Christian framework.</li>';
echo '<li><strong>Invisible Brotherhood</strong> — the Rosicrucian brothers were said to travel invisibly, healing the sick without payment, practicing various sciences, and meeting once yearly at the House of the Holy Spirit. Their secrecy was their protection from persecution.</li>';
echo '<li><strong>Grades of Initiation</strong> — knowledge was transmitted in grades; each grade revealed more of the universal wisdom.</li>';
echo '</ul>';
echo '<h3>Legacy</h3>';
echo '<p>Rosicrucianism fed directly into Freemasonry (whose ritual system shares structural features) and into the broader esoteric current of the 18th century. Modern Rosicrucian orders include AMORC (Ancient and Mystical Order Rosae Crucis), founded in the USA in 1915, and the Rosicrucian Fellowship. These organizations teach a mix of esoteric Christianity, Hermetics, and practical mysticism to their members through correspondence courses.</p>';
echo '<h3>Key Text</h3>';
echo '<p><strong>The Chymical Wedding of Christian Rosenkreutz</strong> (1616). Free: <a href="https://sacred-texts.com/sro/rcia/index.htm" target="_blank" rel="noopener">sacred-texts.com/sro/rcia</a></p>';

// FREEMASONRY
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#1a365d;">⊕ Freemasonry</h2>';
echo '<p><strong>Origin:</strong> Scotland/England | <strong>Period:</strong> Operative guilds medieval; speculative Freemasonry 1717 CE | <strong>Theism:</strong> Deistic/non-denominational (requires belief in a Supreme Being) | <strong>Proselytism:</strong> None — must be invited or petition | <strong>Apostasy:</strong> Resignation/expulsion from Lodge</p>';
echo '<h3>Origin</h3>';
echo '<p>Freemasonry emerged from the medieval trade guilds of operative stonemasons, who built the great cathedrals of Europe. These guilds had signs, tokens, and words to identify genuine craftsmen and to protect trade secrets. In the 17th century, non-operative ("speculative") members — gentlemen and intellectuals — began joining the lodges. The first Grand Lodge was established in London in 1717, marking the formal beginning of speculative Freemasonry. By the 18th century, Freemasonry had spread across Europe and America and counted among its members Enlightenment figures including Voltaire, Benjamin Franklin, and George Washington.</p>';
echo '<h3>Core Doctrine and Symbolism</h3>';
echo '<ul>';
echo '<li><strong>The Great Architect of the Universe (GAOTU)</strong> — Freemasonry requires belief in a Supreme Being but does not define this theologically. The lodge contains members of all religions; the GAOTU is their common denominator. This is deliberately non-sectarian rather than atheist.</li>';
echo '<li><strong>The Legend of Hiram Abiff</strong> — the central Masonic myth: Hiram Abiff, master builder of Solomon\'s Temple, was murdered by three ruffians demanding the secret word of a Master Mason. His body was buried; it was later found and "raised" in a specific manner. This drama is enacted in the third degree initiation. Its esoteric meaning: the death and resurrection of the initiated soul; the quest for lost wisdom.</li>';
echo '<li><strong>The Tools of the Mason as Moral Symbols</strong> — the square (moral rectitude), compass (keeping passions within bounds), level (equality), plumb line (uprightness). Masonry uses the language and tools of architecture as an extended metaphor for moral and spiritual construction.</li>';
echo '<li><strong>The Three Degrees</strong> — Entered Apprentice, Fellow Craft, Master Mason. Each degree contains ritual drama, instruction, and the communication of "secrets" (signs, tokens, words). Higher degree systems (Scottish Rite — 33 degrees; York Rite) exist beyond these.</li>';
echo '<li><strong>Freemasonry and Reincarnation</strong> — mainstream Freemasonry does not formally teach reincarnation. However, the Hiramic legend of death and resurrection, interpreted esoterically, resonates with transmigration themes. Certain higher degree bodies and Masonic-adjacent systems (Memphis-Misraïm Rite) explicitly incorporate esoteric doctrines including rebirth.</li>';
echo '</ul>';
echo '<h3>Proselytism and Secrecy</h3>';
echo '<p>Freemasonry never solicits members — a man must ask to join (though he may be encouraged by a member). This reflects the esoteric principle that the teaching must be sought, not imposed. The "secrets" of Freemasonry (signs and words of recognition) are now widely published and effectively public; the real "secret," Masons say, is the transformation that initiation produces in the initiate.</p>';
echo '<h3>Key Text</h3>';
echo '<p><strong>Albert Pike — Morals and Dogma</strong> (1871) — the most comprehensive exposition of Scottish Rite philosophy. Free: <a href="https://sacred-texts.com/mas/md/index.htm" target="_blank" rel="noopener">sacred-texts.com/mas/md</a></p>';

// THEOSOPHY
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2d6a1f;">⊕ Theosophy</h2>';
echo '<p><strong>Origin:</strong> New York, USA | <strong>Period:</strong> 1875 CE | <strong>Founder:</strong> Helena Petrovna Blavatsky (1831–1891) | <strong>Theism:</strong> Monistic panentheism | <strong>Proselytism:</strong> Open membership; books widely published | <strong>Apostasy:</strong> Resignation from Theosophical Society</p>';
echo '<h3>The Founder</h3>';
echo '<p>Helena Petrovna Blavatsky (HPB) was a Russian-born writer and occultist who co-founded the Theosophical Society in New York in 1875 with Henry Steel Olcott and William Quan Judge. A controversial figure — accused by critics of fraud and celebrated by followers as a genuine initiate — she claimed to have spent years in Tibet and Central Asia receiving teachings from "Mahatmas" (Great Souls) — advanced human beings who had evolved beyond ordinary humanity. Her two major works — <em>Isis Unveiled</em> (1877) and <em>The Secret Doctrine</em> (1888) — claimed to reveal the hidden wisdom underlying all religions.</p>';
echo '<h3>Core Doctrine</h3>';
echo '<ul>';
echo '<li><strong>The Secret Doctrine\'s Three Propositions</strong>:</li>';
echo '<li style="list-style:none;padding-left:20px;">1. An Omnipresent, Eternal, Boundless and Immutable Principle upon which all speculation is impossible since it transcends the power of human conception.</li>';
echo '<li style="list-style:none;padding-left:20px;">2. The absolute universality of the law of periodicity — flux and reflux, ebb and flow, observed throughout nature; the underlying principle of reincarnation and karma.</li>';
echo '<li style="list-style:none;padding-left:20px;">3. The fundamental identity of all individual souls with the Universal Oversoul, and the obligatory pilgrimage for every soul through the cycle of Incarnation in accordance with Cyclic and Karmic law.</li>';
echo '<li><strong>The Seven Planes of Existence</strong> — reality is organized in seven interpenetrating planes from the most dense (physical) to the most subtle (divine): Physical, Astral, Mental, Buddhic, Atmic, Monadic, Divine.</li>';
echo '<li><strong>The Seven Root Races</strong> — humanity evolves through seven Root Races, each with seven sub-races. We are currently in the Fifth Root Race (Aryan). Each race develops specific faculties. (Note: "Aryan" in Theosophy refers to the current intellectual humanity, not the racial category perverted by the Nazis — though Theosophy\'s racial schemes were later misappropriated.)</li>';
echo '<li><strong>Reincarnation and Karma</strong> — central Theosophical doctrines. The soul (or Monad) incarnates repeatedly through many lifetimes in an arc of spiritual evolution. Karma is the law of moral causation — every action creates consequences that shape future incarnations. Evolution is spiritual, not merely biological; it spans cosmic timescales.</li>';
echo '<li><strong>The Mahatmas / Masters</strong> — evolved human beings who have completed their human evolution but remain to guide humanity\'s spiritual development. They communicated with Blavatsky through letters and inner dictation.</li>';
echo '</ul>';
echo '<h3>Uniqueness</h3>';
echo '<p>Theosophy was the first Western system to systematically synthesize Hindu, Buddhist, and Western esoteric concepts into a single framework and present it to mass audiences. Its influence on 20th-century spirituality was enormous — it shaped Rudolf Steiner\'s Anthroposophy, Alice Bailey\'s Arcane School, the New Age movement, and provided the conceptual vocabulary (planes, karma, chakras, Masters, Akashic Records) that permeates popular spirituality today.</p>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>The Secret Doctrine</strong> (1888) by HPB. Free: <a href="https://sacred-texts.com/the/sd/index.htm" target="_blank" rel="noopener">sacred-texts.com/the/sd</a></li>';
echo '<li><strong>The Key to Theosophy</strong> (1889) by HPB. Free: <a href="https://sacred-texts.com/the/kt/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '<li><strong>The Voice of the Silence</strong> (1889) by HPB. Free: <a href="https://sacred-texts.com/the/vs/index.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '</ul>';

// THELEMA / GOLDEN DAWN
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#553c9a;">⊕ The Hermetic Order of the Golden Dawn & Thelema</h2>';
echo '<p><strong>Origin:</strong> England | <strong>Period:</strong> Golden Dawn 1888; Thelema 1904 | <strong>Founders:</strong> William Wynn Westcott, S.L. MacGregor Mathers (Golden Dawn); Aleister Crowley (Thelema) | <strong>Theism:</strong> Polytheistic/pantheistic magical system | <strong>Proselytism:</strong> Initiatory — invitation and application</p>';
echo '<h3>The Hermetic Order of the Golden Dawn</h3>';
echo '<p>Founded in London in 1888 by William Wynn Westcott, Samuel Liddell MacGregor Mathers, and William Robert Woodman, the Golden Dawn was the most influential magical order in the English-speaking world. It claimed descent from a German Rosicrucian order through a mysterious "Cipher Manuscript" (possibly fabricated). Its membership included W.B. Yeats, Algernon Blackwood, Arthur Machen, and a young Aleister Crowley. The order synthesized Kabbalah, Tarot, astrology, Enochian magic, Hermeticism, and ceremonial magic into a graded initiatory system of extraordinary sophistication.</p>';
echo '<h3>The Grade System</h3>';
echo '<p>The Golden Dawn used a 10-grade system corresponding to the Kabbalistic Tree of Life: Neophyte through Ipsissimus. Each grade corresponded to a Sephirah and involved specific knowledge, ritual work, and inner development. The grades were divided into three orders: the Outer Order (grades 1–5), the Second Order (Inner Order, grades 5–6, where practical magic was taught), and the Third Order (theoretically the Secret Chiefs — invisible masters).</p>';
echo '<h3>Thelema</h3>';
echo '<p>In 1904, Aleister Crowley (1875–1947) received (or composed — debate continues) a text called <em>The Book of the Law</em> (Liber AL vel Legis), dictated by a being called Aiwass. This text proclaimed the dawning of a new Aeon (the Aeon of Horus) and the central law of Thelema: <strong>"Do what thou wilt shall be the whole of the Law. Love is the law, love under will."</strong></p>';
echo '<ul>';
echo '<li><strong>Thelema</strong> (Greek: "Will") — the supreme principle; every person has a True Will — their deepest, truest purpose — and the spiritual task is to discover and fulfill this Will.</li>';
echo '<li><strong>The False Will vs True Will</strong> — the ego\'s desires are not the True Will; they are distractions. Finding the True Will requires rigorous self-knowledge.</li>';
echo '<li><strong>The Three Aeons</strong> — Thelema teaches that history is divided into Aeons: the Aeon of Isis (matriarchy, nature worship), the Aeon of Osiris (patriarchy, dying-and-rising god religions including Christianity), and the Aeon of Horus (the current age of individual will and self-realization).</li>';
echo '<li><strong>The Holy Guardian Angel</strong> — the central Thelemic magical operation: Knowledge and Conversation of the Holy Guardian Angel — contact with one\'s higher self or divine genius. This is the supreme magical attainment.</li>';
echo '<li><strong>Reincarnation</strong> — Thelema accepts reincarnation; the "Star" (Nuit) that is each individual soul is eternal and reincarnates. "Every man and every woman is a star."</li>';
echo '</ul>';
echo '<h3>Key Texts</h3>';
echo '<ul>';
echo '<li><strong>The Book of the Law</strong> (1904) by Aleister Crowley. Free: <a href="https://sacred-texts.com/oto/engccxx.htm" target="_blank" rel="noopener">sacred-texts.com</a></li>';
echo '<li><strong>777 and Other Qabalistic Writings</strong> by Crowley — the tables of correspondence used in Golden Dawn/Thelemic magic</li>';
echo '</ul>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/eastern/">Eastern Mysticism</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/african/">African Esoteric</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/spirituality/sources/">Texts & Downloads</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">→ World Religions</a>';
echo '</div></div>';
