<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">A structured overview of the 1966 pogroms — causes, events, scale, and consequences.</p>';
echo '<h2>The Context: Nigeria 1960–1966</h2>';
echo '<p>Nigeria\'s First Republic (1960–1966) was characterized by intense regional and ethnic competition. The colonial amalgamation of 1914 had created a country whose major ethnic groups — Hausa-Fulani in the north, Yoruba in the southwest, Igbo in the southeast — had fundamentally different histories, political cultures, and interests. Independence in 1960 did not resolve these tensions; it intensified them as the groups competed for control of the new state\'s patronage and resources.</p>';
echo '<p>The Igbo were uniquely positioned in this competition. They had embraced Western education earlier and more thoroughly than most northern groups, and as a result were heavily represented in the federal civil service, the military officer corps, the railways, the postal service, and commerce throughout Nigeria — including, critically, in the north where millions of Igbo had settled as traders, civil servants, teachers, and laborers. This Igbo presence in the north, built over decades, made them visible and vulnerable.</p>';
echo '<h2>The January 1966 Coup</h2>';
echo '<p>On January 15, 1966, a group of military officers — predominantly Igbo — staged Nigeria\'s first military coup. Prime Minister Abubakar Tafawa Balewa (a northerner), Premiers Ahmadu Bello (northern) and Samuel Akintola (western), and a number of senior military officers (predominantly northern) were killed. The coup\'s leader, Major Chukwuma Nzeogwu, declared its aim as ending corruption and tribalism.</p>';
echo '<p>The coup was widely perceived in the north as an Igbo conspiracy to seize power — this perception, whether accurate or not, was politically decisive. In fact, the coup was not uniformly successful, not uniformly Igbo in composition, and not uniformly anti-northern in its targets (some northern officers survived; some Igbo targets were also killed). But the pattern of killings — which disproportionately eliminated northern leaders — shaped northern perception irreversibly.</p>';
echo '<h2>The Counter-Coup and Its Aftermath</h2>';
echo '<p>On July 29, 1966, northern officers staged a counter-coup. Unlike the January coup, the July counter-coup was explicitly ethnic in character: Igbo officers were specifically targeted and killed across military barracks in Nigeria. General Johnson Aguiyi-Ironsi — the Igbo Supreme Commander who had taken power after the January coup — was killed. General Yakubu Gowon, a northerner from the minority Angas group, assumed power.</p>';
echo '<p>In the weeks following the counter-coup, violence against Igbo soldiers in barracks spread to violence against Igbo civilians in northern cities. The military\'s failure to protect Igbo soldiers from murder by their colleagues signaled that the state would not protect Igbo civilians either.</p>';
echo '<h2>The Pogroms: May–October 1966</h2>';
echo '<p>The mass killing of Igbo civilians in northern Nigeria occurred in two main waves:</p>';
echo '<h3>First Wave — May 1966</h3>';
echo '<p>Following riots in northern cities (Kano, Kaduna, Zaria) triggered by rumors and political agitation against Igbo and southern Nigerian residents. Igbo homes and businesses were attacked; dozens killed. This wave was a prelude rather than the main event.</p>';
echo '<h3>Second and Major Wave — September–October 1966</h3>';
echo '<p>Following the July counter-coup and a period of escalating tension, systematic mass violence against Igbo civilians erupted across northern Nigeria. The scale was unprecedented in Nigerian history. Key characteristics:</p>';
echo '<ul>';
echo '<li><strong>Geographic scope</strong> — killings occurred in cities and towns across all northern states: Kano, Kaduna, Zaria, Jos, Sokoto, Maiduguri, Makurdi, and smaller towns. Igbo living in Middle Belt states were also targeted.</li>';
echo '<li><strong>Organization</strong> — eyewitness accounts and subsequent investigations describe organized groups moving through Igbo neighborhoods with lists of names and addresses; the violence was not spontaneous mob action but coordinated attack</li>';
echo '<li><strong>Military participation</strong> — in some locations, soldiers participated in or facilitated the killings; in virtually all locations, the military and police failed to protect Igbo civilians</li>';
echo '<li><strong>Scale</strong> — estimates range from 10,000 to 100,000 killed; the wide range reflects the absence of systematic documentation; academic consensus tends toward the lower end (10,000–30,000) though some scholars argue for higher figures</li>';
echo '<li><strong>Displacement</strong> — over one million Igbo fled south; they arrived in the Eastern Region with accounts of mass murder, destruction of property, and total loss of everything they had built over decades in the north</li>';
echo '</ul>';
echo '<h2>The Official Response</h2>';
echo '<p>The federal government under Gowon did not prosecute perpetrators. No individuals were tried for the killings. No official investigation with subpoena powers was conducted. The standard government position was that the killings were "regrettable" but essentially a spontaneous popular reaction to the January coup. This official characterization — minimizing organized violence as spontaneous passion — has never been seriously challenged by Nigerian government institutions.</p>';
echo '<p>The British government, which had significant intelligence about events in Nigeria, did not publicly call for accountability. Its primary concern was preserving Nigerian unity and British commercial and strategic interests.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/pogrom/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/pogrom/topics/">Key Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/intro/">→ Biafra</a>';
echo '</div></div>';
