<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Essential references for understanding the 1966 pogroms — primary accounts, historical studies, and documentary sources.</p>';
echo '<h2>Primary Accounts</h2>';
echo '<ul>';
echo '<li><strong>Chinua Achebe</strong> — <em>There Was a Country: A Personal History of Biafra</em> (2012). The most important Igbo literary account; covers the 1966 killings in detail from personal testimony and historical record. Essential.</li>';
echo '<li><strong>Alexander Madiebo</strong> — <em>The Nigerian Revolution and the Biafran War</em> (1980). Account by Biafra\'s army commander; includes his direct experience of the 1966 military killings.</li>';
echo '<li><strong>Ntieyong Akpan</strong> — <em>The Struggle for Secession 1966–1970</em> (1971). Written by Ojukwu\'s Secretary to the Military Government; first-hand account of eastern Nigerian decision-making in 1966–1967.</li>';
echo '</ul>';
echo '<h2>Historical Studies</h2>';
echo '<ul>';
echo '<li><strong>John Stremlau</strong> — <em>The International Politics of the Nigerian Civil War 1967–1970</em> (1977). The standard academic account; covers the 1966 background extensively.</li>';
echo '<li><strong>Lasse Heerten and A. Dirk Moses</strong> — "The Nigerian-Biafran War: Postcolonial Conflict and the Question of Genocide" (2014). The most rigorous scholarly engagement with the genocide question.</li>';
echo '<li><strong>Toyin Falola and Matthew Heaton</strong> — <em>A History of Nigeria</em> (2008). Places the 1966 events in the broader context of Nigerian history.</li>';
echo '</ul>';
echo '<h2>Journalism</h2>';
echo '<ul>';
echo '<li><strong>Frederick Forsyth</strong> — <em>The Biafra Story</em> (1969). Contemporary journalistic account from the Biafran side; includes reporting on the 1966 pogroms based on eyewitness testimony.</li>';
echo '<li><strong>Auberon Waugh and Suzanne Cronje</strong> — <em>Biafra: Britain\'s Shame</em> (1969). Documents British government complicity.</li>';
echo '</ul>';
echo '<h2>Declassified Documents</h2>';
echo '<ul>';
echo '<li><strong>British National Archives</strong> — FCO files on Nigeria 1966–1970; now substantially declassified; available at Kew, London. Key files document British knowledge of the killings in real time.</li>';
echo '<li><strong>US State Department cables</strong> — available through the National Security Archive (nsarchive.gwu.edu); American diplomatic reports from Lagos and Enugu during 1966.</li>';
echo '</ul>';
echo '<h2>Fiction and Memory</h2>';
echo '<ul>';
echo '<li><strong>Chimamanda Ngozi Adichie</strong> — <em>Half of a Yellow Sun</em> (2006). The most celebrated fictional treatment of the civil war; the 1966 pogroms are a significant narrative element.</li>';
echo '<li><strong>Flora Nwapa</strong> — <em>Never Again</em> (1975). Short novel about a woman\'s experience of the war.</li>';
echo '</ul>';
echo '<h2>Online Resources</h2>';
echo '<ul>';
echo '<li><strong>Biafra Foundation</strong> — documentation of 1966 events and ongoing memory work</li>';
echo '<li><strong>The Igbo Cultural Archive</strong> — community documentation projects</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/pogrom/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/pogrom/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/sources/">→ Biafra Sources</a>';
echo '</div></div>';
