<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">An overview of Igbo and African figures across the major periods of history.</p>';
echo '<h2>The Precolonial Era</h2>';
echo '<p>Before European contact, Igbo society produced its own forms of distinction. Titled men of the <em>Ozo</em> and <em>Nze</em> orders, long-distance traders who connected the hinterland to the coast, skilled bronze-casters at Igbo-Ukwu, and <em>dibia</em> — specialists in medicine, divination, and ritual — constituted a recognizable intellectual and social elite. Their names are largely lost to written record, but the archaeological and oral record makes clear that precolonial Igbo society was not without its great individuals.</p>';
echo '<h2>The Slave Trade Era (1600s-1800s)</h2>';
echo '<p>The Atlantic slave trade forced Igbo people into global history in the most brutal way. Millions were taken; a few survived to leave records. Olaudah Equiano is the towering figure of this period — enslaved, self-educated, freed, and eventually a central actor in the British abolitionist movement. His <em>Interesting Narrative</em> (1789) is the first major autobiographical text by an African writer in English and one of the most important books of the 18th century.</p>';
echo '<h2>The Colonial Period (1850s-1960)</h2>';
echo '<p>Colonial education produced a new kind of Igbo figure: the Western-educated professional who moved between African and European worlds. Nnamdi Azikiwe, trained in the United States and active in Britain, became Nigeria\'s first president. Herbert Macaulay, though Yoruba, worked alongside Igbo nationalists to build the structures of independence. Igbo women — Omu Okwei, the Aba Women, Margaret Ekpo — organized politically in ways that colonial authorities consistently underestimated.</p>';
echo '<h2>The Postcolonial and Diaspora Era (1960-Present)</h2>';
echo '<p>After independence, Igbo figures entered global culture with new force. Chinua Achebe\'s fiction was translated into more than sixty languages. Wole Soyinka (Yoruba) and other Nigerian writers shared an international stage with Igbo authors Buchi Emecheta, Chimamanda Ngozi Adichie, and Chris Abani. In medicine, science, law, and business, Igbo professionals in Britain, the United States, and Canada built careers that would have been impossible two generations earlier.</p>';
echo '<h2>After Biafra</h2>';
echo '<p>The Biafra war (1967-1970) produced its own generation of significant figures: Odumegwu Ojukwu, the military commander; Christopher Okigbo, the poet who died in battle; Chinua Achebe, who served as Biafra\'s cultural ambassador; and the countless unnamed doctors, nurses, and relief workers who sustained a besieged population. The aftermath of Biafra shaped Igbo identity for decades and sent a new wave of people into the diaspora.</p>';
echo '</div>';