<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Key Igbo and African figures in history, culture, politics, and the arts.</p>';
echo '<h2>Olaudah Equiano (c. 1745–1797)</h2>';
echo '<p>Born in the Igbo heartland, enslaved as a child, transported across the Atlantic, and eventually freed, Equiano settled in London and became the most prominent Black abolitionist in Britain. His autobiography — <em>The Interesting Narrative of the Life of Olaudah Equiano</em> (1789) — was a bestseller, going through nine editions in his lifetime. He lobbied Parliament, toured Britain on speaking engagements, and married an Englishwoman, Susanna Cullen. He is the ancestor of everything that followed in the British-Nigerian relationship.</p>';
echo '<h2>Nnamdi Azikiwe (1904–1996)</h2>';
echo '<p>Born in Zungeru to an Igbo father, educated in the United States at Howard, Storer, and Lincoln universities, Azikiwe returned to West Africa in the 1930s to build the institutions of nationalism. As editor of the <em>West African Pilot</em> and eventually as Nigeria\'s first President (1963–1966), he was the dominant political figure of his generation.</p>';
echo '<h2>Chinua Achebe (1930–2013)</h2>';
echo '<p>Born in Ogidi, Anambra State, Achebe published <em>Things Fall Apart</em> in 1958 — one year before Nigerian independence — and changed African literature permanently. The novel has been translated into more than sixty languages and sold more than twenty million copies. His account of Biafra, <em>There Was a Country</em> (2012), appeared a year before his death.</p>';
echo '<h2>Christopher Okigbo (1932–1967)</h2>';
echo '<p>Widely regarded as the finest Igbo poet of the 20th century, Okigbo\'s poetry — dense, allusive, drawing on Igbo ritual and Western modernism — was collected in <em>Labyrinths</em> (1971). When Biafra declared independence, Okigbo enlisted. He was killed in combat near Nsukka in August 1967, aged thirty-five.</p>';
echo '<h2>Odumegwu Ojukwu (1933–2011)</h2>';
echo '<p>Born in Nnewi, educated at Epsom College and Lincoln College Oxford, Ojukwu entered the Nigerian army and rose quickly. After the 1966 pogroms and the failure of the Aburi Accord, he declared the independent Republic of Biafra on 30 May 1967. He led Biafra through thirty months of war before going into exile in Côte d\'Ivoire in January 1970.</p>';
echo '<h2>Buchi Emecheta (1944–2017)</h2>';
echo '<p>Born in Lagos to Igbo parents, Emecheta arrived in London in 1962. After raising five children alone, she studied sociology at the University of London and wrote. Her novels — <em>Second Class Citizen</em> (1974), <em>The Joys of Motherhood</em> (1979) — documented the experience of African women in both Nigeria and Britain with a directness that made her one of the most important feminist voices of her era.</p>';
echo '<h2>Flora Nwapa (1931–1993)</h2>';
echo '<p>Born in Oguta, educated at University College Ibadan and the University of Edinburgh, Nwapa\'s novel <em>Efuru</em> (1966) was the first work by an African woman published by Heinemann\'s African Writers Series. She went on to found her own publishing company, Tana Press, becoming the first African woman to own and run a major publishing house.</p>';
echo '<h2>Chimamanda Ngozi Adichie (1977–)</h2>';
echo '<p>Born in Enugu and raised in Nsukka, Adichie\'s novels — <em>Purple Hibiscus</em> (2003), <em>Half of a Yellow Sun</em> (2006), <em>Americanah</em> (2013) — and her essays have made her one of the most widely read writers in the world. Her TED talks "The Danger of a Single Story" and "We Should All Be Feminists" have been watched by tens of millions of people.</p>';
echo '<h2>Omu Okwei (1872–1943)</h2>';
echo '<p>Born in Ossomari on the Niger, Okwei became the dominant long-distance trader in the Niger Delta in the early 20th century — commanding a commercial network that connected the interior to the coast and competed directly with European trading companies. She was recognized by the Ossomari community and the British colonial administration as Omu — the title reserved for the most senior woman in the community.</p>';
echo '</div>';