<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Five Centuries of Igbo Resistance</h2>';

echo '<h3>I. Resistance to the Atlantic Slave Trade (15th–19th centuries)</h3>';
echo '<p>The Atlantic slave trade did not encounter a passive Igbo population. The societies of the Niger Delta and hinterland responded to the trade with a range of strategies: flight into less accessible areas, the strengthening of defensive alliances, the development of warrior institutions, and in some cases the active participation in the trade as a mechanism of protecting one\'s own community by supplying others. The Aro Confederacy — centred on the Aro Chukwu oracle at Arochukwu — dominated the inland slave trade routes and used the authority of the oracle to acquire captives for sale to European traders at the coast. This participation in the trade by some Igbo sub-groups complicates simple narratives of victimhood, but it does not diminish the fact that the trade devastated Igbo communities across the region and that its termination — achieved through British naval suppression and the abolition of the British slave trade in 1807 — was not the result of Igbo agency but of external political forces.</p>';
echo '<p>What is less documented is the internal resistance: the communities that refused to sell their members, the individuals who escaped, the cultural and religious mechanisms that communities developed to protect themselves from capture. The Igbo practice of mass suicide rather than capture — documented in the Igbo Landing incident of 1803, when a group of Igbo captives drowned themselves in the waters off St. Simons Island, Georgia, rather than submit to enslavement — represents an extreme expression of this refusal.</p>';

echo '<h3>II. Anti-Colonial Resistance (1885–1945)</h3>';
echo '<p>British colonial penetration of Igboland was neither swift nor uncontested. The Royal Niger Company\'s commercial monopoly, established in 1886, generated immediate Igbo resistance through boycotts, attacks on company stations, and the protection of trade routes from company control. When the British government took direct control in 1900, it faced a population that had no tradition of centralised submission to external authority and that possessed, in the age-grade system and the village assembly, institutions capable of rapid collective action.</p>';
echo '<p>The Ekumeku movement in Western Igboland (1898–1911) mounted the most sustained armed resistance to British penetration. A secret society that coordinated attacks on British outposts, missionary stations, and collaborating local rulers across a wide area, the Ekumeku was suppressed only after multiple British military expeditions and the capture and imprisonment of its leadership. The Aro Expedition of 1901–1902 destroyed the Aro Chukwu oracle — the religious and commercial centre of the inland trade network — in an operation that required 87 officers, 3,161 men, and supporting naval forces. These were not police actions against criminals; they were wars against a resistant population.</p>';
echo '<p>The Women\'s War of 1929 — <em>Ogu Umunwanyi</em> in Igbo — was the largest and most significant anti-colonial uprising in Nigerian history. Triggered by rumours that the British intended to tax women, hundreds of thousands of women across southeastern Nigeria rose in coordinated protest: singing, dancing, demanding the resignations of warrant chiefs, attacking Native Administration courts and European trading stores. The British response was armed suppression: 55 women were killed and 50 wounded in the Aba and Utu Etim Ekpo incidents. The uprising forced a fundamental revision of British colonial policy in southeastern Nigeria, leading to the abolition of the warrant chief system and the introduction of a modified form of indirect rule more attentive to existing Igbo political structures. It was a political victory achieved at the cost of women\'s lives.</p>';

echo '<h3>III. The Biafra War (1967–1970)</h3>';
echo '<p>The Biafra War was the defining struggle of 20th-century Igbo history. Its immediate causes were the 1966 military coups and the pogroms against Igbo living in northern Nigeria in which between 30,000 and 100,000 people were killed and over a million displaced. Its deeper causes were the structural imbalances of the Nigerian federal state — the dominance of the Hausa-Fulani north in federal politics and the military, the exclusion of Igbo from key federal positions after the July 1966 counter-coup, and the failure of the Aburi Accord (January 1967) to produce the confederal arrangement that Ojukwu and the Eastern Region sought.</p>';
echo '<p>The secession of Biafra (May 30, 1967) and the subsequent federal military campaign produced a war of extraordinary brutality. The federal blockade of Biafra — cutting off food, medicine, and supplies to a population of approximately 14 million people — produced a famine in which between 500,000 and 2 million people, predominantly children, died of starvation. The images of kwashiorkor-afflicted Biafran children became the founding images of modern humanitarian media. The war ended in January 1970 with Biafra\'s military collapse and Ojukwu\'s flight into exile.</p>';
echo '<p>The federal government\'s post-war policy — "No victor, no vanquished" — was a political formula that concealed a systematic economic and political marginalisation of the Igbo. The abandoned property policy dispossessed Igbo of property in other regions. The twenty-pound limit on bank account withdrawals wiped out Igbo savings. Federal reconstruction bypassed the former Eastern Region. The wounds of the war have never been honestly addressed by the Nigerian state.</p>';

echo '<h3>IV. Resistance to Military Dictatorship (1966–1999)</h3>';
echo '<p>Nigeria\'s military era (1966–1979; 1983–1999) produced its own forms of resistance. The pro-democracy movements of the late 1980s and 1990s — the Campaign for Democracy, the National Democratic Coalition, the human rights lawyers and journalists who maintained pressure under Babangida and Abacha — were pan-Nigerian in composition but drew heavily on Igbo and Yoruba civil society traditions. The annulment of the June 12, 1993 election — won by Moshood Abiola — and the subsequent crackdown produced the most sustained pro-democracy mobilisation in Nigerian history.</p>';
echo '<p>Ken Saro-Wiwa\'s Movement for the Survival of the Ogoni People (MOSOP) represented a distinct form of resistance: the assertion of minority rights within the minority rights framework, combining environmental justice demands with political self-determination claims. His execution by the Abacha government in November 1995 — along with eight other Ogoni activists — produced international outrage and Nigeria\'s suspension from the Commonwealth. It also demonstrated the lengths to which the Nigerian military state would go to protect the oil revenue that sustained it.</p>';

echo '<h3>V. Contemporary Struggles (1999–present)</h3>';
echo '<p>The return to civilian rule in 1999 did not end Igbo political struggle; it transformed its forms. IPOB — the Indigenous People of Biafra, led by Nnamdi Kanu from 2012 — has pursued self-determination through a combination of media agitation (Radio Biafra), mass mobilisation, and international lobbying. Its proscription by the Nigerian government as a terrorist organisation, and the military operations against its members in the southeast, represent the continuation of state violence against Igbo political expression. The sit-at-home orders that IPOB has imposed on the southeast — and the compliance with which large sections of the Igbo population have met them — demonstrate both the organisation\'s popular resonance and the costs its tactics impose on ordinary life.</p>';
echo '<p>The ENDSARS movement of October 2020 — a youth-led protest against police brutality that swept through Nigerian cities — was not specifically Igbo but reflected conditions experienced acutely in Igbo cities. The Lekki tollgate massacre of October 20, 2020, in which Nigerian Army personnel opened fire on unarmed protesters, was the defining atrocity of the movement. The movement\'s suppression without political accountability demonstrated the continuity between military-era and civilian-era state violence.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/resistance/overview/">→ Resistance</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/slavery/overview/">→ Slavery</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/biafra/overview/">→ Biafra</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/history/overview/">→ History</a>';
echo '</div>';
echo '</div>';