<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Those Who Led, Those Who Paid</h2>';
echo '<h3>The Women of 1929 (collective)</h3>';
echo '<p>The Women\'s War of 1929 had no single leader — and that was precisely its strength. The uprising was coordinated through the existing networks of Igbo women\'s associations, market organisations, and age-grade groups, without any individual whose arrest could decapitate the movement. The British colonial inquiry struggled to find leaders to prosecute because the movement\'s leadership was distributed through the entire social fabric of Igbo women\'s collective life. The women who died at Aba and Utu Etim Ekpo are not individually named in most historical accounts — they died as members of a collective. This platform names them collectively as the founders of the Igbo tradition of mass civil resistance.</p>';
echo '<h3>Margaret Ekpo (1914-2006)</h3>';
echo '<p>Margaret Ekpo was the most significant Igbo woman politician of the independence era. Born in Aba, she became a market trader, community organiser, and political activist who built her political base through the networks of market women in the Eastern Region. She was elected to the Eastern House of Assembly in 1954 and served as a member of the Federal House of Representatives. Her political philosophy combined women\'s rights with anti-colonial nationalism — she organised boycotts of European goods, led delegations to colonial authorities, and trained a generation of women political organisers. She represents the continuity between the Women\'s War tradition and formal electoral politics.</p>';
echo '<h3>Odumegwu Ojukwu (1933-2011)</h3>';
echo '<p>Chukwuemeka Odumegwu Ojukwu is the most contested figure in modern Igbo history. The son of one of Nigeria\'s wealthiest men, educated at Epsom College and Lincoln College Oxford, he became Military Governor of the Eastern Region after the July 1966 counter-coup and the leader who declared Biafran independence on May 30, 1967. His decision to secede — taken after the failure of the Aburi Accord and in the context of mass killings of Igbo in the north — was supported by the overwhelming majority of the Igbo population. He fled to Côte d\'Ivoire in January 1970 as Biafra collapsed, was pardoned in 1982, returned to Nigeria, and spent the remainder of his life as a political figure advocating for Igbo interests. He died in London in 2011 and was buried with full military honours — a belated and incomplete recognition of his place in Nigerian history.</p>';
echo '<h3>Ken Saro-Wiwa (1941-1995)</h3>';
echo '<p>Ken Saro-Wiwa was a writer, television producer, businessman, and activist who became the most significant environmental justice martyr in African history. Born in Bori, Rivers State, of Ogoni heritage, he built a media career that included the creation of <em>Basi and Company</em>, the most popular television series in Nigerian history. He used his public platform and his business resources to fund and lead MOSOP — the Movement for the Survival of the Ogoni People — which he built from a small advocacy organisation into a mass movement that mobilised 300,000 Ogoni in a single demonstration in January 1993. His execution by the Abacha government on November 10, 1995 — with eight other Ogoni activists — was intended to silence him. It transformed him into a global symbol of resistance to both corporate extractivism and military dictatorship.</p>';
echo '<h3>Nnamdi Kanu (b. 1967)</h3>';
echo '<p>Nnamdi Kanu is the most polarising figure in contemporary Igbo politics. Born in Isiama Afaraukwu, Abia State, he built Radio Biafra from London into the most listened-to Igbo political broadcast in the world, combining Biafran nationalism with scathing critique of the Nigerian state. His arrest in 2015, flight in 2017, extraordinary rendition from Kenya in 2021, and ongoing detention represent the Nigerian state\'s most direct confrontation with the contemporary self-determination movement. His significance lies in what his existence demonstrates: that fifty years after the end of the Biafra War, a significant portion of the Igbo population remains unconvinced that the Nigerian federal state represents their interests or guarantees their safety.</p>';
echo '</div>';