<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Five Sites of Struggle</h2>';

echo '<h3>1. The Women\'s War of 1929: The Largest Anti-Colonial Uprising in Nigerian History</h3>';
echo '<p>The Women\'s War — <em>Ogu Umunwanyi</em> — of November-December 1929 is the most significant and least adequately remembered event in Igbo political history. Triggered by rumours that the British colonial administration intended to extend direct taxation to women, the uprising mobilised hundreds of thousands of women across Owerri and Calabar Provinces in a form of protest rooted in traditional Igbo women\'s collective action: the practice of "sitting on a man" — surrounding the compound of an offender, singing, dancing, and demanding redress until satisfaction was obtained.</p>';
echo '<p>The scale and coordination of the uprising were extraordinary. Women attacked Native Administration courts — the symbols of British indirect rule and the warrant chief system — destroyed court buildings, and released prisoners. They forced the resignation of warrant chiefs. They demanded the removal of European trading stores. The uprising spread across an area of approximately 6,000 square miles involving tens of thousands of women acting in coordinated fashion without any centralised leadership structure — a demonstration of the organisational capacity of Igbo women\'s institutions that the British completely failed to anticipate.</p>';
echo '<p>The British response was armed suppression. At Aba, soldiers fired into a crowd of women, killing 32. At Utu Etim Ekpo, 18 more were killed. The Aba Commission of Inquiry that followed acknowledged the legitimacy of the women\'s grievances and recommended the abolition of the warrant chief system — a fundamental reform of British colonial governance in southeastern Nigeria. The women won the political argument. They paid for it with their lives.</p>';

echo '<h3>2. The Biafra War: Survival as Politics</h3>';
echo '<p>The Biafra War cannot be understood as simply a failed secession. It must be understood as a survival response to a genocide. The pogroms of 1966 — in which Igbo living in northern Nigeria were systematically killed, their property destroyed, their women raped, and their bodies mutilated — were not random violence. They were organised. They were participated in by Nigerian Army soldiers. They were watched and largely unreported by the federal government. Over a million Igbo fled the north in the largest internal displacement in Nigerian history to that point.</p>';
echo '<p>The Aburi Accord of January 1967, negotiated between Ojukwu and Gowon in Ghana, produced an agreement for a loose confederation that would have kept Nigeria together while protecting Igbo safety. It was repudiated by Gowon on his return to Lagos under pressure from northern officers and British advisers. The declaration of Biafra (May 30, 1967) was not an act of aggression. It was the consequence of a federal government that had demonstrated it could not or would not protect its Igbo citizens.</p>';
echo '<p>The federal blockade — cutting off food, medicine, and supplies — was a deliberate strategy. Obafemi Awolowo, then federal Finance Commissioner, articulated the logic: starvation was a legitimate weapon of war. The images of starving Biafran children that reached the world in 1968-1969 produced the first modern humanitarian media crisis and the founding of organisations like Médecins Sans Frontières (whose founders were French doctors who served in Biafra). The war ended in January 1970. The starvation, the abandoned property, the twenty-pound bank limit, the federal reconstruction that bypassed the Igbo heartland — these were the peace.</p>';

echo '<h3>3. Ken Saro-Wiwa and the Ogoni Struggle: Ecology as Politics</h3>';
echo '<p>Ken Saro-Wiwa was not Igbo — he was Ogoni, from the Rivers State minority communities whose land sits atop some of Nigeria\'s richest oil reserves. But his struggle belongs in the Igbo Struggles subject because it represents a form of political resistance that the broader Niger Delta and Igbo experience shares: the struggle against the extraction of resources from minority communities without consent, compensation, or environmental protection.</p>';
echo '<p>Shell\'s operations in Ogoniland, begun in 1958, produced decades of oil spills, gas flaring, and environmental devastation that destroyed the agricultural and fishing economy on which Ogoni communities depended. MOSOP — the Movement for the Survival of the Ogoni People, founded by Saro-Wiwa in 1990 — demanded a share of oil revenues, environmental cleanup, and political autonomy for the Ogoni within the Nigerian federation. The Ogoni Bill of Rights (1990) articulated these demands in terms that drew on international human rights law and the emerging framework of indigenous peoples\' rights.</p>';
echo '<p>The Abacha government arrested Saro-Wiwa in 1994, charged him and eight other Ogoni activists with the murder of four pro-government Ogoni chiefs (in proceedings that were widely recognised as a travesty), and executed them on November 10, 1995. The execution produced Nigeria\'s suspension from the Commonwealth and international sanctions. Shell\'s culpability — its provision of logistics to the Nigerian military, its failure to use its leverage with the Nigerian government to prevent the executions — was documented in subsequent legal proceedings and a 2009 settlement in which Shell paid $15.5 million to the families of the executed men without admitting liability.</p>';

echo '<h3>4. IPOB and the Self-Determination Movement</h3>';
echo '<p>The Indigenous People of Biafra — IPOB — was founded by Nnamdi Kanu in 2012 and has become the most significant Igbo political movement of the 21st century. Its core demand is a referendum on Biafran independence, conducted under international supervision. Its methods have included Radio Biafra broadcasts (from London, until the Nigerian government pressured the UK authorities to shut it down), mass rallies in the southeast, sit-at-home strikes, and international lobbying at the UN and in diaspora communities across Europe and North America.</p>';
echo '<p>The Nigerian government\'s response has been military. Operation Python Dance (2017) deployed the Nigerian Army to the southeast in operations that killed IPOB members and supporters. Nnamdi Kanu was arrested in 2015, released on bail, fled Nigeria in 2017 after the military operation on his family compound, was extraordinarily rendered from Kenya to Nigeria in 2021, and has been held in detention since then in conditions that his lawyers describe as torture. His trial has proceeded slowly and controversially.</p>';
echo '<p>The sit-at-home orders that IPOB imposes on the southeast — typically on Mondays and on dates significant to the Biafra struggle — have produced a complex political situation. Compliance is widespread, driven by a combination of genuine political support, fear of IPOB enforcement, and the practical reality that non-compliance carries risks. The economic costs to the southeast — schools closed, markets shut, businesses paralysed — are enormous and are borne primarily by the communities IPOB claims to represent. This contradiction between the movement\'s political goals and the costs its tactics impose on ordinary Igbo life is the central tension of contemporary Igbo politics.</p>';

echo '<h3>5. ENDSARS and Youth Movements: The New Politics</h3>';
echo '<p>The ENDSARS movement of October 2020 was not specifically Igbo, but it was deeply Nigerian — and it demonstrated both the potential and the limits of cross-ethnic youth mobilisation against state violence. The movement began as a demand for the disbandment of SARS (Special Anti-Robbery Squad), a police unit notorious for extrajudicial killings, extortion, and torture particularly targeting young men. It grew within days into a broader movement against police brutality, government corruption, and the failure of civilian governance to deliver basic security and dignity.</p>';
echo '<p>The Lekki tollgate massacre of October 20, 2020 — in which soldiers of the Nigerian Army opened fire on unarmed protesters, killing an undetermined number (the Lagos State Judicial Panel of Inquiry found that at least 11 people died) — was the defining atrocity of the movement. The government\'s response — denial, then partial acknowledgement, then impunity — demonstrated the continuity between military-era and civilian-era approaches to political dissent. No soldier has been prosecuted. No senior official has been held accountable.</p>';
echo '<p>ENDSARS produced no institutional political change. What it produced was a generation of young Nigerians — including young Igbo — with direct experience of state violence and with the organisational skills, the media literacy, and the political consciousness that come from having built a movement from scratch in ten days. That is not nothing. It is, historically, how political traditions begin.</p>';
echo '</div>';