<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Five Phases of the Arab-African Relationship</h2>';
echo '<h3>I. Pre-Islamic Contact (antiquity–630 CE)</h3>';
echo '<p>The relationship between the Arabian Peninsula and the African continent is older than Islam. Arab and South Arabian traders operated along the East African coast from at least the 1st century CE, trading in ivory, gold, and enslaved people through Red Sea and Indian Ocean networks. The Kingdom of Aksum — centred in what is now Ethiopia and Eritrea — controlled the Red Sea trade routes and maintained diplomatic relations with Rome, Persia, and the Arabian kingdoms. When the Prophet Muhammad\'s early followers faced persecution in Mecca, it was to Aksum that they fled — the Hijra to Abyssinia (615 CE). Islam\'s survival in its earliest years depended on African protection. This fact is foundational and rarely emphasised.</p>';
echo '<h3>II. The Arab Conquests and North Africa (639–711 CE)</h3>';
echo '<p>The Arab Muslim conquest of North Africa began with the invasion of Egypt in 639 CE and was largely complete by 711 CE. The conquest transformed North Africa permanently. The indigenous Berber populations were Arabised over centuries through intermarriage, conversion, and cultural assimilation, but also through military suppression and the subordination of Berber languages and traditions. The Coptic Christian population of Egypt was reduced from majority to minority over several centuries. The ancient Christian churches of North Africa — the churches of Tertullian, Cyprian, and Augustine — were largely extinguished. The Amazigh cultural revival of the late 20th and early 21st centuries — demanding recognition of Tamazight languages and Berber historical identity — is in part a reckoning with what the Arab conquests did to indigenous North African cultures.</p>';
echo '<h3>III. The Trans-Saharan Slave Trade (650–1900 CE)</h3>';
echo '<p>Beginning around 650 CE and continuing into the early 20th century, the trans-Saharan slave trade transported an estimated 17 million Africans into slavery in North Africa, the Arabian Peninsula, Persia, the Ottoman Empire, and South Asia. West African captives from Hausaland, Bornu, and the Sahel were marched northward to Tripoli, Tunis, and Cairo. East African captives from the Swahili coast were shipped from Zanzibar and Kilwa to Oman and the Persian Gulf. The Sultanate of Zanzibar, established by Omani Arabs in the 19th century, was the organisational centre of the East African trade. Mortality rates during trans-Saharan transportation were catastrophic. The trade ended not through Arab abolitionism but through European colonial pressure — suppressed from outside, not abolished from within.</p>';
echo '<h3>IV. Islam in Sub-Saharan Africa (11th century–present)</h3>';
echo '<p>Islam spread into sub-Saharan Africa through trade routes rather than conquest. West African Islam generated a remarkable tradition of Islamic scholarship centred in Timbuktu, Kano, and other cities — the Sankore University at Timbuktu was, at its height in the 15th and 16th centuries, one of the major centres of Islamic learning in the world. The 19th century jihad movements — of which Usman dan Fodio\'s Sokoto Jihad (1804–1808) was the most consequential — transformed commercial Islam into a political programme. The Sokoto Caliphate organised northern Nigeria under Islamic administration that the British preserved through indirect rule. The consequences for Igbo-Nigerian relations were profound: the 1966 pogroms, the Biafra War, and contemporary Boko Haram violence are all shaped by this structural fault line.</p>';
echo '<h3>V. Contemporary Arab-African Relations</h3>';
echo '<p>Gulf Arab states have invested heavily in sub-Saharan Africa through sovereign wealth funds, infrastructure projects, agricultural land leasing, and Islamic charitable organisations. The treatment of African migrants in Arab countries — particularly under the Gulf kafala sponsorship system, and in Libyan detention centres documented as sites of torture and slave auctions — has generated repeated controversy. The question of anti-Black racism in the Arab world is contested but real, and has been named by African intellectuals including Wole Soyinka with a directness that official pan-African discourse has long avoided.</p>';
echo '</div>';