<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Figures at the Arab-African Intersection</h2>';
echo '<h3>Ibn Battuta (1304–c.1368)</h3>';
echo '<p>The Moroccan scholar and traveller Ibn Battuta is the most important Arab witness to medieval sub-Saharan Africa. His <em>Rihla</em> (Journey) contains detailed descriptions of the Mali Empire under Mansa Suleyman, whom he visited in 1352–1353, the trans-Saharan trade routes, and the Islamic scholarly communities of the western Sudan. He was simultaneously impressed by the Mali Empire\'s wealth, legal order, and piety, and critical of its deviations from North African Islamic orthodoxy — particularly its gender culture, in which women went unveiled and received male visitors freely. He is the most significant Arab voice in the early history of sub-Saharan African Islam.</p>';
echo '<h3>Usman dan Fodio (1754–1817)</h3>';
echo '<p>Usman dan Fodio is the figure whose actions most directly shaped the Arab-Islamic connection to Igbo political experience. A Fulani Islamic scholar in the Hausa state of Gobir, he launched a jihad in 1804 that within four years established the Sokoto Caliphate across what is now northern Nigeria and parts of Niger and Cameroon. Dan Fodio did not target the Igbo directly. But the Sokoto Caliphate he founded organised northern Nigeria under Islamic governance that British colonialism preserved intact, creating the structural conditions for Hausa-Fulani political dominance that produced the 1966 pogroms and the Biafra War.</p>';
echo '<h3>Gamal Abdel Nasser (1918–1970)</h3>';
echo '<p>Egypt\'s President Nasser is the Arab leader who most actively cultivated African solidarity. His <em>The Philosophy of the Revolution</em> (1955) positioned Egypt as a bridge between the Arab and African worlds. He hosted African liberation movements in Cairo and was a founding figure of the Non-Aligned Movement. The limits of his African solidarity were exposed by his support for the Nigerian federal government during the Biafra War — Egypt backed the federal side, prioritising Arab League solidarity with the Muslim north over solidarity with Igbo civilians under blockade. This contradiction has not been forgotten.</p>';
echo '<h3>Muammar Gaddafi (1942–2011)</h3>';
echo '<p>Gaddafi had the most extravagant and most damaging relationship with sub-Saharan Africa of any Arab leader. In his later years he channelled Libyan oil revenue into African Union institutions and sought to create a United States of Africa. He was simultaneously the continent\'s most generous state funder of pan-African institutions and one of its most destabilising forces — his weapons supplies to West African conflicts contributed to hundreds of thousands of deaths. His overthrow in 2011 destabilised the entire Sahel, flooding the region with weapons and creating the conditions for the Mediterranean people-smuggling networks and the slave markets documented in Libya in 2017.</p>';
echo '<h3>Wole Soyinka (b. 1934) — On Arab Anti-Blackness</h3>';
echo '<p>The Nigerian Nobel laureate Wole Soyinka has been one of the most consistent African voices naming Arab anti-Blackness as a dimension of the African experience that pan-African solidarity frameworks have been reluctant to confront. In essays and public speeches over several decades, he has argued that the Arab slave trade and its cultural legacy of anti-Black racism represent a debt owed to Africa that is no less real for being politically inconvenient to acknowledge. He is included here as an African thinker whose engagement with the Arab world is part of the Mkomigbo story.</p>';
echo '</div>';