<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>What to Read, and Why</h2>';
echo '<h3>The Trans-Saharan Slave Trade</h3>';
echo '<ul>';
echo '<li><strong>Paul Lovejoy, <em>Transformations in Slavery</em> (1983; 3rd ed. 2012)</strong> — The standard academic account of African slavery systems including the trans-Saharan trade. Essential starting point.</li>';
echo '<li><strong>John Wright, <em>The Trans-Saharan Slave Trade</em> (2007)</strong> — The most focused book-length treatment of the trade routes, organisation, and scale.</li>';
echo '<li><strong>Ronald Segal, <em>Islam\'s Black Slaves: The Other Black Diaspora</em> (2001)</strong> — Accessible account of the Arab slave trade and its legacy.</li>';
echo '<li><strong>Tidiane N\'Diaye, <em>Le génocide voilé</em> (2008)</strong> — Senegalese anthropologist on the Arab slave trade. Available in French.</li>';
echo '</ul>';
echo '<h3>Islam in West Africa</h3>';
echo '<ul>';
echo '<li><strong>Murray Last, <em>The Sokoto Caliphate</em> (1967)</strong> — The standard academic history of Usman dan Fodio\'s jihad. Essential for understanding northern Nigeria.</li>';
echo '<li><strong>Ousmane Kane, <em>Beyond Timbuktu: An Intellectual History of Muslim West Africa</em> (2016)</strong> — Recovery of the West African Islamic scholarly tradition.</li>';
echo '<li><strong>Nehemia Levtzion, <em>Ancient Ghana and Mali</em> (1973)</strong> — Islam\'s role in the Saharan empires.</li>';
echo '<li><strong>Ibn Battuta, <em>The Travels of Ibn Battuta</em> (tr. H.A.R. Gibb)</strong> — Primary source. Volume 4 covers the Mali Empire and West African Sudan.</li>';
echo '</ul>';
echo '<h3>Arab-African Relations</h3>';
echo '<ul>';
echo '<li><strong>Gamal Abdel Nasser, <em>The Philosophy of the Revolution</em> (1955)</strong> — Short primary source on Nasser\'s three-circle theory of Egyptian identity.</li>';
echo '<li><strong>Hakim Adi, <em>Pan-Africanism: A History</em> (2018)</strong> — Includes the Arab dimension of pan-African solidarity and its contradictions.</li>';
echo '<li><strong>Mahmood Mamdani, <em>Saviors and Survivors: Darfur, Politics, and the War on Terror</em> (2009)</strong> — On the Darfur conflict as an Arab-African war.</li>';
echo '<li><strong>Wole Soyinka, <em>You Must Set Forth at Dawn</em> (2006)</strong> — Memoir including reflections on Arab-African relations and anti-Blackness.</li>';
echo '</ul>';
echo '<h3>Contemporary Issues</h3>';
echo '<ul>';
echo '<li><strong>IOM, <em>Slavery in Libya</em> (2017)</strong> — Available at iom.int. Primary documentation of the Libya slave market situation.</li>';
echo '<li><strong>Human Rights Watch, Kafala reports (various years)</strong> — The Gulf kafala sponsorship system and its exploitation of African migrant workers.</li>';
echo '</ul>';
echo '<h3>Nigeria Specifically</h3>';
echo '<ul>';
echo '<li><strong>Karl Maier, <em>This House Has Fallen: Nigeria in Crisis</em> (2000)</strong> — The Hausa-Fulani/Igbo/Yoruba political triangle and its consequences.</li>';
echo '<li><strong>Elizabeth Isichei, <em>A History of the Igbo People</em> (1976)</strong> — Standard history including the northern Nigerian context and the Biafra War.</li>';
echo '</ul>';
echo '</div>';