<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Five Sites of Encounter</h2>';
echo '<h3>1. The Trans-Saharan Slave Trade: The Undiscussed Holocaust</h3>';
echo '<p>The trans-Saharan slave trade operated for twelve centuries and transported an estimated 17 million Africans into slavery — the longest-running forced migration in human history and, relative to its scale, the least discussed. Several factors account for this silence: the trade lacked the documentary infrastructure that makes the Atlantic trade recoverable; the societies that conducted it did not undergo abolitionist movements that forced public reckoning; and Arab solidarity with African anti-colonial movements created political incentives to avoid this history in inter-African discourse. A platform dedicated to African knowledge cannot document the Atlantic slave trade without equal rigour about the trans-Saharan trade.</p>';
echo '<h3>2. Islam in West Africa: Enrichment and Fault Line</h3>';
echo '<p>Islam\'s presence in West Africa is a story of genuine intellectual enrichment alongside genuine political conflict. The Islamic scholarly tradition of Timbuktu produced manuscripts of extraordinary sophistication — in mathematics, astronomy, jurisprudence, theology, and literature — that are only now being systematically recovered and digitised. The Sankore University at Timbuktu was at its height one of the major centres of Islamic learning in the world. At the same time, the Islamisation of the Sahel and savanna zones created the religious and political boundary that runs through Nigeria and has been the source of the most consequential conflicts in Nigerian history. Contemporary Boko Haram — having killed tens of thousands and displaced millions — is a direct product of this history.</p>';
echo '<h3>3. Arab Anti-Blackness: The Conversation Pan-Africanism Avoided</h3>';
echo '<p>Pan-African political ideology constructed a broad solidarity that included Arab North Africa. Nasser\'s Egypt supported African liberation movements; Arab states voted with sub-Saharan African states in international organisations. This solidarity had genuine substance. What pan-African solidarity frameworks were reluctant to name was the anti-Black racism embedded in Arab cultural and historical practice. The Arabic word <em>abid</em>, meaning slave, became a common term for Black Africans across much of the Arab world. The castration of enslaved African males — practised on a significant scale in the trans-Saharan trade — reflects a dehumanisation with no equivalent in the Atlantic trade. The 2017 CNN footage of a slave auction in Libya demonstrated that these structures had not entirely disappeared. Wole Soyinka, Chinweizu, and other African intellectuals have written about Arab anti-Blackness with a directness that official pan-African discourse has avoided.</p>';
echo '<h3>4. Gulf Arab Investment in Africa: Aid, Leverage, and Land</h3>';
echo '<p>Gulf Arab states have become significant investors in sub-Saharan Africa through sovereign wealth fund investment, agricultural land leasing (millions of hectares in Sudan, Ethiopia, and Tanzania), Islamic Development Bank lending, and mosque-building and Islamic education funding. African states want capital and infrastructure; Gulf states want food security, political allies, and soft power. The transactions are rational from both sides — but they reproduce structural relationships that echo the colonial period, with African resources and land exchanged for Gulf capital on terms set by the party with capital.</p>';
echo '<h3>5. The Nigerian Fault Line: Hausa-Fulani, Igbo, and the Arab Connection</h3>';
echo '<p>The most direct consequence of the Arab-African encounter for the Igbo is the political structure of Nigeria. The Sokoto Caliphate, established in 1808, organised northern Nigeria under Islamic governance. British indirect rule preserved these structures. Post-independence Nigeria inherited them. The result is a federal state in which the Hausa-Fulani Muslim north has dominated federal power for most of Nigeria\'s independent history. The Biafra War (1967–1970), in which between one and three million people died — predominantly Igbo — was the most violent expression of this fault line. The federal government prosecuted a war that included the deliberate blockade of food to Biafra. The structural conditions that produced the war have not been resolved.</p>';
echo '</div>';