<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>The Nigerian and Igbo Diaspora in Britain</h2>';

echo '<h3>I. Early Arrivals (1900-1960)</h3>';
echo '<p>The Nigerian presence in Britain begins with students. From the early 20th century, ambitious young Nigerians — the sons of clergymen, lawyers, traders, and chiefs who had prospered under colonial conditions — came to Britain to study law, medicine, and the humanities at universities that their parents\' colonial relationship with Britain had made accessible. Nnamdi Azikiwe, Herbert Macaulay, H.O. Davies, and dozens of others who would shape Nigerian nationalism spent formative years in Britain, experiencing simultaneously the intellectual resources of British universities and the racial condescension of British society.</p>';
echo '<p>This early presence was small and largely male, largely student, and largely urban — concentrated in London and in the university cities. It was shaped by the colonial framework: Nigerians came to Britain as subjects of the Crown, with rights that were formally equal to those of other British subjects but practically subordinated by race. The West African Students\' Union (WASU), founded in London in 1925, was the primary institutional expression of this early Nigerian presence — a political and social organisation that connected Nigerian students across institutions and provided a forum for anti-colonial thought.</p>';

echo '<h3>II. Post-Independence Migration (1960-1980)</h3>';
echo '<p>Nigerian independence in 1960 changed the character of Nigerian migration to Britain without immediately reducing it. Professional Nigerians — doctors, nurses, lawyers, academics, engineers — continued to come to Britain for training and work, in part because British professional qualifications carried prestige in newly independent Nigeria and in part because the Nigerian oil boom of the 1970s had not yet created sufficient domestic demand for professional services. The NHS recruited heavily in Nigeria in the 1960s and 1970s; Nigerian nurses and doctors became significant presences in British hospitals.</p>';
echo '<p>The Biafra War (1967-1970) produced the first significant refugee flow from Nigeria to Britain: Igbo people who had been in Britain during the war and could not safely return, and a smaller number who fled during or after the conflict. This community carried the trauma of the war and the particular bitterness of the British government\'s role in it — its supply of arms to the federal government, its diplomatic support for the blockade that starved Biafran children. The Biafran community in Britain became a centre of political advocacy and memory-keeping that has persisted across generations.</p>';

echo '<h3>III. The 1980s-2000s: Economic Migration and Community Formation</h3>';
echo '<p>The 1980s saw a significant shift in the character of Nigerian migration to Britain. Economic collapse in Nigeria — the oil price crash of 1981, the structural adjustment programmes imposed by the IMF, the successive military governments\' looting of public resources — drove a new wave of migration that was less elite, more economically diverse, and more permanent in its intentions than earlier waves. Communities formed in specific London boroughs: Peckham and New Cross became centres of the Yoruba and Niger Delta communities; Tottenham and Barking developed significant Igbo populations.</p>';
echo '<p>The 1990s Abacha dictatorship produced another wave: political activists, journalists, human rights lawyers, and others who fled the terror of the most brutal of Nigeria\'s military governments. This wave added political complexity to Nigerian British community life — bringing people with direct experience of political persecution and strong opinions about Nigerian governance into a community that had previously been more economically than politically defined.</p>';

echo '<h3>IV. The Second Generation and the Contemporary Moment</h3>';
echo '<p>The British-born or British-raised children of Nigerian migrants — the second generation — have produced some of the most significant cultural contributions to contemporary British life. Bernardine Evaristo, winner of the 2019 Booker Prize, was born in Woolwich to a Nigerian father and a British mother. David Oyelowo, the actor who played Martin Luther King in <em>Selma</em>, is of Nigerian Yoruba descent. Skepta, the grime artist who won the Mercury Prize in 2016, is of Yoruba descent. These figures are simultaneously British cultural icons and members of the Nigerian diaspora — a dual identity that British culture has been slow to acknowledge and that the second generation has had to negotiate without institutional support.</p>';
echo '<p>The second generation also navigates the hostile environment that successive British governments have created: stop-and-search rates that target Black people disproportionately, an immigration system that treats Nigerian British citizens as suspects rather than members of the community, and a national conversation about identity that has consistently struggled to accommodate Blackness and Britishness simultaneously.</p>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/europe/overview/">→ Europe</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/people/overview/">→ People</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/history/overview/">→ History</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/resistance/overview/">→ Resistance</a>';
echo '</div>';
echo '</div>';