<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Figures in the British-Nigerian Experience</h2>';
echo '<h3>Olaudah Equiano (c.1745-1797)</h3>';
echo '<p>Olaudah Equiano is the founding figure of the British-Nigerian relationship. Born in Igboland, enslaved as a child, transported across the Atlantic, sold multiple times, and eventually purchasing his own freedom, Equiano settled in London and became the most important Black voice in the British abolitionist movement. His autobiography (1789) went through nine editions in his lifetime. He lobbied Parliament, lectured across Britain, married a British woman (Susanna Cullen of Soham, Cambridgeshire), and organised the Black Poor of London. He died in London in 1797. He is simultaneously the ancestor of the British-Nigerian relationship, the founding figure of Igbo diaspora literature, and a reminder that the Nigerian presence in Britain began not with Windrush but with the Atlantic slave trade.</p>';
echo '<h3>Buchi Emecheta (1944-2017)</h3>';
echo '<p>Buchi Emecheta was the first Nigerian woman to achieve major literary recognition in Britain. Born in Lagos of Igbo heritage, she came to London in 1962, was abandoned with five young children, lived in poverty in North London, and wrote novels that documented the experience of African women in Britain with unflinching honesty. <em>Second Class Citizen</em> (1974) is the essential account of the Nigerian woman\'s experience in 1960s London: the racism, the poverty, the domestic violence, the social isolation, and the determination. She went on to write fourteen novels, including <em>The Joys of Motherhood</em> (1979). She was nominated for the Booker Prize twice. She is the most important literary figure in the British-Igbo tradition after Equiano.</p>';
echo '<h3>Ben Okri (b.1959)</h3>';
echo '<p>Ben Okri was born in Nigeria and has lived in Britain since the 1970s. His novel <em>The Famished Road</em> (1991) — a work of magical realism centred on a spirit child (<em>abiku</em>) navigating between the world of the living and the world of the dead in colonial and post-colonial Nigeria — won the Booker Prize and established him as one of the major figures of late 20th-century world literature. He is the first Nigerian to win the Booker Prize and a defining figure of the British-Nigerian literary tradition.</p>';
echo '<h3>Bernardine Evaristo (b.1959)</h3>';
echo '<p>Bernardine Evaristo was born in Woolwich, London, to a Nigerian father and a white British mother. Her 2019 novel <em>Girl, Woman, Other</em> — twelve interconnected characters, mostly Black British women, across generations and geographies — won the Booker Prize and transformed the conversation about who British literature is for and about. Her experimental form — no full stops, free verse prose — enacts the argument: that Black British lives do not fit the punctuation of the standard sentence. She is Chair of the Royal Society of Literature and the most significant Black British literary voice of her generation. She is Nigerian in ancestry and British in formation — a combination that British culture has been slow to hold simultaneously.</p>';
echo '<h3>David Oyelowo (b.1976)</h3>';
echo '<p>David Oyelowo is a British actor of Nigerian Yoruba descent who played Martin Luther King in <em>Selma</em> (2014), widely considered one of the finest performances in recent British-American cinema. Born in Oxford, raised in Lagos and London, he trained at LAMDA and RADA. His casting as MLK demonstrated both his ability and the persistent marginalisation of Black British talent in British film and television. He represents the second generation of British Nigerians who have achieved at the highest level in British cultural life while maintaining their Nigerian identity.</p>';
echo '</div>';