<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Key references for the British-Nigerian experience.</p>';
echo '<h2>Literature and Memoir</h2>';
echo '<ul>';
echo '<li><strong>Olaudah Equiano</strong> — <em>The Interesting Narrative</em> (1789). The foundational text.</li>';
echo '<li><strong>Buchi Emecheta</strong> — <em>Second Class Citizen</em> (1974). Nigerian woman\'s experience in London.</li>';
echo '<li><strong>Ben Okri</strong> — <em>The Famished Road</em> (1991). Booker Prize-winning Nigerian-British fiction.</li>';
echo '<li><strong>Chibundu Onuzo</strong> — <em>Welcome to Lagos</em> (2017) and <em>Sankofa</em> (2021). Contemporary British-Nigerian literary fiction.</li>';
echo '</ul>';
echo '<h2>Academic Studies</h2>';
echo '<ul>';
echo '<li><strong>Harry Goulbourne and Mary Chamberlain (eds.)</strong> — <em>Caribbean Families in Britain and the Trans-Atlantic World</em> (2001). Broader Caribbean and African diaspora context.</li>';
echo '<li><strong>Naomi Richman</strong> — <em>In Exile from the Self</em> (2002). Mental health and refugee experience in Britain.</li>';
echo '<li><strong>David Killingray (ed.)</strong> — <em>Africans in Britain</em> (1994). Historical survey.</li>';
echo '</ul>';
echo '<h2>On Race in Britain</h2>';
echo '<ul>';
echo '<li><strong>Reni Eddo-Lodge</strong> — <em>Why I\'m No Longer Talking to White People About Race</em> (2017). The most widely read contemporary British book on race.</li>';
echo '<li><strong>David Olusoga</strong> — <em>Black and British: A Forgotten History</em> (2016). Essential history of Black presence in Britain.</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/uk/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/uk/topics/">Topics</a>';
echo '</div></div>';
