<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>From the Compound to the Cosmos</h2>';

echo '<h3>I. The Compound as Cultural Centre</h3>';
echo '<p>Igbo cultural life begins in the compound — the <em>obi</em>, the central meeting space of the patrilineage. Here elders gather, titles are conferred, disputes are settled, and the dead are remembered. The compound is both physical space and social institution, organising kinship, authority, and memory across generations. The <em>obi</em> of the household head stands at the compound\'s centre; around it are arranged the dwellings of wives, sons, and dependants in an architecture that encodes social hierarchy in space.</p>';
echo '<p>The compound is also a cosmological centre. The threshold between the compound and the outside world — marked by the <em>ofo</em> staff of the lineage head — is the threshold between the domestic and the dangerous, between the ordered world of kinship and the unpredictable world beyond. Ancestral shrines within the compound maintain the connection between the living and the dead. The compound is where the most important rituals of birth, title-taking, marriage, and death are performed. It is the primary unit of Igbo cultural life, and understanding it is the key to understanding everything else.</p>';

echo '<h3>II. Time: The Four-Day Week and the Agricultural Cycle</h3>';
echo '<p>The Igbo calendar is organised around a four-day market week — Eke, Orie, Afo, Nkwo. Each day has its associated market, its ritual significance, and its place in the agricultural and ceremonial cycle. A child born on Eke is named Nwaeke. A man born on Afo carries that name. Time is not merely measured — it is named, embodied, and lived. The four-day week is simultaneously a commercial institution (market days), a ritual institution (certain activities forbidden on certain days), and an identity institution (naming practices).</p>';
echo '<p>The agricultural cycle overlays the weekly cycle with a seasonal one. The yam (<em>ji</em>) — the "king of crops" — structures the year. Planting begins with ritual preparation of the farm; the harvest is celebrated with the New Yam Festival (<em>Iwa Ji</em> or <em>Iri Ji</em>), one of the most important communal events in the Igbo calendar. The New Yam Festival is simultaneously a thanksgiving, a social display, and a renewal — the moment at which the community affirms its continuity with the land and with its ancestors.</p>';

echo '<h3>III. The Cosmological Framework</h3>';
echo '<p>Igbo cosmology provides the framework within which all cultural practices make sense. At its centre is <em>Chukwu</em> — the supreme being, the great spirit, the source of all existence. Chukwu is not directly approachable; one communicates with the divine through intermediaries: <em>alusi</em> (minor deities), ancestral spirits, and one\'s personal <em>chi</em>.</p>';
echo '<p>The <em>chi</em> — every person\'s personal spiritual double — is one of the most philosophically rich concepts in Igbo thought. It accompanies the person through life, influences their destiny, and can be propitiated through ritual. The relationship between a person and their <em>chi</em> is dialogic: "Onye kwe, chi ya ekwe" — if a person agrees, their chi agrees — suggests that human will and spiritual destiny are in conversation, not contradiction. Success reflects a good chi; failure may reflect a chi that needs propitiation. This is not fatalism — it is a sophisticated account of the relationship between individual agency and forces beyond individual control.</p>';
echo '<p><em>Ofo</em> and <em>ogu</em> — righteous authority and clean hands — form the ethical foundation of Igbo justice and leadership. The <em>ofo</em> stick, held by lineage heads and title holders, represents the authority of the ancestors and the obligation to act with integrity. "Onye nwere ofo na ogu" — he who has ofo and ogu — is he whose authority is legitimate because his conduct is clean.</p>';

echo '<h3>IV. Performance Culture: Masquerades and Music</h3>';
echo '<p>The <em>Mmanwu</em> tradition is the most visible and complex form of Igbo performative culture. Masquerades are understood as manifestations of ancestral spirits — the dead returning to the world of the living to enforce social norms, celebrate community events, or mark transitions. Each community has its own masquerade traditions, costumes, and protocols. <em>Mmanwu</em> can be comic or terrifying, healing or punishing, celebratory or judicial. The masquerade tradition is simultaneously a religious institution, an artistic tradition, a judicial mechanism, and a form of entertainment — categories that Igbo culture does not separate as sharply as Western culture does.</p>';
echo '<p>Igbo music traditions are equally rich. The <em>ogene</em> (metal gong), <em>ekwe</em> (slit drum), <em>udu</em> (clay pot drum), <em>oja</em> (flute), and <em>igba</em> (drum) form the core instrumental ensemble. Music accompanies every major social event. The highlife tradition, developed in the mid-20th century with significant Igbo input, became one of West Africa\'s most influential popular music forms. Contemporary Afrobeats — now dominating global popular music charts — has deep Igbo roots in its rhythmic structures, its celebration of communal festivity, and its irreverence toward established authority.</p>';

echo '<h3>V. Visual Culture: Uli, Mbari, and the Arts</h3>';
echo '<p>Igbo visual culture is as diverse as Igbo political culture — distributed, locally varied, and extraordinarily creative. <em>Uli</em> is the tradition of decorative line drawing practised by Igbo women, applied to the body for ceremonies and to the walls of houses and shrines. The designs are abstract and symbolic, drawn freehand with extraordinary skill. <em>Uli</em> was largely suppressed during the colonial period as "pagan" but has experienced significant revival as a recognised art form with influence on modern Nigerian painting and design. The artist Uche Okeke drew explicitly on <em>Uli</em> in developing what he called "Natural Synthesis" — an African modernism rooted in indigenous visual traditions.</p>';
echo '<p><em>Mbari</em> houses — elaborate mud sculptures created for the earth deity <em>Ala</em> — represent some of the most complex and culturally rich artistic productions in precolonial West Africa. Built by community teams under ritual direction, <em>mbari</em> houses depicted the full range of Igbo life: deities, animals, humans, Europeans, everyday activities, and sexual and violent scenes that transgressed normal social boundaries. The <em>mbari</em> was understood as a gift to <em>Ala</em>; once completed, it was left to decay, embodying the Igbo understanding that creation is cyclical rather than permanent.</p>';
echo '</div>';