<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Artists, Writers, Musicians, and Cultural Custodians</h2>';
echo '<h3>Chinua Achebe (1930-2013)</h3>';
echo '<p>Chinua Achebe is the most significant single contributor to the global understanding of Igbo culture. His four novels of the colonial and post-colonial period — <em>Things Fall Apart</em> (1958), <em>No Longer at Ease</em> (1960), <em>Arrow of God</em> (1964), and <em>A Man of the People</em> (1966) — constitute the richest literary documentation of Igbo cultural life in the 20th century. <em>Arrow of God</em> in particular — the story of the chief priest of Ulu in the village of Umuaro during the colonial period — is the most detailed and philosophically profound account of Igbo religious and political culture ever written. Achebe did not merely describe Igbo culture; he demonstrated its coherence, its moral depth, and its resilience in a form accessible to readers worldwide.</p>';
echo '<h3>Flora Nwapa (1931-1993)</h3>';
echo '<p>Flora Nwapa was the first African woman to be published by a major international publisher and the first African woman to establish her own publishing house. Born in Oguta, Rivers State, her novels <em>Efuru</em> (1966) and <em>Idu</em> (1970) centred Igbo women\'s lives — their relationships with the water goddess <em>Uhamiri</em>, their experiences of marriage and motherhood, their agency within the constraints of Igbo patrilineal culture — at a time when African literature was almost entirely dominated by male perspectives. She also founded Tana Press (1977), publishing Nigerian children\'s literature and adult fiction when Nigerian authors had almost no local publishing options. She is underacknowledged relative to her significance.</p>';
echo '<h3>Christopher Okigbo (1932-1967)</h3>';
echo '<p>Christopher Okigbo is the most celebrated Igbo poet of the 20th century and, by many assessments, the greatest African poet of his era. Born in Ojoto, Anambra State, his poetry — collected in <em>Labyrinths</em> (1971, posthumous) — draws simultaneously on Igbo cosmology (particularly the tradition of <em>Idoto</em>, the water goddess of his hometown), on classical literature, and on jazz. It is a poetry that refuses to be placed in a single tradition because it inhabits all of them at once. Okigbo enlisted in the Biafran army and was killed near Nsukka in August 1967, aged 35. His death is one of the great losses of the civil war for African literature.</p>';
echo '<h3>Chief Stephen Osita Osadebe (1936-2007)</h3>';
echo '<p>Chief Stephen Osita Osadebe — the "Sweet Maestro" — was one of the greatest Igbo highlife musicians of the 20th century and one of the most important archivists of Igbo oral culture in the medium of recorded sound. His music combined traditional Igbo rhythms, proverbs, and narratives with the highlife sound. His songs — many of them extended meditations on Igbo social values, community life, and moral philosophy — preserve in sonic form dimensions of Igbo oral culture that are not documented in any other medium. His recordings remain beloved across generations of Igbo people worldwide.</p>';
echo '<h3>Uche Okeke (1933-2016)</h3>';
echo '<p>Uche Okeke was the founder of the Zaria Art Society (1958) and one of the most important figures in the history of modern Nigerian art. As a student in Zaria, he developed "Natural Synthesis" — a theory of African modernism that argued for drawing on indigenous visual traditions rather than simply adopting European modern art styles. His own practice drew explicitly on <em>Uli</em> — the Igbo women\'s tradition of abstract line drawing — creating paintings simultaneously modern in technique and deeply rooted in Igbo visual culture. His work as an educator at the University of Nigeria Nsukka transformed Nigerian art education and produced several of the most significant contemporary Nigerian artists.</p>';
echo '<h3>Chimamanda Ngozi Adichie (b.1977)</h3>';
echo '<p>Chimamanda Ngozi Adichie is the most globally significant Igbo cultural figure of the 21st century. Her three novels and story collection have been translated into over 30 languages. Her TED talk "The Danger of a Single Story" makes the argument for cultural diversity in terms drawn directly from her Igbo and Nigerian experience. Her novel <em>Half of a Yellow Sun</em> is the most widely read account of the Biafra War in any language. She is the inheritor and extender of the Achebe tradition in the most precise sense: she grew up in Nsukka, in the house Achebe had previously occupied, and her work extends his project of making Igbo experience visible and legible to the world.</p>';
echo '</div>';