<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Key books, collections, and references for the study of Igbo culture.</p>';
echo '<h2>Essential Literary Sources</h2>';
echo '<ul>';
echo '<li><strong>Chinua Achebe</strong> — <em>Things Fall Apart</em> (1958). The richest literary portrait of precolonial and early colonial Igbo culture.</li>';
echo '<li><strong>Chinua Achebe</strong> — <em>Arrow of God</em> (1964). Focuses on Igbo religious and political culture during colonization.</li>';
echo '<li><strong>Flora Nwapa</strong> — <em>Efuru</em> (1966). Centres Igbo women\'s lives and the Uhamiri (lake goddess) tradition.</li>';
echo '<li><strong>Chimamanda Ngozi Adichie</strong> — <em>Purple Hibiscus</em> (2003). Contemporary Igbo family life and religious change.</li>';
echo '</ul>';
echo '<h2>Ethnographic and Anthropological Studies</h2>';
echo '<ul>';
echo '<li><strong>M.M. Green</strong> — <em>Igbo Village Affairs</em> (1947). One of the earliest and most detailed ethnographic studies of Igbo community life.</li>';
echo '<li><strong>Victor Uchendu</strong> — <em>The Igbo of Southeast Nigeria</em> (1965). Standard introductory anthropological account, written by an Igbo scholar.</li>';
echo '<li><strong>Phoebe Ottenberg</strong> — <em>Afikpo: The Resurgence of a Culture</em> (2005). Detailed study of Afikpo Igbo masquerade and cultural life.</li>';
echo '<li><strong>Simon Ottenberg</strong> — <em>Masked Rituals of Afikpo</em> (1975). The definitive study of Igbo masquerade tradition.</li>';
echo '</ul>';
echo '<h2>Art and Visual Culture</h2>';
echo '<ul>';
echo '<li><strong>Herbert Cole and Chike Aniakor</strong> — <em>Igbo Arts: Community and Cosmos</em> (1984). The most comprehensive survey of Igbo visual art.</li>';
echo '<li><strong>Chike Aniakor</strong> — various articles on Uli art and Igbo aesthetics.</li>';
echo '<li><strong>Uche Okeke</strong> — writings on Natural Synthesis and Igbo visual traditions.</li>';
echo '</ul>';
echo '<h2>Language and Oral Tradition</h2>';
echo '<ul>';
echo '<li><strong>Onuora Nzekwu</strong> — <em>Wand of Noble Wood</em> (1961). Early novel documenting Igbo customs and social life.</li>';
echo '<li><strong>Akachi Adimora-Ezeigbo</strong> — various works on Igbo women\'s oral literature.</li>';
echo '<li><strong>F.C. Ogbalu</strong> — <em>Ilu Igbo</em> (Igbo Proverbs). The standard collection of Igbo proverbs.</li>';
echo '</ul>';
echo '<h2>Music</h2>';
echo '<ul>';
echo '<li><strong>John Collins</strong> — works on West African highlife music and its Igbo roots.</li>';
echo '<li><strong>Meki Nzewi</strong> — writings on Igbo musical theory and practice.</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/culture/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/culture/overview/">Overview</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/culture/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/culture/people/">People</a>';
echo '</div></div>';
