<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Topics in Igbo Cultural Life</h2>';

echo '<h3>1. The Kola Nut: When Objects Carry Worlds</h3>';
echo '<p>The kola nut (<em>oji</em>) is the most important ritual object in Igbo culture. No significant gathering — a visit, a meeting, a ceremony, a negotiation — begins without the presentation and breaking of kola. The act of presenting kola is a blessing; the prayer over kola (<em>igo oji</em>) invokes the ancestors, the chi, and the forces of life. "Onye wetara oji wetara ndụ" — he who brings kola brings life. To refuse kola is a serious social offence. To be given the right to break kola is a mark of seniority and respect.</p>';
echo '<p>The kola nut prayer is one of the richest forms of Igbo oral poetry. It invokes the earth (<em>Ala</em>), the sky (<em>Igwe</em>), the ancestors, the chi of those present, and the specific purposes of the gathering. It is simultaneously a prayer, a greeting, a social contract, and a cosmological statement. Learning to pray over kola correctly is one of the marks of adult male competence in Igbo culture — and the prayer\'s content varies by community, by occasion, and by the eloquence of the person praying. There is no single correct kola prayer; there are as many as there are communities and occasions.</p>';

echo '<h3>2. Title Systems: How Igbo Society Rewards Achievement</h3>';
echo '<p>The Igbo title system is one of the most developed systems of achieved status in West Africa. Unlike hereditary aristocracies, Igbo titles must be earned — through wealth, community service, moral standing, and the performance of specific rituals. Titles such as <em>Ozo</em>, <em>Nze</em>, <em>Eze</em>, and <em>Ichie</em> carry specific rights, obligations, and symbols. Title-taking is a major life event requiring significant wealth, community support, and ritual preparation that can span weeks.</p>';
echo '<p>The title system is significant for what it reveals about Igbo values. Achievement, not birth, confers status. Wealth must be publicly demonstrated and shared — the title ceremony requires extensive feasting and gift-giving that redistributes wealth through the community. Moral standing matters: a man of bad character cannot take certain titles regardless of his wealth. The system rewards the combination of economic success, social generosity, and ethical conduct that Igbo culture identifies as the ideal of manhood. The <em>ichi</em> facial scarification, once associated with Nri and Onitsha aristocracy, marked the titled man as someone who had crossed a threshold into a different social category — permanently, visibly, irreversibly.</p>';

echo '<h3>3. Marriage and Kinship: The Architecture of Society</h3>';
echo '<p>Traditional Igbo marriage (<em>Igba Nkwu</em> — wine-carrying) is a community event, not merely a personal one. The bride carries palm wine to her husband in a public ceremony attended by both families and the wider community. Bride price (<em>ime ego</em>) is negotiated between families. Marriage connects lineages, not just individuals — the marriage creates obligations and alliances that extend far beyond the couple themselves.</p>';
echo '<p>Igbo kinship is organised through the <em>umunna</em> — the patrilineage group — and the <em>ụmụada</em> — the daughters of the lineage, who retain rights and authority in their natal community even after marriage. The <em>ụmụada</em> institution is particularly significant: daughters who marry out of the lineage maintain a permanent connection to it, return for major ceremonies, and exercise specific judicial and ritual authority within the lineage that their husbands\' lineages do not possess. The <em>ụmụada</em> are not simply visitors; they are a constitutive part of the lineage\'s authority structure.</p>';

echo '<h3>4. Death, Funerals, and the Ancestors</h3>';
echo '<p>Death in Igbo culture is not an ending but a transition. A good death — at old age, after a life well-lived, surrounded by children and grandchildren — is celebrated with elaborate funeral ceremonies that can last several days. Music, masquerades, feasting, and the firing of guns mark the passage. The body is washed, dressed in title regalia if the deceased held titles, and buried with objects appropriate to their status. Second burials (<em>ikwa ozu</em>) may be held weeks or months later for prominent figures, allowing the community time to prepare appropriate celebrations.</p>';
echo '<p>Dying young, dying without children, or dying in certain ways (by drowning, by lightning, in childbirth) is considered a bad death (<em>ọnwụ ojọọ</em>) and is treated differently — with less ceremony and sometimes with specific rituals to manage the spiritual danger such deaths are understood to carry. The ancestors — those who died well and are properly remembered — remain present in the life of the community. They are invoked at the kola nut prayer, propitiated at household shrines, and consulted through divination. The boundary between the living and the dead in Igbo culture is permeable and maintained through ritual attention on both sides.</p>';

echo '<h3>5. Nollywood and Contemporary Igbo Culture</h3>';
echo '<p>Nollywood — the Nigerian film industry that emerged in the early 1990s and is now the second largest film industry in the world by volume — is disproportionately Igbo in its creative workforce, its production centres (largely in Onitsha, Owerri, and Lagos), and its cultural content. The industry began with Igbo traders selling VHS cassettes in Onitsha market — a characteristically Igbo fusion of commerce and culture — and grew into a global phenomenon that reaches African audiences in every country on earth and diaspora communities from London to Houston.</p>';
echo '<p>Nollywood is significant culturally as well as economically. It has become one of the primary vehicles through which Igbo cultural knowledge — about family structures, traditional medicine, masquerade traditions, marriage customs, title systems, and supernatural beliefs — is transmitted to younger generations who may not speak fluent Igbo and may have grown up outside Igboland. It is simultaneously a commercial entertainment industry, a cultural preservation mechanism, and a source of significant distortion — the Nollywood representation of Igbo culture is selective, melodramatic, and often shaped by the demands of a pan-Nigerian market rather than by the priorities of Igbo cultural custodians. Both things are true.</p>';
echo '</div>';