<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Individual biographical portraits — Igbo and African figures examined in depth.</p>';
echo '<h2>Nwanyeruwa (fl. 1929)</h2>';
echo '<p>The woman whose confrontation with a census counter on 23 November 1929 triggered the Aba Women\'s War. When a man sent by warrant chief Okugo came to count Nwanyeruwa\'s goats and people — which she understood as preparation for new taxes — she refused, and the argument escalated. She sent palm fronds to neighboring villages, the traditional signal of women\'s assembly. Within days tens of thousands of women were mobilizing across the region. Nwanyeruwa is the immediate human cause of one of the most significant events in Nigerian colonial history.</p>';
echo '<h2>Aguiyi-Ironsi (1924-1966)</h2>';
echo '<p>Major-General Johnson Thomas Umunnakwe Aguiyi-Ironsi was the first military head of state of Nigeria, coming to power after the coup of January 1966. Born in Umuahia, he rose through the Nigerian army, serving with distinction in UN operations in the Congo. His Unification Decree of May 1966, which abolished Nigeria\'s federal structure in favor of a unitary state, was perceived by northern Nigerians as an Igbo power grab. He was killed in the counter-coup of July 1966. His death was the prelude to the pogroms and, eventually, to Biafra.</p>';
echo '<h2>Warrant Chief Okugo (fl. 1929)</h2>';
echo '<p>One of the warrant chiefs whose abuse of the system of indirect rule helped trigger the Aba Women\'s War of 1929. Appointed by the British without traditional authority, Okugo used his position to extort money and labor from women in his district. He was subsequently tried and imprisoned by the colonial administration. His case illustrates the structural problem of the warrant chief system and the specific dynamic that produced the 1929 uprising.</p>';
echo '<h2>Ezeulu — the Archetypal Priest</h2>';
echo '<p>Chinua Achebe\'s <em>Arrow of God</em> (1964) centers on Ezeulu, the chief priest of Ulu. Though fictional, Ezeulu is a biographical type: the Igbo ritual specialist whose world is destroyed by colonial contact. His confrontation with British colonial authority — and his catastrophic decision to refuse to announce the new yam festival on time — is one of the great fictional explorations of the collision between Igbo spiritual authority and colonial power. Achebe based the character on research into Igbo priestly traditions; Ezeulu is fictional but his world is accurately rendered.</p>';
echo '<h2>Omu Okwei (1872-1943)</h2>';
echo '<p>Born in Ossomari on the Niger, Okwei became the dominant long-distance trader in the Niger Delta in the early 20th century, commanding a commercial network that connected the interior to the coast and competed directly with European trading companies. She was recognized by both the Ossomari community and the British colonial administration as Omu — the title reserved for the most senior woman in the community. Her life is documented in Sylvia Leith-Ross\'s study <em>African Women</em> (1939).</p>';
echo '</div>';