<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>The Igbo Language: Structure, History, and Writing</h2>';

echo '<h3>I. Linguistic Classification and Relationship</h3>';
echo '<p>Igbo belongs to the Volta-Niger branch of the Niger-Congo language family — one of the world\'s largest and most geographically extensive language families, encompassing most of sub-Saharan Africa\'s languages. Within the Niger-Congo family, Igbo\'s closest relatives are the Igboid languages: Ekpeye, Oguta, Ika, Ukwuani, and Oshimili — languages that share common ancestry with Igbo but are not mutually intelligible with it. More distantly, Igbo is related to Yoruba, Edo, Itsekiri, and other Volta-Niger languages, sharing grammatical features (tonal systems, vowel harmony, serial verb constructions) without sharing vocabulary.</p>';
echo '<p>The internal diversity of Igbo is itself significant. There are hundreds of Igbo dialects — Owerri, Onitsha, Ngwa, Afikpo, Ika, Ekpeye, Oguta, Orlu, and many more — that differ from each other in phonology, vocabulary, and to some extent grammar. The Owerri dialect became the basis of Standard Igbo (the Önwu orthography was largely based on Owerri-Igbo phonology), a choice that has been contested by communities whose dialects differ significantly from Owerri. The tension between a necessary standard and the diversity of living dialects is one of the permanent challenges of Igbo language policy.</p>';

echo '<h3>II. Phonology: The Sound System</h3>';
echo '<p>Igbo\'s phonological system is significantly more complex than the Roman alphabet can capture. The language has two primary lexical tones — high (marked with acute accent: á) and low (unmarked or marked with grave: à) — plus a downstep that creates a third functional tone level. These tones are not ornamental; they carry distinct meaning. The same consonant-vowel sequence spoken at different pitches means different things: "aka" (hand) versus "àkà" (direction/side); "ọ bịara" (he/she came) versus "ọ bịarā" (has he/she come?). Tones carry grammatical information as well as lexical information — distinguishing statements from questions, complete from incomplete actions.</p>';
echo '<p>The vowel system includes eight vowels (a, e, i, o, u, ị, ọ, ụ) divided into two harmonic sets. Vowel harmony — the principle that vowels within a word must belong to the same harmonic set — is a fundamental feature of Igbo phonology. The consonant system includes sounds not found in European languages: the labial-velar stops gb and kp (produced simultaneously at two points of articulation), the labial-velar glide w, the labiodental fricative f, and the nasal resonants nw and ny. It also includes a range of nasalised variants of consonants that the current standard orthography represents inconsistently or not at all.</p>';

echo '<h3>III. The Writing Systems</h3>';
echo '<p>Igbo has been written in three distinct ways, each with different histories and different relationships to the spoken language.</p>';
echo '<p><strong>Nsịbịdị</strong> is the oldest Igbo visual communication system — a set of ideographic signs used by the Ékpè (Leopard Society) and in other ritual contexts among the Igbo and Ibibio peoples. Nsịbịdị is not a phonetic writing system; it encodes social, spiritual, and philosophical meanings through symbols rather than sounds. It predates European contact and represents a form of visual literacy that existed independently of any Roman-derived system. It is currently experiencing a revival as a cultural symbol, though its use as a practical writing system for everyday Igbo remains limited.</p>';
echo '<p><strong>Roman-derived orthographies</strong> began with missionary transcriptions in the 19th century — inconsistent, dialect-specific, and designed primarily for Bible translation rather than comprehensive language representation. The Önwu orthography of 1961, produced by a committee chaired by F.C. Ogbalu, brought partial standardisation. It uses 24 of the 26 Roman letters (dropping Q and X), adds four dotted vowels (ị, ọ, ụ, ṅ), and employs digraphs (gb, kp, nw, ny, gh, ch) for sounds not representable by single letters. It is the current standard for education and publishing in Igbo.</p>';
echo '<p><strong>Ndebe</strong> is an indigenous script created in 2009 by Lotanna Uchenna (known as Kamalu), designed from scratch to represent Igbo sounds without Roman derivation. Ndebe is an abugida — each symbol represents a consonant-vowel unit, with modifications for different vowels. It is designed to represent tones systematically and to capture sounds the Roman alphabet cannot. Its adoption remains a work in progress: it has generated significant interest in language revitalisation communities but has not yet achieved mainstream use in education or media.</p>';

echo '<h3>IV. The Phoneme Gap</h3>';
echo '<p>The central argument of this subject is that the current Igbo writing system — even with its digraphs and diacritics — captures only a fraction of the actual phoneme inventory of the spoken language. The 24-letter Önwu orthography, supplemented by digraphs, represents perhaps 30% of what Igbo actually says. The remaining 70% — the nasalised variants, the aspirated stops, the labialised consonants, the full range of tonal distinctions — are either unmarked, inconsistently marked, or conflated with other sounds in the current system.</p>';
echo '<p>The principle of H-nasalisation — that when H follows a consonant, it signals a nasalised variant of that consonant with a different meaning — is particularly significant. This principle is active in the spoken language but not systematically recognised in the standard orthography. The distinction between C (a simple consonant sound) and CH (its nasalised variant) is a case in point: in the current orthography, CH represents one sound, but the underlying phonological distinction between the simple and nasalised forms is not consistently captured. The full representation of Igbo phonology would require the systematic extension of this H-nasalisation principle across the consonant inventory — producing new digraphs (bw, kh, gh in their Igbo senses) and trigraphs (kwh, for example) that the current standard does not recognise.</p>';

echo '<h3>V. Language Endangerment and Revitalisation</h3>';
echo '<p>Igbo faces significant endangerment pressure. In urban Igbo households, children increasingly grow up speaking English as their primary language, with Igbo as a second language or not at all. The civil war disrupted intergenerational transmission in ways that have not been fully recovered. Mission education promoted English at the expense of Igbo for over a century. Today, revitalisation efforts — through schools, media, digital platforms, and diaspora communities — are attempting to reverse this trend. The adequacy of the writing system is not separate from the endangerment question: a language that cannot be fully written is a language that is harder to teach, harder to standardise, and harder to pass on across generations and geographies.</p>';
echo '</div>';