<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Linguists, Writers, and Language Activists</h2>';
echo '<h3>F.C. Ogbalu (1927-1980)</h3>';
echo '<p>Francis Chukwuemeka Ogbalu is the most important figure in the history of written Igbo. As chair of the committee that produced the Önwu orthography in 1961, he brought partial standardisation to a written Igbo that had previously been fragmented across dozens of inconsistent missionary and administrative systems. His <em>Ilu Igbo</em> (Igbo Proverbs) remains the standard proverb collection; his Igbo-English dictionary and Igbo grammar are foundational reference works. The Society for Promoting Igbo Language and Culture (SPILC), which he founded, has been the primary institutional vehicle for Igbo language standardisation and promotion for over half a century. His work was essential; its limitations — the constraints of the 24-letter Roman framework he worked within — are the constraints of his era, not of his ambition.</p>';
echo '<h3>Kay Williamson (1935-2005)</h3>';
echo '<p>Kay Williamson was a British linguist who spent most of her career at the University of Ibadan and the University of Port Harcourt studying Nigerian languages, with particular attention to Igbo and the Ijoid languages. Her Igbo-English dictionary (1972) and her work on Igbo tone rules remain the most rigorous scholarly contributions to Igbo linguistics from outside the Igbo-speaking community. Her comparative work on Niger-Congo languages placed Igbo within its proper linguistic context and her documentation of Igbo phonology — particularly the tonal system — provided the scholarly foundation for subsequent work. She learned to speak Igbo fluently, an unusual achievement among foreign linguists working on the language.</p>';
echo '<h3>E.N. Emenanjo (contemporary)</h3>';
echo '<p>Emmanuel Nolue Emenanjo is the leading contemporary Igbo linguist. His work on Igbo syntax, verbal morphology, and language policy spans four decades. His <em>Auxiliaries in Igbo Syntax</em> (1985) is the most rigorous formal analysis of a key aspect of Igbo grammar. As a language policy advocate, he has consistently argued for a more comprehensive approach to Igbo orthography — one that goes beyond the Önwu framework to capture the full phonological richness of the language.</p>';
echo '<h3>Kamalu Uchenna (Lotanna Uchenna, contemporary)</h3>';
echo '<p>Kamalu Uchenna is the creator of Ndebe, the indigenous Igbo script developed in 2009. Born in the Igbo diaspora, his decision to create an entirely new writing system for Igbo — rather than working within the Roman framework — represents a fundamental challenge to the assumptions of the Önwu tradition. Ndebe is designed from the ground up to represent Igbo phonology adequately: it is an abugida that represents tones systematically and includes symbols for sounds the Roman alphabet cannot capture. The script has generated significant interest in language revitalisation communities worldwide and has inspired a new generation of Igbo speakers to think about what it would mean to write their language on its own terms.</p>';
echo '<h3>University of Nigeria Nsukka — Igbo Studies</h3>';
echo '<p>The University of Nigeria Nsukka (UNN) is the institutional centre of Igbo linguistic and literary scholarship. Its Igbo Studies department has produced generations of linguists, literature scholars, and language educators. Its dictionary projects, oral literature archives, and language teaching programmes are the most important institutional resources for Igbo language study in the world. The Nsukka intellectual tradition represents the most sustained institutional commitment to Igbo cultural and linguistic knowledge of any university.</p>';
echo '</div>';