<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Key references for the study of the Igbo language.</p>';
echo '<h2>Dictionaries and Reference Works</h2>';
echo '<ul>';
echo '<li><strong>F.C. Ogbalu</strong> — <em>Igbo-English Dictionary</em>. The standard bilingual dictionary.</li>';
echo '<li><strong>Kay Williamson</strong> — <em>Igbo-English Dictionary</em> (1972). Scholarly linguistic dictionary.</li>';
echo '<li><strong>F.C. Ogbalu</strong> — <em>Ilu Igbo</em> (Igbo Proverbs). The standard proverb collection.</li>';
echo '<li><strong>Emenanjo, E. N.</strong> — <em>Auxiliaries in Igbo Syntax</em> (1985). Important grammatical study.</li>';
echo '</ul>';
echo '<h2>Grammars and Linguistic Studies</h2>';
echo '<ul>';
echo '<li><strong>Kay Williamson</strong> — <em>Igbo Tone Rules</em>. The foundational study of Igbo tonology.</li>';
echo '<li><strong>Ọmọniyị Ọladẹlẹ</strong> — works on Niger-Congo language classification.</li>';
echo '<li><strong>Larry Hyman</strong> — comparative studies of Niger-Congo tone systems.</li>';
echo '</ul>';
echo '<h2>Orthography and Script</h2>';
echo '<ul>';
echo '<li><strong>Society for Promoting Igbo Language and Culture (SPILC)</strong> — publications on Igbo orthography and standardization.</li>';
echo '<li><strong>Önwu Orthography Committee Report</strong> (1961). The foundational document of standard written Igbo.</li>';
echo '<li>Documentation on Ndebe script — available at ndebe.org</li>';
echo '</ul>';
echo '<h2>Language and Literature</h2>';
echo '<ul>';
echo '<li><strong>Chinua Achebe</strong> — "The African Writer and the English Language" (1964). Essential essay on language and African writing.</li>';
echo '<li><strong>Ngugi wa Thiong\'o</strong> — <em>Decolonising the Mind</em> (1986). On the politics of language in African literature.</li>';
echo '<li><strong>Obiechina, Emmanuel</strong> — <em>Language and Theme: Essays on African Literature</em> (1990).</li>';
echo '</ul>';
echo '<h2>Learning Resources</h2>';
echo '<ul>';
echo '<li>Igbo Wikibooks — community-built Igbo language learning resource</li>';
echo '<li>Ikoikoigbo.com — online Igbo dictionary and learning platform</li>';
echo '<li>Igbo language courses — University of Nigeria Nsukka distance learning</li>';
echo '</ul>';
echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language1/intro/">Introduction</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language1/topics/">Topics</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/language1/people/">People</a>';
echo '</div></div>';
