<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<h2>Key Topics in Igbo Language and Writing</h2>';

echo '<h3>1. The Phoneme Gap: What the Roman Alphabet Cannot Say</h3>';
echo '<p>The fundamental problem of written Igbo is that the Roman alphabet — a system designed for Latin and its European descendants — cannot adequately represent the sounds of a language as phonologically rich as Igbo. The Önwu orthography of 1961 improved on earlier missionary systems by adding dotted vowels and digraphs, but it remains constrained by the 26-letter Roman framework (of which Igbo uses 24, dropping Q and X). The full phoneme inventory of Igbo — including all its tonal distinctions, nasalised consonant variants, labialised stops, and aspirated forms — cannot be adequately represented within this framework. Current estimates suggest that the Önwu system captures approximately 30% of Igbo\'s actual phoneme inventory. A fully adequate Igbo alphabet would require more than 70 distinct letters or letter combinations.</p>';
echo '<p>This is not merely a technical problem. A writing system that cannot represent a language\'s sounds is a writing system that distorts and diminishes the language it purports to encode. When Igbo children learn to read and write using the Önwu orthography, they learn a partial and imprecise representation of their language — one that makes the written form systematically different from the spoken form in ways that impede fluency and undermine the prestige of the written language.</p>';

echo '<h3>2. The H-Nasalisation Principle</h3>';
echo '<p>One of the most important and under-recognised features of Igbo phonology is the systematic nasalisation of consonants — the production of a consonant sound with nasal resonance that distinguishes it from its non-nasalised counterpart and carries a different meaning. In spoken Igbo, this distinction is clear to native speakers. In the current written orthography, it is largely unrepresented.</p>';
echo '<p>The principle that H following a consonant signals nasalisation — what we may call the H-nasalisation principle — is the key to representing these distinctions in Roman script. When H appears after a consonant, it should consistently indicate the nasalised variant of that consonant. This principle is partially active in the current orthography (CH already represents a distinct sound from C), but it is not systematically applied across the consonant inventory.</p>';
echo '<p>The C/CH distinction illustrates this: in a fully adequate Igbo orthography, C would represent a simple consonant sound, while CH would represent its nasalised variant. Currently, however, the letter C does not appear in the Önwu orthography at all — CH is used for a sound that would be better written simply as C, while the nasalised form that should be written CH is not systematically distinguished. The word for "pursue" or "chase" could be written <em>cou</em>, while the word for "sacrifice" — its nasalised phonological relative with a different meaning — would be written <em>chou</em>.</p>';

echo '<h3>3. Digraphs and Trigraphs: Beyond the Current Standard</h3>';
echo '<p>The Önwu orthography already employs digraphs — two-letter combinations representing single sounds: GB (as in <em>ụgbọ</em>, vehicle), KP (as in <em>akpị</em>, small), NW (as in <em>nwoke</em>, man), NY (as in <em>nyịnyị</em>, horse), GH, and CH. These digraphs were a necessary recognition that some Igbo sounds require more than one Roman letter to represent.</p>';
echo '<p>The argument developed here is that the standard also requires trigraphs — three-letter combinations representing single sounds — to capture phonological distinctions that digraphs alone cannot represent. The distinction between KW and KWH illustrates this: <em>kwuo</em> means "speak" (a simple labialised stop), while <em>kwhuo ikwhu</em> means "to curse" — a nasalised labialised form that requires the trigraph KWH to distinguish it from the non-nasalised KW. Other consonants require similar extension: BW, for example, would represent a labialised form of B that is distinct from both B and BH.</p>';
echo '<p><em>Note: The full systematic analysis of Igbo digraphs and trigraphs — covering the complete consonant inventory and its nasalised, labialised, and aspirated variants — is an active area of scholarly work being developed specifically for this platform. This section will be expanded significantly as that work progresses.</em></p>';

echo '<h3>4. Nsịbịdị: The Pre-Colonial Visual Tradition</h3>';
echo '<p>Nsịbịdị is a system of ideographic signs developed among the Igbo and Ibibio peoples of southeastern Nigeria, used primarily by the Ékpè (Leopard Society) and in other ritual and social contexts. Nsịbịdị signs encode social information — status, relationships, agreements, prohibitions — through symbols rather than phonetic representation. They are not a writing system in the phonetic sense; they do not represent sounds. They are a visual language that encodes meaning directly.</p>';
echo '<p>Nsịbịdị predates European contact and represents a form of Igbo literacy that existed independently of any Roman-derived system. Its full extent — the number of signs, their range of meanings, the contexts of their use — has never been comprehensively documented, in part because the knowledge was restricted to initiates of the Ékpè society. Contemporary scholars and artists are working to document and revive Nsịbịdị as a cultural symbol and as a resource for thinking about non-Roman approaches to representing Igbo meaning.</p>';

echo '<h3>5. Ndebe: The Contemporary Indigenous Script</h3>';
echo '<p>Ndebe is an indigenous Igbo script created in 2009 by Lotanna Uchenna (Kamalu), designed from the ground up to represent Igbo sounds without dependence on the Roman alphabet. It is an abugida — a writing system in which each symbol represents a consonant-vowel unit, with modifications indicating different vowels. Ndebe is designed to represent tones systematically and to capture phonological distinctions that the Roman alphabet cannot.</p>';
echo '<p>Ndebe\'s creation represents the most ambitious modern attempt to solve the phoneme gap through a fundamentally new approach rather than through incremental modification of the Roman system. Its adoption faces significant practical challenges: the investment in Roman-based Igbo literacy already made by education systems, publishers, and learners; the need for digital support (fonts, keyboards, input methods); and the absence of a strong institutional champion. However, it has generated genuine enthusiasm in language revitalisation communities and has inspired a new generation of Igbo speakers to think about writing their language on its own terms.</p>';
echo '</div>';