<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">The Abrahamic religions in depth — Judaism, Christianity, and Islam with all major branches, founders, beliefs, doctrines, and practices.</p>';

// JUDAISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2b6cb0;">⊕ Judaism</h2>';
echo '<p><strong>Founded:</strong> c. 1800 BCE (Abraham) / c. 1300 BCE (Moses/Sinai covenant) | <strong>Origin:</strong> Canaan / Levant | <strong>Followers:</strong> ~15 million | <strong>Status:</strong> Living</p>';
echo '<h3>Origin and Founders</h3>';
echo '<p>Judaism is the oldest Abrahamic religion and the source from which Christianity and Islam emerged. Its origins trace to Abraham (Ibrahim) — a Mesopotamian patriarch called by God to leave Ur and travel to Canaan, making a covenant (brit) that his descendants would be God\'s chosen people and inherit the land of Canaan. The decisive formative event was the Exodus — the liberation of the Israelites from Egyptian slavery under Moses (c. 1300 BCE) and the receiving of the Torah at Mount Sinai. This covenant at Sinai — God\'s law given to Israel, Israel\'s commitment to obey it — is the foundation of Judaism.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Monotheism</strong> — "Shema Yisrael: Adonai Eloheinu, Adonai Echad" — Hear O Israel: the Lord our God, the Lord is One. The declaration of God\'s absolute unity is the central statement of Jewish faith.</li>';
echo '<li><strong>The Covenant (Brit)</strong> — the binding agreement between God and the Jewish people. God will protect and bless Israel; Israel will obey God\'s commandments (mitzvot).</li>';
echo '<li><strong>Torah</strong> — the divine instruction given to Moses at Sinai. In its narrow sense: the Five Books of Moses. In its broad sense: the entire body of Jewish law and teaching, written and oral.</li>';
echo '<li><strong>613 Commandments (Mitzvot)</strong> — the laws of the Torah governing every aspect of life: ritual, ethical, dietary, agricultural, judicial. Jewish practice is fundamentally about observing these commandments.</li>';
echo '<li><strong>Tikkun Olam</strong> — "repair of the world." The Jewish obligation to act for justice, charity, and the improvement of human society.</li>';
echo '<li><strong>The Messianic Age</strong> — a future time of universal peace, justice, and knowledge of God, to be ushered in by the Messiah (a human leader, not a divine figure in mainstream Judaism).</li>';
echo '<li><strong>The World to Come (Olam Ha-Ba)</strong> — Jewish afterlife beliefs are diverse; the focus has historically been on this world and communal life rather than individual salvation.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Torah</strong> — Five Books of Moses (Genesis, Exodus, Leviticus, Numbers, Deuteronomy). The most sacred text.</li>';
echo '<li><strong>The Tanakh</strong> — the Hebrew Bible: Torah (Law), Nevi\'im (Prophets), Ketuvim (Writings). What Christians call the "Old Testament."</li>';
echo '<li><strong>The Talmud</strong> — the central text of Rabbinic Judaism. Contains the Mishnah (oral law codified c. 200 CE) and the Gemara (rabbinic discussion). The Babylonian Talmud (c. 500 CE) is the authoritative version.</li>';
echo '<li><strong>The Midrash</strong> — rabbinic interpretation and homiletical stories expanding on biblical texts.</li>';
echo '<li><strong>The Zohar</strong> — the central text of Kabbalah (Jewish mysticism), attributed to Rabbi Shimon bar Yochai (2nd century CE) but likely compiled in 13th century Spain.</li>';
echo '</ul>';
echo '<h3>Major Branches</h3>';
echo '<ul>';
echo '<li><strong>Orthodox Judaism</strong> — adherence to traditional halacha (Jewish law); the Torah was divinely given and cannot be changed. Largest single denominational grouping.</li>';
echo '<li><strong>Ultra-Orthodox (Haredi) Judaism</strong> — the most strictly observant; often living in insular communities; men typically devote their lives to Torah study.</li>';
echo '<li><strong>Conservative (Masorti) Judaism</strong> — traditional practice with some adaptation to modernity; accepts critical scholarship on the Torah while maintaining halachic observance.</li>';
echo '<li><strong>Reform (Liberal/Progressive) Judaism</strong> — founded in 19th century Germany; emphasizes ethical principles over ritual law; most adaptable to modern life; largest movement in the USA.</li>';
echo '<li><strong>Reconstructionist Judaism</strong> — views Judaism as an evolving civilization; founded by Mordecai Kaplan in the 1920s.</li>';
echo '<li><strong>Hasidic Judaism</strong> — mystical movement founded in 18th century Ukraine by the Baal Shem Tov; emphasizes joy, prayer, and the presence of God in all things; organized around charismatic rebbes (masters).</li>';
echo '<li><strong>Sephardic Judaism</strong> — traditions of Jews expelled from Spain in 1492; dominant in the Middle East, North Africa, and parts of Europe.</li>';
echo '<li><strong>Ashkenazi Judaism</strong> — traditions of Jews from Central and Eastern Europe.</li>';
echo '<li><strong>Mizrahi Judaism</strong> — traditions of Jews from the Middle East and North Africa.</li>';
echo '<li><strong>Ethiopian Judaism (Beta Israel)</strong> — ancient Jewish community of Ethiopia; practiced Judaism without the Talmud for centuries.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Shabbat</strong> — the Sabbath: from Friday sunset to Saturday night; no work; prayer, study, family, and rest.</li>';
echo '<li><strong>Kashrut</strong> — dietary laws: no pork, no shellfish, no mixing of meat and dairy; animals must be slaughtered in a specific way (shechita).</li>';
echo '<li><strong>Prayer (Tefillah)</strong> — three daily prayer services: Shacharit (morning), Mincha (afternoon), Ma\'ariv (evening).</li>';
echo '<li><strong>Synagogue</strong> — the Jewish house of worship and community center.</li>';
echo '<li><strong>Life Cycle Rites</strong> — Brit Milah (circumcision, 8th day), Bar/Bat Mitzvah (coming of age, 13/12 years), marriage, and burial.</li>';
echo '<li><strong>High Holy Days</strong> — Rosh Hashanah (New Year) and Yom Kippur (Day of Atonement) — the most solemn days of the Jewish year.</li>';
echo '<li><strong>Passover (Pesach)</strong> — commemorating the Exodus; the Seder meal retells the liberation story.</li>';
echo '</ul>';

// CHRISTIANITY
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Christianity</h2>';
echo '<p><strong>Founded:</strong> c. 30 CE | <strong>Founder:</strong> Jesus of Nazareth | <strong>Origin:</strong> Roman Palestine | <strong>Followers:</strong> ~2.4 billion | <strong>Status:</strong> Living — world\'s largest religion</p>';
echo '<h3>The Founder</h3>';
echo '<p>Jesus of Nazareth (c. 4 BCE – c. 30 CE) was a Jewish teacher and preacher from Galilee. According to Christian belief, he was the Son of God — the second person of the Trinity — born of a virgin (Mary), lived a sinless life, was crucified under Pontius Pilate, rose from the dead on the third day, and ascended to heaven. His life, death, and resurrection are understood to have atoned for human sin and opened the possibility of eternal life for all who believe.</p>';
echo '<p>Historically, Jesus was a real figure who preached a message of the Kingdom of God, the love of God and neighbor, and care for the poor. He gathered disciples, attracted large crowds, and was executed by crucifixion — a Roman method reserved for rebels and criminals — around 30 CE. The movement that grew from his followers became Christianity.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>The Trinity</strong> — God is three persons in one being: Father, Son (Jesus Christ), and Holy Spirit. This doctrine was formalized at the Council of Nicaea (325 CE).</li>';
echo '<li><strong>The Incarnation</strong> — God became human in Jesus Christ: fully divine and fully human simultaneously.</li>';
echo '<li><strong>Salvation</strong> — humanity is separated from God by sin; Jesus\'s death on the cross atones for sin; faith in Jesus (and in various traditions, also good works and sacraments) restores the relationship with God.</li>';
echo '<li><strong>Resurrection</strong> — Jesus rose bodily from the dead; this is the central claim of Christianity. "If Christ has not been raised, your faith is futile" (1 Corinthians 15:17).</li>';
echo '<li><strong>The Bible</strong> — the inspired word of God; contains the Old Testament (Jewish scriptures) and New Testament (apostolic writings).</li>';
echo '<li><strong>Heaven and Hell</strong> — eternal destinations after death; those who accept salvation go to heaven; those who reject it face eternal separation from God (hell).</li>';
echo '<li><strong>The Second Coming</strong> — Jesus will return at the end of history to judge the living and the dead and establish God\'s kingdom fully.</li>';
echo '</ul>';
echo '<h3>Sacred Text</h3>';
echo '<p><strong>The Bible</strong> — 66 books (Protestant) or 73 (Catholic) or more (Orthodox). Divided into Old Testament and New Testament. The New Testament contains four Gospels (Matthew, Mark, Luke, John), Acts of the Apostles, letters (Epistles) of Paul and others, and the Book of Revelation.</p>';
echo '<h3>Major Branches</h3>';
echo '<ul>';
echo '<li><strong>Roman Catholicism</strong> (~1.3 billion) — led by the Pope (Bishop of Rome); holds that the Church is the necessary means of salvation; 7 sacraments; venerates Mary and the saints; believes in purgatory.</li>';
echo '<li><strong>Eastern Orthodoxy</strong> (~220 million) — split from Rome in 1054 CE; 15 autocephalous churches (Greek, Russian, Serbian, Romanian, etc.); emphasizes theosis (divinization); liturgy in the vernacular; married parish priests.</li>';
echo '<li><strong>Protestantism</strong> (~900 million) — emerged from the Reformation (Luther 1517, Calvin 1536); rejects papal authority; "Scripture alone, faith alone, grace alone"; no purgatory; includes Lutheranism, Calvinism/Reformed, Anglicanism, Methodism, Baptism, Presbyterianism.</li>';
echo '<li><strong>Pentecostalism / Charismatic</strong> (~700 million) — emphasizes direct experience of the Holy Spirit; speaking in tongues; healing; prophecy; fastest-growing branch globally.</li>';
echo '<li><strong>Anglicanism</strong> (~85 million) — Church of England and worldwide Communion; created by Henry VIII\'s break with Rome (1534); theologically between Catholicism and Protestantism.</li>';
echo '<li><strong>Mormonism (LDS)</strong> (~17 million) — founded by Joseph Smith (1830); additional scripture (Book of Mormon); not considered Christian by many mainline denominations.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Sunday worship</strong> — the primary weekly gathering for prayer, scripture reading, preaching, and sacraments</li>';
echo '<li><strong>Baptism</strong> — initiation into the Christian community through water; infant or adult depending on tradition</li>';
echo '<li><strong>Eucharist / Communion / Lord\'s Supper</strong> — sharing bread and wine in memory of Jesus\'s last supper; understood as actual body and blood (Catholic), spiritual presence (Lutheran), or memorial (Baptist)</li>';
echo '<li><strong>Prayer</strong> — direct communication with God; the Lord\'s Prayer as the model</li>';
echo '<li><strong>Christmas</strong> — celebrating Jesus\'s birth (December 25 in Western Christianity)</li>';
echo '<li><strong>Easter</strong> — celebrating Jesus\'s resurrection; the central feast of the Christian year</li>';
echo '</ul>';

// ISLAM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Islam</h2>';
echo '<p><strong>Founded:</strong> 610 CE | <strong>Founder:</strong> Muhammad ibn Abdullah | <strong>Origin:</strong> Mecca, Arabia | <strong>Followers:</strong> ~1.9 billion | <strong>Status:</strong> Living — world\'s second largest religion</p>';
echo '<h3>The Founder</h3>';
echo '<p>Muhammad ibn Abdullah (570–632 CE) was born in Mecca, Arabia, into the Quraysh tribe. Orphaned young, raised by his uncle Abu Talib, he became a successful merchant known for his honesty (al-Amin — the trustworthy). At age 40, while meditating in the Cave of Hira on Mount Nur, he received the first revelation from God through the angel Jibril (Gabriel): "Iqra!" — "Read/Recite!" These revelations continued for 23 years and were compiled after his death as the Quran.</p>';
echo '<p>Muhammad began preaching monotheism in polytheistic Mecca, faced persecution, and migrated to Medina in 622 CE (the Hijra — the starting point of the Islamic calendar). From Medina he built a community and state, and by 630 CE had unified most of Arabia under Islam. He died in 632 CE, having never designated a clear successor — creating the division between Sunni and Shia that endures today.</p>';
echo '<h3>Core Beliefs — The Six Articles of Faith (Arkan al-Iman)</h3>';
echo '<ul>';
echo '<li><strong>Tawhid</strong> — the absolute oneness and uniqueness of God (Allah). "La ilaha illa Allah" — There is no god but God. The most fundamental Islamic statement.</li>';
echo '<li><strong>Angels (Mala\'ika)</strong> — created from light; they worship God and carry out divine commands; Jibril delivered revelation to Muhammad.</li>';
echo '<li><strong>Scriptures (Kutub)</strong> — God revealed scriptures to previous prophets: Torah (Musa/Moses), Psalms (Dawud/David), Gospel (Isa/Jesus); these were distorted by humans; the Quran is God\'s final, uncorrupted revelation.</li>';
echo '<li><strong>Prophets (Anbiya/Rusul)</strong> — God sent 124,000 prophets to humanity; 25 are named in the Quran including Adam, Ibrahim, Musa, Isa, and Muhammad — the Seal of the Prophets (final prophet).</li>';
echo '<li><strong>Day of Judgment (Yawm al-Qiyama)</strong> — all humans will be resurrected and judged; deeds weighed on scales; the righteous enter Paradise (Janna); the wicked face Hell (Jahannam).</li>';
echo '<li><strong>Divine Decree (Qadar)</strong> — God has knowledge of all things; everything occurs by God\'s will. Human free will and divine decree exist in tension in Islamic theology.</li>';
echo '</ul>';
echo '<h3>The Five Pillars of Islam (Arkan al-Islam)</h3>';
echo '<ul>';
echo '<li><strong>Shahada</strong> — Declaration of faith: "La ilaha illa Allah, Muhammadun rasul Allah" — There is no god but God, and Muhammad is His messenger.</li>';
echo '<li><strong>Salat</strong> — Five daily prayers: Fajr (dawn), Dhuhr (midday), Asr (afternoon), Maghrib (sunset), Isha (night). Performed facing Mecca.</li>';
echo '<li><strong>Zakat</strong> — Obligatory almsgiving: 2.5% of savings above a minimum threshold (nisab) given annually to the poor.</li>';
echo '<li><strong>Sawm</strong> — Fasting during Ramadan: complete abstention from food, drink, and sexual activity from dawn to sunset for the entire lunar month of Ramadan.</li>';
echo '<li><strong>Hajj</strong> — Pilgrimage to Mecca: obligatory once in a lifetime for those physically and financially able; performed in the Islamic month of Dhul Hijja.</li>';
echo '</ul>';
echo '<h3>Sacred Text</h3>';
echo '<p><strong>The Quran</strong> — "The Recitation." 114 surahs (chapters), 6,236 verses. Believed to be the literal word of God (Allah), revealed to Muhammad in Arabic through the angel Jibril. The Quran in Arabic is considered inimitable — no translation is considered equivalent to the original. The <strong>Hadith</strong> — collections of Muhammad\'s sayings and actions — are the second most important source of Islamic law and guidance.</p>';
echo '<h3>Major Branches</h3>';
echo '<ul>';
echo '<li><strong>Sunni Islam</strong> (~85-90% of Muslims) — "people of the Sunnah and the community." Accept the first four caliphs (Abu Bakr, Umar, Uthman, Ali) as legitimate. Four major legal schools: Hanafi, Maliki, Shafi\'i, Hanbali.</li>';
echo '<li><strong>Shia Islam</strong> (~10-15%) — "party of Ali." Believe the Prophet\'s leadership should have passed directly to Ali ibn Abi Talib (his cousin and son-in-law) and then to the Imams of his lineage. The martyrdom of Hussain ibn Ali at Karbala (680 CE) is the central tragedy of Shia history. Major branches: Ithna Ashari (Twelvers, dominant in Iran, Iraq, Lebanon), Ismaili (Seveners), Zaidi (Fivers).</li>';
echo '<li><strong>Sufism (Tasawwuf)</strong> — Islamic mysticism; the inner, spiritual dimension of Islam; seeking direct experience of God through dhikr (remembrance), music, poetry, and spiritual practice. Major orders include the Qadiriyya, Naqshbandiyya, Chishtiyya, Tijaniyya. Rumi is the most famous Sufi poet.</li>';
echo '<li><strong>Salafi / Wahhabi</strong> — 18th-century reform movement (Muhammad ibn Abd al-Wahhab); rejection of innovation (bid\'a); strict literalism; dominant in Saudi Arabia.</li>';
echo '<li><strong>Ahmadiyya</strong> — founded in 1889 by Mirza Ghulam Ahmad who claimed prophethood; considered heretical by mainstream Islam; persecuted in Pakistan.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Mosque (Masjid)</strong> — house of worship; Friday prayer (Jumu\'ah) is obligatory for men</li>';
echo '<li><strong>Halal</strong> — permitted food: no pork, no alcohol, animals must be slaughtered in God\'s name</li>';
echo '<li><strong>Islamic calendar</strong> — lunar calendar; Eid al-Fitr (end of Ramadan) and Eid al-Adha (feast of sacrifice, during Hajj) are the two major festivals</li>';
echo '<li><strong>Adhan</strong> — the call to prayer, sung from minarets five times daily</li>';
echo '<li><strong>Wudu</strong> — ritual purification before prayer</li>';
echo '</ul>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">Full Map</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/topics/">Ancient Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/eastern/">Eastern Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/african/">African Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/modern/">Modern Religions</a>';
echo '</div></div>';
