<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Doctrines, dogma, faith, proselytism, apostasy, and life-cycle traditions across world religions — a comparative thesis.</p>';

echo '<h2>Key Definitions</h2>';
echo '<ul>';
echo '<li><strong>Belief</strong> — what adherents hold to be true about God, the cosmos, and the human condition; the propositional content of religious conviction.</li>';
echo '<li><strong>Faith</strong> — the mode of holding religious belief; distinct from mere intellectual assent. In Christianity, faith (pistis) involves trust and commitment, not just acknowledgment. In Islam, iman (faith) has six articles. In Judaism, emunah is trust in God\'s reliability. In Buddhism, saddha is confidence in the Three Jewels based on experience.</li>';
echo '<li><strong>Doctrine</strong> — formal religious teaching; what a tradition officially holds and teaches. Doctrine may be disputed within a tradition.</li>';
echo '<li><strong>Dogma</strong> — doctrine that has been formally defined as binding and non-negotiable; departure from dogma constitutes heresy. Strongest in Roman Catholicism and Eastern Orthodoxy; weaker in Protestant Christianity; effectively absent in most non-Abrahamic traditions.</li>';
echo '<li><strong>Proselytism</strong> — the active seeking of converts from other religions or no religion.</li>';
echo '<li><strong>Apostasy</strong> — the formal abandonment of one\'s religion. Consequences range from social exclusion to, historically, death.</li>';
echo '</ul>';

echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2b6cb0;">⊕ Judaism</h2>';
echo '<h3>Faith and Belief</h3>';
echo '<p>Judaism\'s relationship to belief is distinctive among Abrahamic religions: it is primarily a religion of <em>practice</em> (halakha — Jewish law) rather than of <em>creed</em>. There is no binding creed in Judaism in the way the Nicene Creed binds Christians. Maimonides\' Thirteen Principles of Faith (12th century CE) is the closest thing, but even this has never been formally adopted as obligatory. The principles include: God\'s existence, uniqueness, and incorporeality; revelation through the prophets; the special prophecy of Moses; the divine origin of the Torah; God\'s omniscience; reward and punishment; the coming of the Messiah; and the resurrection of the dead. Many liberal Jews do not affirm all thirteen; many Orthodox Jews do.</p>';
echo '<h3>Doctrines and Dogma</h3>';
echo '<ul>';
echo '<li><strong>Monotheism (Tawhid / Yichud Hashem)</strong> — the absolute unity of God is the foundational dogma: "Shema Yisrael: Adonai Eloheinu, Adonai Echad."</li>';
echo '<li><strong>The Chosen People (Am Segulah)</strong> — Israel has a special covenantal relationship with God; elected not for privilege but for responsibility.</li>';
echo '<li><strong>The Divine Origin of Torah</strong> — Orthodox Judaism holds that the entire Torah (written and oral) was given to Moses at Sinai. Liberal movements hold various positions on divine inspiration vs human authorship.</li>';
echo '<li><strong>Messianic Redemption</strong> — a future era of universal peace, justice, and knowledge of God, ushered in by the Messiah (a human leader, not a divine figure).</li>';
echo '<li><strong>Resurrection of the Dead (Techiyat Hameitim)</strong> — bodily resurrection at the end of days; a mainstream Orthodox belief contested by liberal movements.</li>';
echo '</ul>';
echo '<h3>Proselytism</h3>';
echo '<p>Judaism historically does <em>not</em> proselytize — it does not seek converts. The reasons are both theological (the covenant is with the Jewish people specifically) and practical (persecution made open proselytism dangerous). A non-Jew who wishes to convert must demonstrate sincere motivation, study for an extended period (typically 1–3 years), appear before a rabbinical court (beit din), immerse in the mikveh (ritual bath), and for men, undergo circumcision. The tradition teaches that a righteous person of any background (a "righteous gentile" — Noahide) has a place in the world to come without converting to Judaism.</p>';
echo '<h3>Apostasy</h3>';
echo '<p>A Jew who converts to another religion (<em>meshumad</em> or <em>anusim</em>) is considered to have committed apostasy. In halachic terms, such a person remains Jewish (Jewish identity cannot be renounced by birth) but is cut off from the community. Historically, apostasy to Christianity or Islam could lead to severe social consequences including excommunication (cherem). In modern secular contexts, consequences are primarily social. Notably, Maimonides held that even an apostate remains technically Jewish and that their acts (such as marriage) remain legally valid under Jewish law.</p>';
echo '<h3>Birth Traditions</h3>';
echo '<ul>';
echo '<li><strong>Brit Milah</strong> (circumcision) — performed on the eighth day after birth for male children; the sign of the Abrahamic covenant (Genesis 17:12). One of the most ancient and consistently observed Jewish practices.</li>';
echo '<li><strong>Naming</strong> — the baby receives a Hebrew name; Ashkenazi Jews traditionally name after deceased relatives; Sephardic Jews may name after living relatives.</li>';
echo '<li><strong>Pidyon HaBen</strong> — redemption of the firstborn son; performed 31 days after birth for the firstborn male child of a Kohen (priestly) lineage.</li>';
echo '</ul>';
echo '<h3>Marriage Traditions</h3>';
echo '<ul>';
echo '<li><strong>Kiddushin and Nisuin</strong> — the two-stage process of betrothal and marriage; traditionally performed under a chuppah (wedding canopy) with the exchange of a ring, the reading of the ketubah (marriage contract), and seven blessings (Sheva Brachot).</li>';
echo '<li><strong>Endogamy</strong> — traditional Judaism requires marriage within the faith. Intermarriage (marriage with a non-Jew) is discouraged or forbidden depending on the movement; in Orthodox Judaism it is prohibited.</li>';
echo '</ul>';
echo '<h3>Death and Burial</h3>';
echo '<ul>';
echo '<li><strong>Tahara</strong> — ritual purification of the body, performed by the Chevra Kadisha (burial society)</li>';
echo '<li><strong>Burial</strong> — the body is buried in a plain shroud (tachrichim); embalming and cremation are traditionally prohibited (though Reform Judaism permits cremation). Burial should occur as soon as possible after death.</li>';
echo '<li><strong>Shiva</strong> — seven days of mourning in the home; community comes to comfort the bereaved</li>';
echo '<li><strong>Kaddish</strong> — the memorial prayer recited by mourners for 11 months after a parent\'s death and on yahrzeit (the annual anniversary of death)</li>';
echo '<li><strong>Afterlife</strong> — Jewish afterlife beliefs vary: the Talmud mentions Gan Eden (paradise) and Gehinnom (a purgatorial realm). Resurrection of the dead is an Orthodox belief. Kabbalah adds gilgul (reincarnation).</li>';
echo '</ul>';

echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Christianity</h2>';
echo '<h3>Faith and Belief</h3>';
echo '<p>Christianity is uniquely creedal among world religions — it defined specific beliefs (doctrines) as binding on all members through a series of ecumenical councils. Faith (pistis/fides) is the central virtue: "the assurance of things hoped for, the conviction of things not seen" (Hebrews 11:1). The nature of faith — whether it requires works, whether it is God\'s gift or human response — has been the central theological dispute of Western Christianity since Paul\'s letters.</p>';
echo '<h3>Doctrines and Dogma</h3>';
echo '<ul>';
echo '<li><strong>The Trinity</strong> — God is one Being in three Persons: Father, Son, Holy Spirit. Defined at Nicaea (325 CE) and Constantinople (381 CE). Denial of the Trinity is heresy. This is the central Christian dogma and the most debated.</li>';
echo '<li><strong>The Incarnation</strong> — Jesus Christ is fully God and fully human simultaneously. Defined at Chalcedon (451 CE). The Council rejected both Nestorianism (two separate natures = two persons) and Monophysitism (only one nature — the divine).</li>';
echo '<li><strong>The Atonement</strong> — Jesus\'s death on the cross atones for human sin. The mechanism of atonement is disputed: Substitutionary Atonement (Christ took our punishment — dominant in Protestantism), Satisfaction Theory (Christ paid the debt owed to God\'s honor — Anselm, Catholic), Moral Influence (Christ\'s death inspires humans to repent — liberal Protestantism), Christus Victor (Christ defeated the powers of sin and death — Eastern Orthodox emphasis).</li>';
echo '<li><strong>The Resurrection</strong> — Jesus rose bodily from the dead on the third day. The central factual claim of Christianity: "If Christ has not been raised, your faith is futile" (1 Cor 15:17). All major traditions agree this is non-negotiable dogma.</li>';
echo '<li><strong>Salvation (Soteriology)</strong> — how humans are saved differs by tradition: Roman Catholicism teaches that salvation requires faith, works, and the sacraments administered by the Church; Protestant Reformation taught "faith alone, grace alone" (sola fide, sola gratia); Eastern Orthodoxy teaches theosis (divinization) — the progressive transformation of the human person into the divine likeness.</li>';
echo '</ul>';
echo '<h3>Proselytism</h3>';
echo '<p>Christianity is the most proselytizing religion in history — the "Great Commission" (Matthew 28:19-20) commands disciples to "make disciples of all nations." This mandate drove the global spread of Christianity through missionary activity, often combined with colonial power. The methods have ranged from peaceful preaching and education to forced conversion under colonial regimes. Today, evangelical Protestantism and Pentecostalism continue active proselytism globally; Catholic and mainline Protestant traditions emphasize witness and service more than direct conversion pressure.</p>';
echo '<h3>Apostasy</h3>';
echo '<p>In the early Church, apostasy (renouncing Christianity under persecution) was one of the three "mortal sins" (along with murder and adultery) requiring lengthy public penance for readmission. The question of whether apostates could be readmitted divided the early Church (the Donatist controversy). In medieval Europe, apostasy from Christianity to Judaism or Islam was punishable by death. Today, the Catholic Church treats apostasy as a grave sin resulting in automatic excommunication (latae sententiae). In Protestant traditions, consequences are primarily communal. Apostasy does not create legal consequences in most Western democracies.</p>';
echo '<h3>Birth Traditions</h3>';
echo '<ul>';
echo '<li><strong>Baptism</strong> — the primary initiation rite; in most traditions administered in infancy (infant baptism); in Baptist and Anabaptist traditions, only administered to conscious adult believers. Roman Catholicism teaches baptism removes original sin and regenerates the soul.</li>';
echo '<li><strong>Churching of Women</strong> — a traditional blessing for mothers after childbirth; now largely discontinued</li>';
echo '<li><strong>Godparents</strong> — sponsors who undertake responsibility for the child\'s spiritual formation</li>';
echo '</ul>';
echo '<h3>Marriage Traditions</h3>';
echo '<ul>';
echo '<li><strong>Sacrament of Marriage</strong> (Catholic/Orthodox) — marriage is a sacrament conferring grace; indissoluble except by death. The Catholic Church requires canonical form (marriage in a Catholic church before a priest) for Catholics.</li>';
echo '<li><strong>Christian marriage</strong> — generally monogamous; endogamy encouraged ("do not be unequally yoked" — 2 Cor 6:14); divorce variously treated: Roman Catholicism forbids divorce (annulment is possible); Protestant denominations generally permit divorce.</li>';
echo '</ul>';
echo '<h3>Death and Burial</h3>';
echo '<ul>';
echo '<li><strong>Last Rites</strong> (Catholic) — Anointing of the Sick (formerly Extreme Unction), Viaticum (final Eucharist), and prayer for the dying</li>';
echo '<li><strong>Burial</strong> — traditionally in consecrated ground; burial preferred over cremation historically (resurrection of the body implied physical preservation); most Protestant denominations now permit cremation; Catholic Church permitted cremation from 1963 but discourages scattering ashes</li>';
echo '<li><strong>Funeral</strong> — a church service celebrating the resurrection hope; in Catholic tradition, Requiem Mass</li>';
echo '<li><strong>Afterlife</strong> — Heaven (eternal union with God), Hell (eternal separation from God), and Purgatory (Catholic/Orthodox — a process of purification before heaven). The existence and nature of Hell is debated in modern theology (eternal conscious torment vs annihilationism vs universal salvation).</li>';
echo '</ul>';

echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Islam</h2>';
echo '<h3>Faith and Belief — The Six Pillars of Iman</h3>';
echo '<ul>';
echo '<li>Belief in Allah (God)</li>';
echo '<li>Belief in the Angels</li>';
echo '<li>Belief in the Revealed Books (Torah, Psalms, Gospel, Quran)</li>';
echo '<li>Belief in the Prophets and Messengers</li>';
echo '<li>Belief in the Day of Judgment</li>';
echo '<li>Belief in Divine Decree (Qadar) — that God has foreknowledge of all things</li>';
echo '</ul>';
echo '<p>Islam makes a sharp distinction between <em>iman</em> (faith/belief) and <em>islam</em> (submission/practice). The Quran critiques those who say "We believe" without their hearts having accepted faith (49:14). True iman involves the heart\'s conviction, verbal declaration, and action.</p>';
echo '<h3>Doctrines and Dogma</h3>';
echo '<ul>';
echo '<li><strong>Tawhid (Divine Unity)</strong> — the absolute uniqueness and oneness of God. The gravest sin in Islam is shirk — associating anything or anyone with God. The Trinity is explicitly rejected as shirk.</li>';
echo '<li><strong>Risalah (Prophethood)</strong> — God communicates through prophets; Muhammad is the final and seal of the prophets (Khatam al-Anbiya). This is non-negotiable dogma.</li>';
echo '<li><strong>Akhirah (Afterlife)</strong> — the resurrection of the dead, the Day of Judgment, Paradise (Janna) and Hell (Jahannam) are articles of faith.</li>';
echo '<li><strong>The Quran as God\'s Word</strong> — the Quran is the literal, uncreated word of God, preserved perfectly. This is Sunni orthodoxy. The Mu\'tazilite school (rationalist theology, 8th–9th centuries) held that the Quran was created — a position condemned by mainstream Sunnism.</li>';
echo '</ul>';
echo '<h3>Proselytism</h3>';
echo '<p>Islam commands <em>da\'wah</em> — "calling" to Islam — as a religious obligation. Muslims are required to share the message of Islam with non-Muslims, though conversion must be voluntary: "There is no compulsion in religion" (Quran 2:256). This verse is frequently cited against forced conversion; historically, non-Muslims under Islamic rule were protected (as dhimmis) but paid a special tax (jizya) and faced various social restrictions. Modern Islamic proselytism operates through mosques, media, literature, and online presence globally.</p>';
echo '<h3>Apostasy — Riddah</h3>';
echo '<p>Apostasy (riddah) is among the most contested issues in classical Islamic law. The hadith "Whoever changes his religion, kill him" (Bukhari) was interpreted by classical jurists as mandating the death penalty for apostasy. This remained the majority classical position in all four Sunni legal schools. In practice, implementation varied; many jurists required a period of repentance before any punishment. Modern Muslim scholars are divided: many argue the death penalty for apostasy reflects a historical conflation of religious and political treason (apostasy in early Islam often meant defection to the enemy) and is not applicable today; others maintain the classical position. Death penalty for apostasy remains law in several Muslim-majority countries. The human rights implications are severe and debated intensely within Islam.</p>';
echo '<h3>Birth Traditions</h3>';
echo '<ul>';
echo '<li><strong>Adhan</strong> — the call to prayer is whispered in the newborn\'s right ear immediately after birth</li>';
echo '<li><strong>Tahnik</strong> — a small piece of date is placed in the baby\'s mouth, preferably by a pious person</li>';
echo '<li><strong>Aqiqah</strong> — sacrifice of one or two goats on the seventh day after birth; the baby\'s head is shaved and the equivalent weight in silver given to charity</li>';
echo '<li><strong>Naming</strong> — the baby receives a Muslim name on the seventh day; names of prophets and righteous persons are encouraged</li>';
echo '<li><strong>Khitan</strong> — male circumcision; obligatory in Shafi\'i and Hanbali schools; strongly recommended (Sunnah) in Hanafi and Maliki schools</li>';
echo '</ul>';
echo '<h3>Marriage Traditions</h3>';
echo '<ul>';
echo '<li><strong>Nikah</strong> — the Islamic marriage contract; requires the consent of both parties, two witnesses, and a mahr (dower — a gift from the husband to the wife)</li>';
echo '<li><strong>Wali</strong> — a male guardian (father, brother, uncle) represents the bride in Sunni Islam; the Wali\'s consent is required in most schools</li>';
echo '<li><strong>Polygyny</strong> — Islamic law permits a man to marry up to four wives, subject to the condition of treating all equally (Quran 4:3); a condition many scholars argue effectively limits polygyny</li>';
echo '<li><strong>Interfaith marriage</strong> — Muslim men may marry Jewish or Christian women (People of the Book); Muslim women may not marry non-Muslim men under classical law</li>';
echo '</ul>';
echo '<h3>Death and Burial</h3>';
echo '<ul>';
echo '<li><strong>The dying</strong> — the Shahada (declaration of faith) should be the last words; family recites prayers</li>';
echo '<li><strong>Ghusl</strong> — ritual washing of the body by same-sex persons</li>';
echo '<li><strong>Kafan</strong> — the body is wrapped in white unsewn cloth</li>';
echo '<li><strong>Salat al-Janazah</strong> — the funeral prayer</li>';
echo '<li><strong>Burial</strong> — should occur as soon as possible (within 24 hours if possible); body laid on its right side facing Mecca; no embalming; no elaborate coffin; cremation is prohibited</li>';
echo '<li><strong>Mourning</strong> — three days of mourning for family; widows observe four months and ten days of iddah (waiting period before remarriage)</li>';
echo '</ul>';

echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2d6a1f;">⊕ Hinduism</h2>';
echo '<h3>Faith and Belief</h3>';
echo '<p>Hinduism has no single creed, no founder, and no central authority — making the concept of "dogma" problematic. Different schools (Advaita, Vishishtadvaita, Dvaita) hold fundamentally different metaphysical positions. What unifies Hinduism is less a set of beliefs than a set of practices, texts, and social structures (including the caste system). The Vedas are accepted as authoritative by all orthodox Hindu schools; the Upanishads, Bhagavad Gita, and Puranas carry varying weight in different traditions.</p>';
echo '<h3>Doctrines</h3>';
echo '<ul>';
echo '<li><strong>Brahman</strong> — the ultimate reality, infinite, self-existent. Whether Brahman is identical with the individual soul (Advaita — Shankara), related but distinct (Vishishtadvaita — Ramanuja), or completely distinct (Dvaita — Madhva) is the central theological dispute.</li>';
echo '<li><strong>Dharma</strong> — cosmic and social order; one\'s duty according to one\'s nature, stage of life (ashrama), and social position (varna). Dharma is context-specific — there is no single moral code for all persons in all situations.</li>';
echo '<li><strong>Karma and Samsara</strong> — the law of action and its consequences across multiple lives; the cycle of rebirth. These are accepted by all Hindu schools.</li>';
echo '<li><strong>Moksha</strong> — liberation from samsara; the ultimate goal. How it is achieved (through knowledge, devotion, or action) and what it consists of (dissolution into Brahman, eternal relationship with God, or permanent individual existence in God\'s presence) varies by school.</li>';
echo '</ul>';
echo '<h3>Proselytism</h3>';
echo '<p>Classical Hinduism does <em>not</em> proselytize — one is born into Hinduism through one\'s caste and family; Hinduism was not designed as a universal religion. However, certain modern Hindu movements do accept converts: ISKCON (Hare Krishnas), Arya Samaj, and Ramakrishna Mission have all, to varying degrees, welcomed non-Hindu seekers. The RSS (Rashtriya Swayamsevak Sangh) and related organizations practice <em>ghar wapsi</em> ("homecoming") — reconversion of Christians and Muslims who are argued to be of Hindu origin.</p>';
echo '<h3>Apostasy</h3>';
echo '<p>Traditional Hinduism has no formal apostasy doctrine — one cannot exactly "leave" Hinduism since membership is by birth. However, a Hindu who converts to another religion (especially Christianity or Islam) may face social consequences including exclusion from family rituals, loss of caste status, and family pressure to return. In India\'s increasingly polarized political environment, conversion from Hinduism to Christianity or Islam has become politically sensitive, with "anti-conversion" laws in several states.</p>';
echo '<h3>Birth Traditions (Samskaras)</h3>';
echo '<ul>';
echo '<li><strong>Jatakarma</strong> — rites performed at birth: the father touches the baby\'s lips with honey and ghee while whispering the baby\'s name and a prayer</li>';
echo '<li><strong>Namakarana</strong> — naming ceremony on the 11th or 12th day</li>';
echo '<li><strong>Annaprashana</strong> — first feeding of solid food (rice), typically at 6 months</li>';
echo '<li><strong>Upanayana</strong> — sacred thread ceremony; initiation into the student stage of life (brahmacharya); traditionally for upper-caste males</li>';
echo '</ul>';
echo '<h3>Marriage Traditions</h3>';
echo '<ul>';
echo '<li><strong>Vivaha</strong> — Hindu marriage is a sacrament (samskara), not a contract. The central rite is the Saptapadi — seven steps around the sacred fire, each with a specific vow. After seven steps, the couple are irrevocably married.</li>';
echo '<li><strong>Dowry (Dahej)</strong> — gifts from the bride\'s family; legally prohibited in India but culturally persistent. A source of significant domestic violence.</li>';
echo '<li><strong>Caste endogamy</strong> — marriage within one\'s caste is traditional; intercaste marriage has been legal since 1955 but remains socially controversial in many communities.</li>';
echo '</ul>';
echo '<h3>Death and Burial</h3>';
echo '<ul>';
echo '<li><strong>Antyesti (Funeral Rites)</strong> — the last samskara. The body is washed, wrapped in white cloth, and cremated as soon as possible (typically within 24 hours). Cremation returns the body to the five elements.</li>';
echo '<li><strong>The pyre</strong> — lit by the eldest son (or closest male relative) who also breaks the skull at the appropriate moment to release the soul</li>';
echo '<li><strong>Ashes</strong> — immersed in a sacred river, ideally the Ganges at Varanasi (the most auspicious place to die and be cremated)</li>';
echo '<li><strong>Shraddha</strong> — ancestral rites performed on specific days to feed and honor the deceased; the pitru (ancestors) must be kept satisfied or they may cause misfortune</li>';
echo '<li><strong>Mourning period</strong> — typically 13 days; the family is in a state of ritual impurity; specific rites on the 13th day conclude the mourning</li>';
echo '</ul>';

echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#553c9a;">⊕ Buddhism</h2>';
echo '<h3>Faith and Belief</h3>';
echo '<p>Buddhism distinguishes between <em>saddha</em> (faith/confidence — in Pali) and <em>panna</em> (wisdom/insight). Saddha is not blind belief but confidence based on reasoning and experience — confidence in the Buddha as a reliable guide, confidence in the Dharma as true, confidence in the Sangha as a supportive community. The Buddha himself discouraged blind faith: "Do not accept anything on mere hearsay... Do not accept anything by mere tradition... When you know for yourselves: \'These things are good, blameless, praised by the wise, and when adopted and carried out they lead to welfare and happiness,\' then you should accept and practice them." (Kalama Sutta)</p>';
echo '<h3>Doctrines</h3>';
echo '<ul>';
echo '<li><strong>The Four Noble Truths</strong> — the doctrinal foundation; not metaphysical claims about ultimate reality but diagnostic statements about suffering and its cure</li>';
echo '<li><strong>The Three Jewels (Tiratana)</strong> — Buddha (the awakened teacher), Dharma (the teaching), Sangha (the community); taking refuge in the Three Jewels is the act of becoming Buddhist</li>';
echo '<li><strong>Anatta (No-Self)</strong> — the most philosophically radical Buddhist doctrine; there is no permanent, unchanging self. This distinguishes Buddhism from all other Indian traditions that affirm a permanent soul (atman).</li>';
echo '<li><strong>Sunyata (Emptiness)</strong> — Mahayana Buddhism extends anatta: all phenomena are empty of inherent existence; they exist only in dependence on other phenomena. Nagarjuna\'s Madhyamaka philosophy is the most rigorous exposition.</li>';
echo '</ul>';
echo '<h3>Proselytism</h3>';
echo '<p>Buddhism has spread globally but has historically avoided coercive proselytism. The Buddha\'s model was to teach those who came to him and to send monks out to teach "for the welfare of the many, out of compassion for the world." Buddhism spread through example, royal patronage (Ashoka), and the attraction of its teaching rather than through military conquest or legal coercion. Modern Buddhism actively welcomes converts through dharma centers, books, and online teaching — but does not pressure or coerce.</p>';
echo '<h3>Apostasy</h3>';
echo '<p>Buddhism has no concept of apostasy equivalent to the Abrahamic traditions. One can leave Buddhism — simply by no longer taking refuge in the Three Jewels — without any legal or formal consequence. There is no Buddhist equivalent of excommunication. The tradition teaches that each person must walk the path for themselves; forcing or manipulating someone\'s religious identity is antithetical to Buddhist ethics.</p>';
echo '<h3>Birth Traditions</h3>';
echo '<ul>';
echo '<li>Buddhist birth practices vary enormously by culture. In Theravada countries, monks may chant Paritta (protective suttas) over the mother during pregnancy and after birth.</li>';
echo '<li>In Tibetan Buddhism, a lama may be consulted to determine the auspiciousness of the birth and the child\'s spiritual connections.</li>';
echo '<li>Naming often involves the monk or family choosing a name from the Buddhist calendar or associated with a Buddha or Bodhisattva.</li>';
echo '</ul>';
echo '<h3>Marriage Traditions</h3>';
echo '<p>Buddhism has no sacrament of marriage — marriage is a civil/social institution, not a religious one. Monks may bless a marriage and chant suttas for the couple\'s wellbeing, but the actual marriage is performed outside the monastic context. Buddhist marriages vary entirely by local culture (Sinhalese, Thai, Tibetan, Japanese, etc.).</p>';
echo '<h3>Death and Burial</h3>';
echo '<ul>';
echo '<li><strong>Theravada</strong>: monks chant suttas for the dying and the dead; the dying person is encouraged to maintain mindfulness and call to mind virtuous deeds; cremation is traditional (following the Buddha\'s own cremation)</li>';
echo '<li><strong>Tibetan Buddhism</strong>: the <em>Bardo Thodol</em> (Tibetan Book of the Dead) is read aloud to the deceased for 49 days to guide the consciousness through the intermediate state (bardo) toward a favorable rebirth; sky burial (exposure of the body to vultures) is traditional in Tibet</li>';
echo '<li><strong>Japanese Buddhism</strong>: elaborate funeral rites; posthumous Buddhist names (kaimyo) given; elaborate memorial services (obon — annual remembrance of ancestors)</li>';
echo '</ul>';

echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2d6a1f;">⊕ Ọdinala (Igbo) — Doctrines, Faith, and Life Cycle</h2>';
echo '<h3>Faith and Belief</h3>';
echo '<p>Ọdinala does not require propositional faith in the Abrahamic sense — one does not "convert" to Ọdinala or sign up to a creed. It is the birthright tradition of the Igbo people, transmitted through family, community, and ritual practice. Belief is embedded in action: participating in the New Yam Festival, presenting kola, honoring one\'s chi, maintaining proper relationships with the ancestors — these are not optional expressions of prior belief but constitutive of Igbo religious identity. The separation of "believing" from "doing" is a Western (specifically Protestant) framework that does not map onto Ọdinala.</p>';
echo '<h3>Core Doctrines</h3>';
echo '<ul>';
echo '<li><strong>Chukwu is One (Chukwu bu otu)</strong> — the ultimate reality is one divine source; all divine forces (alusi) are aspects of this one source. Ọdinala is panentheistic, not simply polytheistic.</li>';
echo '<li><strong>Chi determines destiny</strong> — one\'s personal divine force (chi) was chosen before birth; it shapes one\'s life path. Success or failure reflects the chi\'s quality and one\'s alignment or misalignment with it.</li>';
echo '<li><strong>Ala is the moral foundation</strong> — the earth goddess Ala is the ground of ethics; nso Ala (abomination) is a crime against cosmic order requiring communal purification.</li>';
echo '<li><strong>The ancestors are present</strong> — the dead do not disappear; they join the community of ancestors (ndichie) who monitor, support, and occasionally punish the living. Ancestral displeasure is a real spiritual force.</li>';
echo '</ul>';
echo '<h3>Proselytism</h3>';
echo '<p>Ọdinala does not proselytize. It is not designed as a universal religion; it is the spiritual tradition of a specific people in a specific land. The concept of converting others to Ọdinala is alien to its structure. One is Igbo; one practices Ọdinala as part of being Igbo. This is both its limitation (it cannot expand by missionary activity) and its strength (it is not a commodity to be sold but a heritage to be maintained).</p>';
echo '<h3>Apostasy</h3>';
echo '<p>There is no formal Ọdinala concept of apostasy. A person who converts to Christianity or Islam does not face formal religious punishment — there is no Ọdinala court or authority to administer one. However, conversion has social consequences: the convert may be excluded from certain family rituals, may not be eligible to pour libations or perform ancestral rites, and in communities where Ọdinala is still strong, may face social marginalization. Many Igbo people practice a form of dual belonging — Christian in public and church attendance, but maintaining ancestral rites at home, participating in masquerade festivals, and observing the four-day market week as a ritual calendar.</p>';
echo '<h3>Birth Traditions</h3>';
echo '<ul>';
echo '<li><strong>Naming ceremony (Igu aha / Ọmụọ nwa)</strong> — on the fourth day after birth (following the Igbo four-day week); the child is formally welcomed into the human community and given its name. The name encodes theology, family history, and aspiration.</li>';
echo '<li><strong>The chi is acknowledged</strong> — the child\'s chi is recognized as accompanying the new life; prayers are offered to the chi and to the ancestors</li>';
echo '<li><strong>Twins (Ejima)</strong> — considered specially blessed in Igbo tradition; associated with fortune and abundance. Contrast with some other West African traditions (notably some Yoruba and Igala communities historically) where twins were seen as anomalous.</li>';
echo '<li><strong>Ọgbanje identification</strong> — if a family has suffered repeated infant deaths, a dibia may be consulted to determine if the new child is an ọgbanje; if so, the iyi-uwa (covenant stone) is sought and destroyed</li>';
echo '</ul>';
echo '<h3>Marriage Traditions</h3>';
echo '<ul>';
echo '<li><strong>Ime ego / Ikwu ego</strong> — bride price negotiations between families; not the purchase of a person but the formalization of a covenant between two lineages</li>';
echo '<li><strong>Igba nkwu</strong> — the wine-carrying ceremony: the bride carries palm wine to her chosen husband in a public celebration attended by both families and the wider community; this public act of choice is the heart of the ceremony</li>';
echo '<li><strong>Iku aka n\'ulo</strong> — the formal introduction of the groom\'s family to the bride\'s family; the beginning of the marriage negotiations</li>';
echo '<li><strong>Ancestral acknowledgment</strong> — the ancestors of both families are acknowledged and propitiated; the marriage is not only between two individuals but between two lineages and their ancestral lines</li>';
echo '</ul>';
echo '<h3>Death and Burial</h3>';
echo '<ul>';
echo '<li><strong>Good death vs bad death</strong> — a death at old age after a full life is a "good death" (onwu ọma) and is celebrated with elaborate ceremonies; a premature death, death by suicide, death by lightning, or death from certain illnesses is a "bad death" and is handled differently — often without full funeral rites</li>';
echo '<li><strong>Ikwa ozu (funeral ceremony)</strong> — can last multiple days; music, masquerades, feasting, eulogies; the community comes together to honor the dead and comfort the bereaved; the quality and scale of the funeral reflects the dead person\'s social standing and the family\'s resources</li>';
echo '<li><strong>Burial in the compound</strong> — traditionally, the dead are buried within the family compound (in their land); this keeps the ancestors close to the family they protect</li>';
echo '<li><strong>Masquerades</strong> — the Mmanwu (ancestral masquerades) appear at funerals as manifestations of the ancestral spirits paying their respects and celebrating the life of the deceased</li>';
echo '<li><strong>Second burial (Iwa ọkwa)</strong> — for prominent persons, a second, even more elaborate ceremony may be held weeks or months after the initial burial; this "sends" the deceased properly into the ancestral realm and elevates them among the honored dead</li>';
echo '<li><strong>Ilo uwa (return)</strong> — the Igbo do not fear death as the Abrahamic traditions conceptualize judgment; the dead become ancestors who will eventually return (ilo uwa) within the family lineage. Death is a passage, not an ending.</li>';
echo '</ul>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/metempsychosis/">Metempsychosis & Karma</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">Full Map</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/abrahamic/">Abrahamic Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/eastern/">Eastern Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/african/">African Religions</a>';
echo '</div></div>';
