<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Eastern religious traditions in depth — Hinduism, Buddhism, Jainism, Sikhism, Confucianism, Taoism, Shinto, Zoroastrianism.</p>';

// HINDUISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#b7791f;">⊕ Hinduism</h2>';
echo '<p><strong>Region:</strong> Indian subcontinent | <strong>Founded:</strong> c. 1500 BCE (Vedic period) | <strong>Followers:</strong> ~1.2 billion | <strong>Status:</strong> Living</p>';
echo '<h3>Origin</h3>';
echo '<p>Hinduism is the world\'s oldest living religion and the third largest by followers. It has no single founder, no single sacred text, and no central authority — it is better understood as a family of related traditions unified by certain core concepts. Its roots lie in the Indus Valley Civilization (c. 2500 BCE) and the Vedic tradition brought by Indo-Aryan peoples (c. 1500 BCE). The name "Hinduism" was applied by Persian and later European observers to the diverse religious practices of people living beyond the Indus River.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Brahman</strong> — the ultimate, formless, infinite reality underlying all existence. The universe is Brahman\'s self-expression.</li>';
echo '<li><strong>Atman</strong> — the individual soul/self, identical in essence with Brahman. "Tat tvam asi" — That thou art.</li>';
echo '<li><strong>Dharma</strong> — cosmic order, duty, righteousness. Each being has a dharma appropriate to their nature and stage of life.</li>';
echo '<li><strong>Karma</strong> — the law of cause and effect. Every action creates consequences that shape future experience, in this life and future lives.</li>';
echo '<li><strong>Samsara</strong> — the cycle of birth, death, and rebirth driven by karma and attachment.</li>';
echo '<li><strong>Moksha</strong> — liberation from samsara — the ultimate goal of Hindu religious life. Achieved through jnana (knowledge), bhakti (devotion), karma yoga (right action), or raja yoga (meditation).</li>';
echo '<li><strong>The Trimurti</strong> — the threefold divine: Brahma (creator), Vishnu (preserver), Shiva (destroyer/transformer).</li>';
echo '</ul>';
echo '<h3>Major Deities</h3>';
echo '<ul>';
echo '<li><strong>Brahma</strong> — the creator god, now rarely worshipped directly</li>';
echo '<li><strong>Vishnu</strong> — the preserver; appears in ten avatars including Rama and Krishna</li>';
echo '<li><strong>Shiva</strong> — the destroyer and transformer; lord of yoga, dance (Nataraja), and meditation</li>';
echo '<li><strong>Devi / Shakti</strong> — the divine feminine in her many forms: Durga, Kali, Lakshmi, Saraswati, Parvati</li>';
echo '<li><strong>Ganesha</strong> — elephant-headed son of Shiva and Parvati; remover of obstacles, lord of beginnings</li>';
echo '<li><strong>Krishna</strong> — eighth avatar of Vishnu; teacher of the Bhagavad Gita; divine lover in the Bhagavata Purana</li>';
echo '<li><strong>Rama</strong> — seventh avatar of Vishnu; ideal king and husband; hero of the Ramayana</li>';
echo '<li><strong>Hanuman</strong> — divine monkey, devotee of Rama; symbol of strength and service</li>';
echo '<li><strong>Saraswati</strong> — goddess of knowledge, arts, music, and wisdom</li>';
echo '<li><strong>Lakshmi</strong> — goddess of wealth, prosperity, and fortune</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Vedas</strong> (c. 1500–500 BCE) — four collections: Rigveda, Samaveda, Yajurveda, Atharvaveda — the oldest Hindu scriptures</li>';
echo '<li><strong>The Upanishads</strong> (c. 800–200 BCE) — philosophical treatises exploring the nature of Brahman and Atman</li>';
echo '<li><strong>The Bhagavad Gita</strong> (c. 200 BCE) — Krishna\'s teaching to Arjuna on the battlefield; the most widely read Hindu text worldwide</li>';
echo '<li><strong>The Mahabharata</strong> — the world\'s longest epic poem; contains the Bhagavad Gita</li>';
echo '<li><strong>The Ramayana</strong> — Rama\'s journey to rescue Sita from Ravana</li>';
echo '<li><strong>The Puranas</strong> — 18 major texts containing myths, cosmology, and devotional teachings</li>';
echo '<li><strong>The Manusmriti</strong> — law code; controversial for its caste prescriptions</li>';
echo '</ul>';
echo '<h3>Major Traditions (Sampradayas)</h3>';
echo '<ul>';
echo '<li><strong>Vaishnavism</strong> — devotion to Vishnu and his avatars; the largest Hindu tradition</li>';
echo '<li><strong>Shaivism</strong> — devotion to Shiva; prominent in South India, Kashmir, Nepal</li>';
echo '<li><strong>Shaktism</strong> — devotion to the divine feminine (Devi/Shakti)</li>';
echo '<li><strong>Smartism</strong> — worship of multiple deities as aspects of Brahman; follows Adi Shankaracharya\'s Advaita Vedanta</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Puja</strong> — daily worship at home shrines or temples; offering flowers, food, incense to the deity</li>';
echo '<li><strong>Yoga</strong> — physical, mental, and spiritual practices for liberation; many forms (Hatha, Raja, Karma, Jnana, Bhakti)</li>';
echo '<li><strong>Pilgrimage (Tirtha)</strong> — sacred journeys to holy rivers, cities, and temples</li>';
echo '<li><strong>Life cycle rites (Samskaras)</strong> — 16 rites from conception to death marking life transitions</li>';
echo '<li><strong>Caste system (Varna)</strong> — traditional social hierarchy: Brahmin (priest), Kshatriya (warrior), Vaishya (merchant), Shudra (servant) — deeply contested and undergoing transformation</li>';
echo '<li><strong>Festivals</strong> — Diwali (festival of lights), Holi (festival of colors), Navaratri (nine nights of Devi), Dussehra, Ganesh Chaturthi</li>';
echo '</ul>';

// BUDDHISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Buddhism</h2>';
echo '<p><strong>Founded:</strong> c. 500 BCE | <strong>Founder:</strong> Siddhartha Gautama (the Buddha) | <strong>Origin:</strong> Lumbini, Nepal/northern India | <strong>Followers:</strong> ~500 million</p>';
echo '<h3>The Founder</h3>';
echo '<p>Siddhartha Gautama was born c. 563 BCE to a noble family in Lumbini (modern Nepal). Sheltered from suffering by his father, he encountered old age, sickness, and death during trips outside the palace. These "four sights" prompted him to abandon his comfortable life at 29 and seek liberation through ascetic practice. After six years, he rejected extreme asceticism and sat under a Bodhi tree in Bodh Gaya until he achieved enlightenment (Bodhi) at around age 35. He spent the next 45 years teaching, and died at approximately 80 years of age. The title "Buddha" means "the Awakened One."</p>';
echo '<h3>Core Teachings</h3>';
echo '<ul>';
echo '<li><strong>The Four Noble Truths</strong> — (1) Life involves suffering (dukkha); (2) Suffering arises from craving (tanha); (3) Suffering can cease; (4) The path to cessation is the Eightfold Path.</li>';
echo '<li><strong>The Noble Eightfold Path</strong> — Right View, Right Intention, Right Speech, Right Action, Right Livelihood, Right Effort, Right Mindfulness, Right Concentration.</li>';
echo '<li><strong>The Three Marks of Existence</strong> — Impermanence (anicca), Suffering (dukkha), No-self (anatta). All conditioned phenomena are impermanent; clinging to them causes suffering.</li>';
echo '<li><strong>Dependent Origination</strong> — all phenomena arise in dependence on conditions. Nothing exists independently. This applies to the self — there is no permanent, unchanging self.</li>';
echo '<li><strong>Nirvana</strong> — the extinguishing of craving and the cessation of suffering. Not a place but a state — the liberation from the cycle of rebirth.</li>';
echo '<li><strong>Karma and Rebirth</strong> — actions create karmic consequences that condition future rebirths. The goal is to break the cycle through wisdom and ethical action.</li>';
echo '</ul>';
echo '<h3>Major Traditions</h3>';
echo '<ul>';
echo '<li><strong>Theravada</strong> ("Way of the Elders") — oldest surviving school; dominant in Sri Lanka, Thailand, Myanmar, Cambodia, Laos. Emphasizes the Pali Canon and the path of the monk.</li>';
echo '<li><strong>Mahayana</strong> ("Great Vehicle") — dominant in China, Japan, Korea, Vietnam, Tibet. Emphasizes the bodhisattva ideal — delaying one\'s own nirvana to help all beings achieve liberation.</li>';
echo '<li><strong>Vajrayana</strong> ("Diamond Vehicle") — Tibetan Buddhism; uses tantric practices, mandalas, mantras, and visualization to accelerate the path to liberation. Associated with the Dalai Lama tradition.</li>';
echo '<li><strong>Zen / Chan</strong> — Japanese/Chinese school emphasizing meditation, direct experience, and sudden enlightenment over scriptural study.</li>';
echo '<li><strong>Pure Land</strong> — devotional school; faith in Amitabha Buddha and rebirth in the Pure Land (Western Paradise) as a route to liberation.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>Pali Canon (Tripitaka)</strong> — the oldest complete Buddhist scripture; Theravada tradition</li>';
echo '<li><strong>Dhammapada</strong> — most widely read Buddhist text; sayings of the Buddha</li>';
echo '<li><strong>Heart Sutra</strong> — core Mahayana text on emptiness (sunyata)</li>';
echo '<li><strong>Diamond Sutra</strong> — Mahayana; on the nature of reality and non-attachment</li>';
echo '<li><strong>Lotus Sutra</strong> — Mahayana; teaching of universal Buddhahood</li>';
echo '<li><strong>Tibetan Book of the Dead (Bardo Thodol)</strong> — guide to the after-death experience; Vajrayana</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Meditation (Dhyana)</strong> — central practice; mindfulness (Vipassana) and concentration (Samatha)</li>';
echo '<li><strong>Taking refuge</strong> — in the Three Jewels: Buddha, Dharma (teachings), Sangha (community)</li>';
echo '<li><strong>Five Precepts</strong> — not to kill, steal, engage in sexual misconduct, lie, or take intoxicants</li>';
echo '<li><strong>Dana</strong> — generosity; giving to monks and the community</li>';
echo '<li><strong>Monasticism</strong> — core institution; monks and nuns preserve and transmit the teaching</li>';
echo '<li><strong>Pilgrimage</strong> — to Bodh Gaya (enlightenment), Lumbini (birth), Sarnath (first teaching), Kushinagar (death)</li>';
echo '</ul>';

// SIKHISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2b6cb0;">⊕ Sikhism</h2>';
echo '<p><strong>Founded:</strong> 1499 CE | <strong>Founder:</strong> Guru Nanak Dev Ji | <strong>Origin:</strong> Punjab (modern Pakistan/India) | <strong>Followers:</strong> ~25-30 million</p>';
echo '<h3>The Founder</h3>';
echo '<p>Guru Nanak (1469–1539) was born in Talwandi (modern Pakistan) to a Hindu family in a Muslim-majority region. At approximately 30 years of age, he had a mystical experience — disappearing into a river for three days and emerging with a divine commission. He declared: "There is no Hindu, there is no Muslim" — a rejection of religious division that became the foundation of Sikhism. He traveled widely (possibly reaching Mecca, Baghdad, and Sri Lanka) teaching a message of one God, equality, and service. He was followed by nine successive human Gurus, the last of whom (Guru Gobind Singh, d. 1708) declared the scripture itself — the Guru Granth Sahib — as the eternal, living Guru.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Ik Onkar</strong> — "There is One God." The opening statement of the Guru Granth Sahib and the foundation of Sikh theology. God is formless, timeless, and without equal.</li>';
echo '<li><strong>Waheguru</strong> — the most common Sikh name for God: "Wonderful Lord." God is personal and can be experienced through devotion and meditation.</li>';
echo '<li><strong>Naam Japna</strong> — meditating on God\'s name. Constant remembrance of God is the path to liberation.</li>';
echo '<li><strong>Kirat Karni</strong> — honest labor. Earning one\'s living through honest means is a religious obligation.</li>';
echo '<li><strong>Vand Chakna</strong> — sharing with others. A portion of one\'s earnings and time must be given to the community.</li>';
echo '<li><strong>Karma and Reincarnation</strong> — accepted from the Hindu context; the goal is liberation (mukti) from the cycle of rebirth through God\'s grace (nadar).</li>';
echo '<li><strong>Rejection of caste</strong> — Sikhism explicitly rejected the caste system; all humans are equal before God.</li>';
echo '</ul>';
echo '<h3>The Ten Gurus</h3>';
echo '<ul>';
echo '<li><strong>Guru Nanak</strong> (1469–1539) — founder</li>';
echo '<li><strong>Guru Angad</strong> (1504–1552) — standardized Gurmukhi script</li>';
echo '<li><strong>Guru Amar Das</strong> (1479–1574) — established langar (free community kitchen)</li>';
echo '<li><strong>Guru Ram Das</strong> (1534–1581) — founded Amritsar</li>';
echo '<li><strong>Guru Arjan Dev</strong> (1563–1606) — compiled the Adi Granth (first scripture); martyred by Mughal Emperor Jahangir</li>';
echo '<li><strong>Guru Hargobind</strong> (1595–1644) — militarized the Sikh community (Miri-Piri)</li>';
echo '<li><strong>Guru Har Rai</strong> (1630–1661)</li>';
echo '<li><strong>Guru Har Krishan</strong> (1656–1664) — youngest Guru, died at age 8</li>';
echo '<li><strong>Guru Tegh Bahadur</strong> (1621–1675) — martyred by Mughal Emperor Aurangzeb for protecting Hindu religious freedom</li>';
echo '<li><strong>Guru Gobind Singh</strong> (1666–1708) — established the Khalsa (community of the pure); declared the Guru Granth Sahib as eternal Guru</li>';
echo '</ul>';
echo '<h3>Sacred Text</h3>';
echo '<p><strong>Guru Granth Sahib</strong> — the eternal, living Guru of the Sikhs. A 1,430-page scripture containing hymns by the Sikh Gurus and by Hindu and Muslim saints (including Kabir and Sheikh Farid). Treated with the same reverence as a living Guru — installed on a throne, fanned, put to rest at night.</p>';
echo '<h3>The Five Ks (Panj Kakars)</h3>';
echo '<p>Khalsa Sikhs wear five articles of faith:</p>';
echo '<ul>';
echo '<li><strong>Kesh</strong> — uncut hair (covered by turban) — respecting God\'s creation</li>';
echo '<li><strong>Kangha</strong> — wooden comb — cleanliness and order</li>';
echo '<li><strong>Kara</strong> — steel bracelet — reminder of God\'s infinity and ethical conduct</li>';
echo '<li><strong>Kachera</strong> — cotton undergarment — modesty and self-control</li>';
echo '<li><strong>Kirpan</strong> — ceremonial steel sword — commitment to justice and defense of the weak</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Langar</strong> — free community kitchen; everyone sits together and eats regardless of caste, religion, or status. One of the most radical social practices in any religion.</li>';
echo '<li><strong>Simran</strong> — meditation on God\'s name</li>';
echo '<li><strong>Kirtan</strong> — devotional music; singing of hymns from the Guru Granth Sahib</li>';
echo '<li><strong>Seva</strong> — selfless service to the community</li>';
echo '<li><strong>Gurdwara</strong> — "Gateway to the Guru" — the Sikh place of worship, open to all</li>';
echo '</ul>';

// CONFUCIANISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Confucianism</h2>';
echo '<p><strong>Founded:</strong> c. 500 BCE | <strong>Founder:</strong> Kong Qiu (Confucius) | <strong>Origin:</strong> China (state of Lu) | <strong>Status:</strong> Living (philosophical tradition)</p>';
echo '<h3>The Founder</h3>';
echo '<p>Kong Qiu (551–479 BCE) — known in the West as Confucius (a Latinization of Kong Fuzi, "Master Kong") — was a teacher, political advisor, and philosopher in the state of Lu (modern Shandong Province, China). Born to an impoverished noble family, he devoted his life to studying and transmitting the values of the Zhou Dynasty classics. He spent years traveling from state to state seeking a ruler who would implement his vision of ethical government, without sustained success. His teachings were compiled by disciples in the <em>Analects</em> (Lunyu).</p>';
echo '<h3>Core Teachings</h3>';
echo '<ul>';
echo '<li><strong>Ren (仁) — Benevolence/Humaneness</strong> — the supreme virtue: love for others, empathy, and compassionate human-heartedness. "What you do not wish for yourself, do not do to others."</li>';
echo '<li><strong>Yi (義) — Righteousness</strong> — doing what is morally right regardless of personal gain.</li>';
echo '<li><strong>Li (禮) — Ritual Propriety</strong> — the correct performance of social rituals, customs, and ceremonies that maintain social harmony.</li>';
echo '<li><strong>Zhi (智) — Wisdom</strong> — moral knowledge and discernment.</li>';
echo '<li><strong>Xin (信) — Faithfulness</strong> — integrity and keeping one\'s word.</li>';
echo '<li><strong>The Five Relationships</strong> — ruler/subject, father/son, husband/wife, elder brother/younger brother, friend/friend. Each relationship has specific duties and obligations. Harmony in these relationships produces social harmony.</li>';
echo '<li><strong>Filial Piety (Xiao)</strong> — reverence for parents and ancestors; the foundation of all other virtues.</li>';
echo '<li><strong>The Junzi (君子) — The Noble Person</strong> — the Confucian ideal: a person of moral cultivation, not necessarily of noble birth.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Analects (Lunyu)</strong> — sayings and conversations of Confucius, compiled by disciples</li>';
echo '<li><strong>The Five Classics</strong> — Book of Changes (I Ching), Book of Documents, Book of Songs, Book of Rites, Spring and Autumn Annals — ancient texts Confucius edited and taught</li>';
echo '<li><strong>The Four Books</strong> — Analects, Mencius, Great Learning, Doctrine of the Mean — core Neo-Confucian curriculum</li>';
echo '</ul>';
echo '<h3>Key Thinkers</h3>';
echo '<ul>';
echo '<li><strong>Mencius (Mengzi, 372–289 BCE)</strong> — argued human nature is inherently good; developed Confucian political thought</li>';
echo '<li><strong>Xunzi (310–235 BCE)</strong> — argued human nature is inherently bad; cultivation and ritual are essential</li>';
echo '<li><strong>Zhu Xi (1130–1200 CE)</strong> — synthesized Neo-Confucianism; his interpretation dominated East Asian education for centuries</li>';
echo '<li><strong>Wang Yangming (1472–1529)</strong> — "Knowledge and action are one" — subjective idealist Neo-Confucianism</li>';
echo '</ul>';
echo '<h3>Influence</h3>';
echo '<p>Confucianism was the official state ideology of China for over 2,000 years and shaped the civil service examination system that governed Chinese government until 1905. Its influence spread to Korea, Japan, Vietnam, and all of East Asia. The Confucian family values, educational emphasis, and respect for social hierarchy continue to shape East Asian culture profoundly.</p>';

// TAOISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#1a365d;">⊕ Taoism (Daoism)</h2>';
echo '<p><strong>Founded:</strong> c. 400 BCE (philosophical); c. 100 CE (religious) | <strong>Attributed to:</strong> Laozi | <strong>Origin:</strong> China | <strong>Followers:</strong> ~20 million (formal)</p>';
echo '<h3>The Founder</h3>';
echo '<p>Laozi ("Old Master") is the legendary author of the Tao Te Ching and the founding figure of Taoism. His historical existence is debated — he may be a composite of several figures or entirely legendary. According to tradition, he was a keeper of archives in the Zhou Dynasty court who, despairing of the world\'s corruption, rode west on a water buffalo and was persuaded by a gatekeeper to write down his wisdom before disappearing. The resulting 81 short chapters — the Tao Te Ching — is one of the most translated books in history.</p>';
echo '<h3>Core Concepts</h3>';
echo '<ul>';
echo '<li><strong>Tao (道) — The Way</strong> — the fundamental principle underlying and unifying all reality. It cannot be defined or named: "The Tao that can be told is not the eternal Tao." It is the source of all things, the pattern of nature, and the proper mode of human life.</li>';
echo '<li><strong>Te (德) — Virtue/Power</strong> — the manifestation of the Tao in particular things; the inherent nature or power of each being.</li>';
echo '<li><strong>Wu Wei (無為) — Non-action/Effortless action</strong> — acting in harmony with the natural flow of things rather than forcing outcomes. Not passivity but alignment with the Tao.</li>';
echo '<li><strong>Yin and Yang</strong> — complementary opposites that together constitute the dynamic balance of reality. Not good vs evil but complementary forces in constant interplay.</li>';
echo '<li><strong>Ziran (自然) — Naturalness</strong> — following one\'s inherent nature; simplicity and spontaneity as the highest mode of life.</li>';
echo '<li><strong>The Three Treasures</strong> — compassion (ci), frugality (jian), and humility (bu gan wei tianxia xian).</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>Tao Te Ching</strong> — 81 chapters attributed to Laozi; the foundational text of philosophical Taoism</li>';
echo '<li><strong>Zhuangzi</strong> — writings of Zhuang Zhou (369–286 BCE); playful, paradoxical explorations of Taoist philosophy</li>';
echo '<li><strong>Liezi</strong> — Taoist text containing stories and teachings</li>';
echo '<li><strong>The Taoist Canon (Daozang)</strong> — over 1,400 texts compiled across centuries</li>';
echo '</ul>';
echo '<h3>Religious Taoism vs Philosophical Taoism</h3>';
echo '<p>Philosophical Taoism (Daojia) — the tradition of Laozi and Zhuangzi — focuses on aligning with the Tao through wisdom, simplicity, and non-action. Religious Taoism (Daojiao) — emerging from the 2nd century CE — developed a rich tradition of ritual, priesthood, deity worship, alchemy (internal and external), immortality seeking, and community practice. These two streams are distinct but related.</p>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Meditation</strong> — various forms of sitting and moving meditation to align with the Tao</li>';
echo '<li><strong>Qigong and Tai Chi</strong> — movement practices cultivating qi (vital energy) in harmony with the Tao</li>';
echo '<li><strong>Internal Alchemy (Neidan)</strong> — practices transforming the body\'s energies to achieve immortality or spiritual refinement</li>';
echo '<li><strong>Feng Shui</strong> — arranging spaces in harmony with the flow of qi</li>';
echo '<li><strong>Ritual</strong> — elaborate priestly rituals in religious Taoism for healing, protection, and cosmic renewal</li>';
echo '</ul>';

// SHINTO
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#9b2c2c;">⊕ Shinto</h2>';
echo '<p><strong>Founded:</strong> Indigenous, c. 700 BCE | <strong>Origin:</strong> Japan | <strong>Followers:</strong> ~3-4 million (formal); widespread cultural practice</p>';
echo '<h3>Origin</h3>';
echo '<p>Shinto ("Way of the Spirits/Gods") is Japan\'s indigenous religion — a tradition without a founder, without a fixed canon of sacred texts, and without a systematic theology. It emerged from ancient Japanese animism and nature veneration, was given form and name in the 8th century CE (partly in response to Buddhism\'s arrival from Korea and China), and has been inseparable from Japanese cultural and political identity ever since. State Shinto — the government\'s use of Shinto to promote Japanese nationalism and imperialism — was dismantled after World War II.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Kami</strong> — spirits or divine forces that inhabit natural phenomena, ancestors, and places. Mountains, rivers, trees, rocks, the wind — all can be kami. There are said to be 8 million kami (yaoyorozu no kami — "eight million" meaning "innumerable").</li>';
echo '<li><strong>Musubi</strong> — the creative and harmonizing power of kami; the force of growth and union.</li>';
echo '<li><strong>Makoto</strong> — sincerity and purity of heart as the essential quality for right relationship with kami.</li>';
echo '<li><strong>Purity and Pollution (Kegare)</strong> — ritual purity is essential. Death, blood, and certain acts create pollution (kegare) requiring purification (harae/misogi).</li>';
echo '<li><strong>This-worldly focus</strong> — Shinto has little concern with afterlife doctrine. The focus is on this life: health, fertility, family, community, and harmony with nature and kami.</li>';
echo '</ul>';
echo '<h3>Major Kami</h3>';
echo '<ul>';
echo '<li><strong>Amaterasu</strong> — the sun goddess; highest deity; ancestress of the imperial family</li>';
echo '<li><strong>Susanoo</strong> — storm god; Amaterasu\'s brother</li>';
echo '<li><strong>Izanagi and Izanami</strong> — the divine couple who created the Japanese islands and gave birth to the kami</li>';
echo '<li><strong>Inari</strong> — god of rice, agriculture, foxes, and industry; one of the most widely worshipped kami</li>';
echo '<li><strong>Raijin and Fujin</strong> — thunder and wind gods</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>Kojiki</strong> (712 CE) — "Record of Ancient Matters" — myths of creation, the kami, and early Japanese history</li>';
echo '<li><strong>Nihon Shoki</strong> (720 CE) — "Chronicles of Japan" — similar content, compiled for official purposes</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Shrine worship (Jinja)</strong> — visiting shrines to honor kami; washing hands at the temizuya (purification fountain), bowing, clapping twice, praying</li>';
echo '<li><strong>Matsuri</strong> — festivals honoring kami; processions carrying the divine portable shrine (mikoshi)</li>';
echo '<li><strong>Harae</strong> — purification rituals; waving a haraegushi (sacred wand) over worshippers</li>';
echo '<li><strong>Misogi</strong> — water purification</li>';
echo '<li><strong>Ema</strong> — wooden votive plaques on which wishes are written and left at shrines</li>';
echo '<li><strong>Omamori</strong> — protective charms obtained at shrines</li>';
echo '<li><strong>Life events</strong> — births and marriages traditionally marked Shinto; funerals typically Buddhist in Japan</li>';
echo '</ul>';

// ZOROASTRIANISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#553c9a;">⊕ Zoroastrianism</h2>';
echo '<p><strong>Founded:</strong> c. 1500–600 BCE | <strong>Founder:</strong> Zarathustra (Zoroaster) | <strong>Origin:</strong> Greater Iran/Central Asia | <strong>Followers:</strong> ~200,000 | <strong>Status:</strong> Living (endangered)</p>';
echo '<h3>The Founder</h3>';
echo '<p>Zarathustra (Greek: Zoroaster) was an ancient Iranian prophet whose dates are disputed — ranging from 1700 BCE to 600 BCE. He received a vision of Ahura Mazda (the "Wise Lord") and began preaching a radical monotheistic reform of the existing Iranian polytheism. His teachings survive in the Gathas — 17 hymns preserved in the Avesta — believed to be his own composition. Zarathustra is considered one of the most influential religious thinkers in history, and Zoroastrianism is believed to have significantly influenced Judaism, Christianity, and Islam through its concepts of heaven, hell, final judgment, angels, and the cosmic struggle between good and evil.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Ahura Mazda</strong> — "Wise Lord" — the one supreme God, creator of all that is good, truth, and light. The central object of Zoroastrian worship.</li>';
echo '<li><strong>Angra Mainyu / Ahriman</strong> — the evil spirit, opponent of Ahura Mazda, source of all that is bad, false, and dark. Unlike the devil of Abrahamic religions, Angra Mainyu is a genuinely equal opposing force (in some interpretations), though destined to be defeated.</li>';
echo '<li><strong>Cosmic Dualism</strong> — the universe is a battleground between Spenta Mainyu (Holy Spirit/Good Mind) and Angra Mainyu (Destructive Spirit). Humans must choose their side.</li>';
echo '<li><strong>Asha</strong> — truth, righteousness, cosmic order. The fundamental principle of good. Opposed by Druj (the lie, falsehood).</li>';
echo '<li><strong>Free Will</strong> — Zoroastrianism places extraordinary emphasis on human free will. Each person must choose between asha and druj; this choice has cosmic significance.</li>';
echo '<li><strong>The Three Pillars</strong> — Humata, Hukhta, Hvarshta: Good Thoughts, Good Words, Good Deeds.</li>';
echo '<li><strong>Frashokereti</strong> — the final renovation of the world. At the end of time, Ahura Mazda will defeat Angra Mainyu, the dead will be resurrected, all souls will be purified, and the world will be restored to perfection.</li>';
echo '</ul>';
echo '<h3>Sacred Text</h3>';
echo '<p><strong>The Avesta</strong> — the Zoroastrian scripture. Contains the Gathas (hymns of Zarathustra), the Yasna (liturgical texts), the Yashts (hymns to individual divine beings), and the Vendidad (purity laws). Only about one quarter of the original Avesta survives.</p>';
echo '<h3>Legacy and Influence</h3>';
echo '<p>Zoroastrianism was the state religion of three great Persian empires (Achaemenid, Parthian, Sassanid) and shaped ancient Iranian civilization for over a thousand years. Its concepts — heaven and hell, final judgment, resurrection of the dead, a messiah figure (Saoshyant), the cosmic battle between good and evil — are widely believed to have entered Judaism during the Babylonian exile and from there influenced Christianity and Islam. In this sense, Zoroastrianism may be the most influential religion most people have never heard of.</p>';
echo '<h3>The Parsis</h3>';
echo '<p>When Arab Muslim armies conquered Persia in the 7th century, many Zoroastrians fled to India, settling in Gujarat. Their descendants — the Parsis — are today the most prominent Zoroastrian community. Despite tiny numbers (~70,000 in India), they have produced extraordinary figures including Freddie Mercury, Zubin Mehta, and the Tata family.</p>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Sacred fire</strong> — the fire temple (Atash Behram) houses a sacred fire that must never be extinguished; it represents Ahura Mazda\'s light</li>';
echo '<li><strong>Prayer (Yasna)</strong> — five daily prayers, performed facing a fire or the sun</li>';
echo '<li><strong>Navjote</strong> — initiation ceremony; the Sudreh (sacred undershirt) and Kusti (sacred cord) are invested</li>';
echo '<li><strong>Sky burial (Dakhma)</strong> — the dead are placed on towers of silence for vultures to consume; fire and earth must not be polluted by death</li>';
echo '<li><strong>No conversion</strong> — traditionally, Zoroastrianism does not accept converts; one must be born into a Zoroastrian family</li>';
echo '</ul>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">Full Map</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/topics/">Ancient Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/abrahamic/">Abrahamic Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/african/">African Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/modern/">Modern Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/people/">Founders</a>';
echo '</div></div>';
