<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Modern and new religious movements — Baháʼí, Eckankar, Rastafari, Mormonism, Cao Dai, Spiritism, Wicca, and others.</p>';

// BAHAI
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2b6cb0;">⊕ The Baháʼí Faith</h2>';
echo '<p><strong>Founded:</strong> 1844 CE | <strong>Founders:</strong> The Báb (1819–1850), Baháʼu\'lláh (1817–1892) | <strong>Origin:</strong> Persia (Iran) | <strong>Followers:</strong> ~8 million | <strong>Status:</strong> Living</p>';
echo '<h3>Origin</h3>';
echo '<p>The Baháʼí Faith emerged from 19th-century Persia. In 1844, Siyyid ʻAlí-Muḥammad of Shiraz declared himself the Báb ("the Gate") — a forerunner of a promised one greater than himself. He attracted thousands of followers in Iran before being executed by firing squad in 1850. One of his followers, Mírzá Ḥusayn-ʻAlí Núrí — known as Baháʼu\'lláh ("Glory of God") — declared in 1863 that he was the one the Báb had foretold. Baháʼu\'lláh spent his life as a prisoner and exile, writing the core texts of the Baháʼí Faith. He died in 1892 under Ottoman house arrest in Akka (modern Israel), where the Baháʼí World Centre is now located.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>The Oneness of God</strong> — one unknowable God is the source of all creation; all divine names and attributes refer to this one Being.</li>';
echo '<li><strong>The Oneness of Religion</strong> — all major world religions are successive chapters of one divine revelation. Abraham, Moses, Krishna, Zoroaster, Buddha, Jesus, Muhammad, the Báb, and Baháʼu\'lláh are all "Manifestations of God" — divine educators sent progressively to guide humanity.</li>';
echo '<li><strong>The Oneness of Humanity</strong> — all human beings are members of one family; racism, nationalism, and religious prejudice are condemned; world peace and global governance are goals.</li>';
echo '<li><strong>Progressive Revelation</strong> — divine guidance evolves in response to humanity\'s growing capacity. Each Manifestation brings teachings appropriate to their era; Baháʼu\'lláh\'s revelation is the most recent and suited to the current age.</li>';
echo '<li><strong>Equality of Men and Women</strong> — full gender equality is a Baháʼí principle.</li>';
echo '<li><strong>Harmony of Science and Religion</strong> — religion and science are two complementary systems of knowledge; they cannot contradict.</li>';
echo '<li><strong>Universal Education</strong> — every human being should be educated.</li>';
echo '<li><strong>Independent Investigation of Truth</strong> — each person must seek truth independently, not follow tradition blindly.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Kitáb-i-Aqdas</strong> ("Most Holy Book") — Baháʼu\'lláh\'s book of laws</li>';
echo '<li><strong>The Hidden Words</strong> — meditations on ethics and the spiritual life</li>';
echo '<li><strong>The Seven Valleys</strong> — mystical work on the journey of the soul</li>';
echo '<li><strong>The Writings of the Báb</strong></li>';
echo '<li><strong>The Writings of ʻAbdu\'l-Bahá</strong> — Baháʼu\'lláh\'s son, appointed interpreter of the Faith</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Prayer</strong> — one of three obligatory daily prayers must be recited</li>';
echo '<li><strong>Fasting</strong> — 19 days of fasting (March 2–20) before the Baháʼí New Year (Naw-Rúz)</li>';
echo '<li><strong>No clergy</strong> — the Faith has no priesthood; communities are governed by elected Houses of Justice</li>';
echo '<li><strong>Devotional gatherings</strong> — open to all; prayer, music, and study</li>';
echo '<li><strong>Service</strong> — community service as a form of worship</li>';
echo '</ul>';
echo '<p><em>Note: Baháʼís face severe persecution in Iran, where the Faith originated — banned, imprisoned, and executed for their beliefs by the Islamic Republic.</em></p>';

// ECKANKAR
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Eckankar</h2>';
echo '<p><strong>Founded:</strong> 1965 CE | <strong>Founder:</strong> Paul Twitchell (1908–1971) | <strong>Origin:</strong> USA (Las Vegas, Nevada) | <strong>Followers:</strong> ~50,000 | <strong>Status:</strong> Living</p>';
echo '<h3>Origin</h3>';
echo '<p>Eckankar was founded in October 1965 by Paul Twitchell, an American writer with a background in Scientology and Kirpal Singh\'s Surat Shabd Yoga (the "sound current" tradition of North India). Twitchell claimed to have been taught by a succession of Eck Masters and synthesized these influences into a new teaching he called "the Ancient Science of Soul Travel." After Twitchell\'s death in 1971, the organization passed to Darwin Gross and then to Harold Klemp, who has led it since 1981 as the "Mahanta, the Living ECK Master." Headquarters are in Chanhassen, Minnesota.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>ECK (Audible Life Stream)</strong> — the divine current of life and consciousness that flows from God through all creation. ECK manifests as both Sound and Light. Connecting with ECK is the path to God-Realization.</li>';
echo '<li><strong>Soul</strong> — each individual is Soul — a spark of God, eternal and indestructible. Soul\'s purpose is to gain spiritual experience and wisdom through multiple lifetimes.</li>';
echo '<li><strong>The Mahanta</strong> — the current Living ECK Master; believed to be the highest spiritual consciousness on earth; serves as inner guide and outer teacher.</li>';
echo '<li><strong>Soul Travel</strong> — the ability to consciously leave the physical body and travel in inner spiritual worlds (planes of existence); a central spiritual practice of Eckankar.</li>';
echo '<li><strong>The Shariyat-Ki-Sugmad</strong> — the sacred scripture of Eckankar, believed to exist on the inner planes and partially transcribed by ECK Masters.</li>';
echo '<li><strong>Reincarnation and Karma</strong> — accepted; Soul incarnates repeatedly until it achieves liberation.</li>';
echo '<li><strong>Spiritual planes</strong> — existence is organized in multiple planes above the physical; Soul ascends through these planes toward union with God (SUGMAD).</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>HU</strong> — the sacred sound of God; singing HU (pronounced "hue") is the central spiritual practice; said to be a love song to God</li>';
echo '<li><strong>Spiritual exercises</strong> — daily 20-minute contemplative practice for Soul Travel and inner experiences</li>';
echo '<li><strong>Dreams</strong> — given great importance as a form of spiritual experience and guidance from the Mahanta</li>';
echo '<li><strong>Initiations</strong> — a series of initiations marking spiritual progress through planes of consciousness</li>';
echo '</ul>';

// RASTAFARI
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Rastafari</h2>';
echo '<p><strong>Founded:</strong> 1930s | <strong>Origin:</strong> Jamaica | <strong>Key Figure:</strong> Haile Selassie I (1892–1975) | <strong>Followers:</strong> ~1 million | <strong>Status:</strong> Living</p>';
echo '<h3>Origin</h3>';
echo '<p>Rastafari emerged in Jamaica in the 1930s among poor Black Jamaicans drawing on the prophetic Black nationalism of Marcus Garvey ("Look to Africa for the crowning of a Black King"). When Ras Tafari Makonnen was crowned Emperor Haile Selassie I of Ethiopia in 1930 — the only African monarch to resist European colonization — early Rastafarians proclaimed him the fulfillment of biblical prophecy: the returned Messiah, the Lion of the Tribe of Judah. Key early figures included Leonard Howell, Joseph Hibbert, and Archibald Dunkley.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Haile Selassie as God (Jah)</strong> — Haile Selassie I is the living God, the returned Jesus Christ (Yeshua), and the fulfillment of Revelation 5:5. This is the central and most distinctive Rastafari belief. (Haile Selassie himself was a devout Ethiopian Orthodox Christian who never claimed divinity.)</li>';
echo '<li><strong>Africa as Zion</strong> — Ethiopia/Africa is the promised land; the African diaspora lives in Babylon (the oppressive system of Western civilization); repatriation to Africa is a spiritual and physical goal.</li>';
echo '<li><strong>Babylon</strong> — the corrupt, oppressive system of white-dominated Western society and its institutions; to be resisted and ultimately destroyed.</li>';
echo '<li><strong>I and I</strong> — the divine is within each person; "I and I" replaces "me" to express the unity between the individual, God, and the community.</li>';
echo '<li><strong>The Bible</strong> — read through an Afrocentric lens; the "true" Israelites are Black Africans whose history has been whitewashed.</li>';
echo '<li><strong>Livity</strong> — a righteous way of life; natural, ital (vital/natural) food, living in harmony with nature.</li>';
echo '</ul>';
echo '<h3>Major Mansions (Branches)</h3>';
echo '<ul>';
echo '<li><strong>Nyahbinghi</strong> — oldest mansion; militant; repatriation emphasis; the Groundation celebration</li>';
echo '<li><strong>Bobo Ashanti</strong> — formal religious order; distinctive white turbans; strict livity</li>';
echo '<li><strong>Twelve Tribes of Israel</strong> — founded 1968; more inclusive; each member belongs to one of the twelve biblical tribes determined by birth month</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Cannabis (Ganja)</strong> — sacramental herb; used in reasoning sessions for spiritual insight; cited in Psalms 104:14</li>';
echo '<li><strong>Dreadlocks</strong> — uncut hair; Nazarite vow (Numbers 6); connection to nature; the Lion\'s mane</li>';
echo '<li><strong>Ital food</strong> — natural, unprocessed food; often vegan; no salt, no pork</li>';
echo '<li><strong>Reggae music</strong> — spiritual expression; Bob Marley was the most important ambassador of Rastafari globally</li>';
echo '<li><strong>Reasoning</strong> — community gathering for discussion, prayer, and cannabis</li>';
echo '<li><strong>Colors</strong> — red (blood of martyrs), gold (wealth of Africa), green (vegetation of Ethiopia), black (African people)</li>';
echo '</ul>';

// CAO DAI
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#9b2c2c;">⊕ Cao Dai</h2>';
echo '<p><strong>Founded:</strong> 1926 CE | <strong>Founder:</strong> Ngô Văn Chiêu (initial) / Lê Văn Trung (organized) | <strong>Origin:</strong> Vietnam (Tây Ninh Province) | <strong>Followers:</strong> ~4-6 million</p>';
echo '<h3>Origin</h3>';
echo '<p>Caodaism (Đạo Cao Đài — "Way of the High Tower/Palace") was founded in Vietnam in 1926 following a series of séances in which the Supreme Being (Cao Đài) communicated through spirit mediums to reveal a new universal religion. It was formally established in Tây Ninh Province, where the Holy See (Great Divine Temple) was built. Cao Dai presented itself as the "Third Alliance Between God and Humanity" — synthesizing all previous religions into a universal faith.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Cao Đài</strong> — the Supreme Being, the "High Tower" — the one God beyond all names and forms; the divine eye (the Left Eye of God) is Cao Dai\'s primary symbol.</li>';
echo '<li><strong>Universal Religion</strong> — Cao Dai teaches that all religions worship the same God and that their differences are products of time, culture, and human limitation. The divine eye is depicted surrounded by clouds, watching over all humanity.</li>';
echo '<li><strong>Three Teachings + Two Religions</strong> — Cao Dai synthesizes the three Chinese teachings (Confucianism, Taoism, Buddhism) with Christianity and Islam, plus indigenous Vietnamese spirit worship.</li>';
echo '<li><strong>Divine Hierarchy</strong> — an elaborate spiritual hierarchy including Cao Đài at the top, followed by the Buddha, Laozi, Confucius, Jesus, and various saints who have been "canonized" — including Victor Hugo, Sun Yat-sen, and Joan of Arc (revealed through séances).</li>';
echo '<li><strong>Karma and Reincarnation</strong> — accepted from Buddhist tradition; moral life improves future rebirths.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Four daily prayers</strong> — at 6am, noon, 6pm, and midnight; facing the Divine Eye</li>';
echo '<li><strong>Vegetarianism</strong> — required on certain days (6, 10, 15, 18, 23, 26, 28 of lunar month)</li>';
echo '<li><strong>Spirit communication (Cơ Bút)</strong> — messages from the divine received through a planchette or spirit medium; integral to the religion\'s founding and ongoing governance</li>';
echo '<li><strong>The Cao Dai Temple (Tòa Thánh)</strong> — a remarkable building in Tây Ninh combining Vietnamese, Chinese, French colonial, and religious architectural elements; among the most visually striking religious buildings in Asia</li>';
echo '</ul>';

// SPIRITISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#553c9a;">⊕ Spiritism (Kardecism)</h2>';
echo '<p><strong>Founded:</strong> 1857 CE | <strong>Founder:</strong> Hippolyte Léon Denizard Rivail (Allan Kardec) | <strong>Origin:</strong> France | <strong>Followers:</strong> ~15 million (primarily Brazil)</p>';
echo '<h3>Origin</h3>';
echo '<p>Allan Kardec (1804–1869) was a French educator and investigator who, in 1854, began attending séances and became convinced that the spirits of the dead were genuinely communicating. He compiled questions and answers received through various mediums into "The Spirits\' Book" (1857) — a systematic philosophy he called Spiritism. Kardec\'s work was largely ignored in France but took root in Brazil, where it combined with Afro-Brazilian traditions (Umbanda) and became one of the most important religious movements in South America.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Spirits exist</strong> — the souls of the dead survive physical death and can communicate with the living through mediums.</li>';
echo '<li><strong>Reincarnation</strong> — souls reincarnate multiple times, progressively improving morally and intellectually. Unlike most reincarnation doctrines, Kardecism holds that souls can incarnate on other planets as well as earth.</li>';
echo '<li><strong>Moral progress</strong> — the purpose of reincarnation is moral and spiritual evolution. Suffering is educational, not punitive.</li>';
echo '<li><strong>Charity</strong> — "Outside of charity, there is no salvation" — Kardec\'s central ethical teaching. Spiritism emphasizes healing, social service, and mediumship as charitable acts.</li>';
echo '<li><strong>God</strong> — Spiritism accepts one God; Jesus is the model of moral perfection; the Gospels are studied and revered.</li>';
echo '<li><strong>No rituals, no sacraments, no clergy</strong> — Spiritism is deliberately non-liturgical. Meetings involve reading, discussion, and mediumship.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Spirits\' Book</strong> (1857) — foundational text; 1,019 questions and answers</li>';
echo '<li><strong>The Mediums\' Book</strong> (1861)</li>';
echo '<li><strong>The Gospel According to Spiritism</strong> (1864) — moral teachings of Jesus interpreted through Spiritist lens</li>';
echo '<li><strong>Heaven and Hell</strong> (1865)</li>';
echo '<li><strong>Genesis</strong> (1868)</li>';
echo '</ul>';

// WICCA
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2d6a1f;">⊕ Wicca / Neo-Paganism</h2>';
echo '<p><strong>Founded:</strong> 1954 CE | <strong>Founder:</strong> Gerald Gardner (1884–1964) | <strong>Origin:</strong> England | <strong>Followers:</strong> ~1-3 million | <strong>Status:</strong> Living and growing</p>';
echo '<h3>Origin</h3>';
echo '<p>Wicca was publicly founded by Gerald Gardner, a British civil servant and amateur anthropologist, who claimed to have been initiated into a surviving witch cult ("the Craft") in the New Forest, Hampshire, in 1939. He published <em>Witchcraft Today</em> in 1954, presenting Wicca as a revival of pre-Christian European religion. The tradition was further developed by Doreen Valiente, who rewrote much of Gardner\'s ritual material, and has since diversified enormously — Alexandrian, Dianic, Eclectic, and many other traditions exist. Wicca is among the fastest-growing religions in the Western world.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>The Goddess and the God</strong> — a dual divine: the Goddess (lunar, feminine, triple-aspected as Maiden/Mother/Crone) and the God (solar, masculine, horned, associated with animals and the hunt). Both are aspects of a greater divine unity.</li>';
echo '<li><strong>The Wiccan Rede</strong> — "An it harm none, do what ye will." The primary ethical principle: total personal freedom except where harm to others would result.</li>';
echo '<li><strong>The Threefold Law</strong> — whatever energy you send out returns to you three times over; a karmic principle governing magical practice.</li>';
echo '<li><strong>Magic</strong> — the use of focused will and ritual to effect change in the world; considered a natural force, not supernatural. "Magic is the art of changing consciousness at will" (Dion Fortune).</li>';
echo '<li><strong>The Elements</strong> — Earth, Air, Fire, Water (and Spirit/Akasha) as sacred forces underlying reality; invoked in ritual.</li>';
echo '<li><strong>Sacred immanence</strong> — the divine is present in nature; the natural world is sacred; ecology and environmental ethics are spiritual concerns.</li>';
echo '<li><strong>Afterlife</strong> — the Summerland (a peaceful resting place between incarnations); most Wiccans accept reincarnation.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>The Wheel of the Year</strong> — 8 seasonal sabbats: Samhain (Oct 31), Yule (Dec 21), Imbolc (Feb 2), Ostara (Mar 21), Beltane (May 1), Litha (Jun 21), Lughnasadh (Aug 1), Mabon (Sep 21)</li>';
echo '<li><strong>Esbats</strong> — full moon (and sometimes new moon) ritual gatherings</li>';
echo '<li><strong>The Circle</strong> — casting a sacred circle to create ritual space; calling the quarters (north/earth, east/air, south/fire, west/water)</li>';
echo '<li><strong>Spellwork</strong> — focused intention and ritual action to manifest desired outcomes</li>';
echo '<li><strong>The Book of Shadows</strong> — each practitioner\'s personal ritual journal</li>';
echo '<li><strong>Covens and Solitary practice</strong> — Wicca can be practiced in groups (covens, typically 13) or alone</li>';
echo '</ul>';

// MORMONISM
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#1a365d;">⊕ Mormonism (The Church of Jesus Christ of Latter-day Saints)</h2>';
echo '<p><strong>Founded:</strong> 1830 CE | <strong>Founder:</strong> Joseph Smith Jr. (1805–1844) | <strong>Origin:</strong> Palmyra, New York, USA | <strong>Followers:</strong> ~17 million | <strong>Status:</strong> Living</p>';
echo '<h3>The Founder</h3>';
echo '<p>Joseph Smith Jr. claimed a series of divine visions beginning in 1820 when (at age 14) God the Father and Jesus Christ appeared to him in a grove of trees near his home (the "First Vision"). In 1823 the angel Moroni directed him to golden plates buried on a hill called Cumorah. Smith translated these plates using two seer stones and published the result in 1830 as the Book of Mormon. He organized the Church of Christ (later renamed) in April 1830. He was murdered by a mob in Carthage, Illinois, in 1844. The majority of Latter-day Saints followed Brigham Young to Utah; other groups followed different successors.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>The Godhead</strong> — God the Father (Heavenly Father), Jesus Christ, and the Holy Ghost are three separate beings, not a Trinity. God the Father has a physical body of flesh and bones.</li>';
echo '<li><strong>Continuing Revelation</strong> — God continues to reveal his will through living prophets; the President of the Church is a prophet, seer, and revelator.</li>';
echo '<li><strong>The Book of Mormon</strong> — "Another Testament of Jesus Christ"; a record of ancient peoples in the Americas who Christ visited after his resurrection.</li>';
echo '<li><strong>The Plan of Salvation</strong> — existence before birth (pre-mortal life), mortal life (a test), and three degrees of glory after death (Celestial, Terrestrial, Telestial kingdoms).</li>';
echo '<li><strong>Eternal Families</strong> — families sealed in the temple can be together forever; the most emotionally powerful LDS doctrine.</li>';
echo '<li><strong>Exaltation</strong> — the highest Celestial Kingdom offers the possibility of becoming like God; "As God is, man may become."</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Bible</strong> (King James Version, "as far as it is translated correctly")</li>';
echo '<li><strong>The Book of Mormon</strong> — scripture</li>';
echo '<li><strong>The Doctrine and Covenants</strong> — modern revelations to Joseph Smith and successors</li>';
echo '<li><strong>The Pearl of Great Price</strong> — additional writings of Joseph Smith</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Temple worship</strong> — sacred ceremonies including baptism for the dead, marriage sealings, and endowments; temples are restricted to members with "temple recommends"</li>';
echo '<li><strong>Missionary service</strong> — typically 2 years for young men, 18 months for young women; LDS missionaries (the distinctive white-shirted pairs) are among the most visible symbols of the Church</li>';
echo '<li><strong>Word of Wisdom</strong> — health code: no coffee, tea, alcohol, or tobacco</li>';
echo '<li><strong>Tithing</strong> — 10% of income given to the Church</li>';
echo '<li><strong>Family Home Evening</strong> — Monday evenings reserved for family religious instruction</li>';
echo '</ul>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:28px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">Full Map</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/topics/">Ancient Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/eastern/">Eastern Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/abrahamic/">Abrahamic Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/african/">African Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/people/">Founders & Teachers</a>';
echo '</div></div>';
