<?php
declare(strict_types=1);
echo '<div class="mk-prose">';
echo '<p class="mk-muted" style="margin-top:0;">Ancient religions in depth — founders, beliefs, doctrines, and practices.</p>';

// KEMET
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#b7791f;">⊕ Kemet — Ancient Egyptian Religion</h2>';
echo '<p><strong>Region:</strong> Nile Valley, Egypt | <strong>Period:</strong> c. 3100 BCE – 400 CE | <strong>Status:</strong> Extinct (revived as Kemetism)</p>';
echo '<h3>Origin and Founder</h3>';
echo '<p>Kemet (the ancient Egyptian name for Egypt, meaning "the Black Land") had no single founder. Its religious tradition emerged organically with the unification of Upper and Lower Egypt under Narmer (c. 3100 BCE) and evolved continuously for over three thousand years. It is one of the longest-surviving religious traditions in human history.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Ma\'at</strong> — the cosmic principle of truth, justice, balance, and order. All creation depends on Ma\'at being maintained. Pharaoh\'s primary duty was to uphold Ma\'at.</li>';
echo '<li><strong>The Soul</strong> — Egyptians believed humans had multiple soul components: the Ka (life force), the Ba (personality/essence that flies after death), the Akh (the transfigured spirit after successful judgment), the Ib (heart as seat of intelligence), and the Ren (name — to speak someone\'s name was to make them live).</li>';
echo '<li><strong>Afterlife</strong> — death was a transition, not an end. The deceased faced judgment in the Hall of Two Truths where the heart was weighed against the feather of Ma\'at. A heart lighter than the feather passed to the Field of Reeds (paradise); a heavier heart was devoured by Ammit.</li>';
echo '<li><strong>Divine Kingship</strong> — Pharaoh was the earthly embodiment of Horus during life and Osiris in death, serving as intermediary between gods and humans.</li>';
echo '</ul>';
echo '<h3>Major Deities</h3>';
echo '<ul>';
echo '<li><strong>Ra / Amun-Ra</strong> — the sun god, king of gods, creator. The daily solar cycle represented his journey through the sky (day) and the underworld (night).</li>';
echo '<li><strong>Osiris</strong> — god of death, resurrection, and the afterlife. Murdered by Set, resurrected by Isis, he became ruler of the dead and symbol of eternal life.</li>';
echo '<li><strong>Isis</strong> — goddess of magic, healing, and motherhood. The most widely worshipped Egyptian deity, whose cult spread throughout the Roman Empire.</li>';
echo '<li><strong>Horus</strong> — sky god, divine kingship. Son of Osiris and Isis, his conflict with Set represents the eternal struggle between order and chaos.</li>';
echo '<li><strong>Thoth</strong> — god of wisdom, writing, and the moon. Scribe of the gods, inventor of hieroglyphs, keeper of divine records.</li>';
echo '<li><strong>Anubis</strong> — god of embalming and guide of the dead. Jackal-headed, he conducted souls to the Hall of Judgment.</li>';
echo '<li><strong>Set</strong> — god of chaos, storms, and the desert. Murderer of Osiris, yet also protector of Ra\'s solar barque against Apep (chaos serpent).</li>';
echo '<li><strong>Nut</strong> — goddess of the sky and stars. She swallowed the sun each evening and gave birth to it each morning.</li>';
echo '<li><strong>Geb</strong> — god of the earth, Nut\'s consort. His laughter caused earthquakes.</li>';
echo '<li><strong>Ptah</strong> — creator god of Memphis. Created the world through thought and speech.</li>';
echo '<li><strong>Sekhmet</strong> — lion-headed goddess of war and healing.</li>';
echo '<li><strong>Bastet</strong> — cat goddess of home, fertility, and protection.</li>';
echo '<li><strong>Ma\'at</strong> — goddess of truth and cosmic order. Her feather balanced against the heart.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Book of the Dead</strong> (Pert em Hru — "Coming Forth by Day") — spells and instructions to guide the deceased through the afterlife</li>';
echo '<li><strong>The Pyramid Texts</strong> (c. 2400 BCE) — oldest religious texts in the world, inscribed on pyramid walls</li>';
echo '<li><strong>The Coffin Texts</strong> — democratized versions of Pyramid Texts for non-royal burials</li>';
echo '<li><strong>The Amduat</strong> — describes the sun god\'s journey through the twelve hours of the night</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Mummification</strong> — preservation of the body to allow the Ba to return and the Akh to be realized</li>';
echo '<li><strong>Temple worship</strong> — daily rituals performed by priests to feed, clothe, and honor the deity\'s statue (believed to house the divine essence)</li>';
echo '<li><strong>Festivals</strong> — the Opet Festival, Wepet Renpet (New Year), Festival of the Valley — occasions for public celebration and procession</li>';
echo '<li><strong>Oracles</strong> — deity statues were carried in processions; their movements answered questions from the crowd</li>';
echo '<li><strong>Magic (Heka)</strong> — integral to Egyptian religion. Spells, amulets, and rituals accessed divine power for healing and protection</li>';
echo '</ul>';

// MESOPOTAMIAN
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Mesopotamian Religions — Sumerian, Babylonian, Akkadian</h2>';
echo '<p><strong>Region:</strong> Tigris-Euphrates valley (modern Iraq/Syria) | <strong>Period:</strong> c. 3500 – 539 BCE | <strong>Status:</strong> Extinct</p>';
echo '<h3>Origin</h3>';
echo '<p>The world\'s oldest known written religious tradition. The Sumerians of southern Mesopotamia developed city-states each with a patron deity, creating humanity\'s first recorded theology, cosmology, and mythology. Their traditions were absorbed by the Akkadians, Babylonians, and Assyrians, evolving but maintaining core continuities.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Creation</strong> — the Enuma Elish (Babylonian creation epic) describes the cosmos emerging from primordial waters. The god Marduk defeated the chaos dragon Tiamat, splitting her body to create heaven and earth.</li>';
echo '<li><strong>Human Purpose</strong> — humans were created from clay mixed with divine blood to serve the gods — to feed them through sacrifice, build their temples, and maintain cosmic order.</li>';
echo '<li><strong>Afterlife</strong> — grim. The dead descended to Kur (the underworld) — a dark, dusty realm of shadows with no distinction between righteous and wicked. Mesopotamian religion offered little comfort about death.</li>';
echo '<li><strong>Fate (Namtar)</strong> — destinies were written on Tablets of Fate, held by the gods. Much of religious practice was aimed at learning and potentially influencing one\'s fate.</li>';
echo '</ul>';
echo '<h3>Major Deities</h3>';
echo '<ul>';
echo '<li><strong>An/Anu</strong> — sky god, father of gods, supreme authority</li>';
echo '<li><strong>Enlil</strong> — god of wind and storms, lord of earth and air, decreed fate of humanity</li>';
echo '<li><strong>Enki/Ea</strong> — god of wisdom, water, crafts, and magic. Friend of humanity, warned Ziusudra/Utnapishtim of the flood</li>';
echo '<li><strong>Inanna/Ishtar</strong> — goddess of love, war, and fertility. Queen of Heaven. Her descent to the underworld is one of the oldest myths.</li>';
echo '<li><strong>Nanna/Sin</strong> — moon god</li>';
echo '<li><strong>Utu/Shamash</strong> — sun god, god of justice</li>';
echo '<li><strong>Marduk</strong> — patron of Babylon, rose to supreme position in Babylonian theology</li>';
echo '<li><strong>Nergal</strong> — god of death and the underworld</li>';
echo '<li><strong>Ereshkigal</strong> — queen of the underworld</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Epic of Gilgamesh</strong> — the world\'s oldest epic poem. A king\'s search for immortality, containing a flood narrative predating the biblical account.</li>';
echo '<li><strong>Enuma Elish</strong> — Babylonian creation epic</li>';
echo '<li><strong>The Descent of Inanna</strong> — goddess descends to underworld, stripped of power, dies, resurrected</li>';
echo '<li><strong>Atrahasis</strong> — creation of humans and the great flood</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Ziggurat temples</strong> — stepped pyramidal temple platforms housing the deity\'s sanctuary at the top</li>';
echo '<li><strong>Daily temple ritual</strong> — priests fed, clothed, and entertained divine statues</li>';
echo '<li><strong>Divination</strong> — reading omens from animal entrails (extispicy), astronomy, oil patterns on water</li>';
echo '<li><strong>Sacred marriage (Hieros Gamos)</strong> — ritual union between king and priestess representing Inanna</li>';
echo '<li><strong>Sacrifice</strong> — animal and food offerings to maintain divine favor</li>';
echo '</ul>';

// MAYA
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2b6cb0;">⊕ Maya Religion</h2>';
echo '<p><strong>Region:</strong> Mesoamerica (southern Mexico, Guatemala, Belize, Honduras) | <strong>Period:</strong> c. 2000 BCE – present (in modified form) | <strong>Status:</strong> Partially surviving</p>';
echo '<h3>Origin</h3>';
echo '<p>The Maya developed one of the most sophisticated civilizations of the ancient world, with advanced mathematics, astronomy, and writing. Their religion was inseparable from their calendar system — one of the most accurate ever developed — and from their understanding of cyclical time.</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Cyclical Time</strong> — the Maya conceived of time as cyclical, not linear. Multiple calendar systems ran simultaneously: the 365-day solar calendar (Haab), the 260-day ritual calendar (Tzolkín), and the Long Count calendar tracking vast cosmic cycles.</li>';
echo '<li><strong>Multiple Creations</strong> — the Popol Vuh describes multiple attempts by the gods to create humans. Clay people dissolved. Wood people were destroyed. Finally maize people — the current humanity — were created from corn.</li>';
echo '<li><strong>Blood Sacrifice</strong> — blood was the most potent sacred substance. Human sacrifice, auto-sacrifice (drawing one\'s own blood), and animal sacrifice maintained the cosmic order and fed the gods.</li>';
echo '<li><strong>The Underworld (Xibalba)</strong> — the Maya underworld had nine levels ruled by death gods. The Hero Twins\' defeat of the lords of Xibalba (in the Popol Vuh) was the mythological foundation for resurrection.</li>';
echo '</ul>';
echo '<h3>Major Deities</h3>';
echo '<ul>';
echo '<li><strong>Itzamna</strong> — supreme creator god, lord of the heavens, inventor of writing</li>';
echo '<li><strong>Ix Chel</strong> — moon goddess, goddess of medicine, weaving, and childbirth</li>';
echo '<li><strong>Kukulkan</strong> — feathered serpent deity (equivalent to Aztec Quetzalcoatl), god of wind and knowledge</li>';
echo '<li><strong>Chaac</strong> — rain god, essential for agriculture</li>';
echo '<li><strong>Ah Puch / Kisin</strong> — god of death, ruler of Xibalba</li>';
echo '<li><strong>Hunahpu and Xbalanque</strong> — the Hero Twins, central figures of the Popol Vuh</li>';
echo '<li><strong>The Bacabs</strong> — four gods supporting the corners of the sky</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>Popol Vuh</strong> — the K\'iche\' Maya creation narrative, written down in the 16th century from oral tradition</li>';
echo '<li><strong>Books of Chilam Balam</strong> — prophetic and historical texts</li>';
echo '<li><strong>Dresden, Madrid, Paris Codices</strong> — pre-Columbian Maya books (most were burned by Spanish missionaries)</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Human sacrifice</strong> — particularly at major calendrical events; decapitation, heart extraction</li>';
echo '<li><strong>Auto-sacrifice</strong> — rulers drew blood from tongue, ears, genitals to communicate with ancestors</li>';
echo '<li><strong>Ball game (Pok-a-tok)</strong> — ritual sport with cosmological significance; losers (or winners, debated) were sacrificed</li>';
echo '<li><strong>Astronomical observation</strong> — temples aligned with solar and stellar events; priests were astronomer-priests</li>';
echo '<li><strong>Shamanic practice</strong> — contact with spirit world through trance, plant medicines (peyote, mushrooms, balché)</li>';
echo '</ul>';

// INCA
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#744210;">⊕ Inca Religion</h2>';
echo '<p><strong>Region:</strong> Andean South America (Peru, Bolivia, Ecuador, Chile, Argentina) | <strong>Period:</strong> c. 1400 – 1533 CE | <strong>Status:</strong> Largely extinct, elements survive in Andean indigenous practice</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Inti (Sun God)</strong> — the supreme deity of the Inca state religion. The Sapa Inca (emperor) was the Son of Inti, divine intermediary between god and humanity.</li>';
echo '<li><strong>Pachamama</strong> — Earth Mother, goddess of fertility, earthquakes, and harvests. Pre-Inca in origin, absorbed into the Inca pantheon. Still actively worshipped in Andean communities today.</li>';
echo '<li><strong>Viracocha</strong> — creator god who made the world, the sun, moon, and humans before withdrawing. Associated with the primordial ocean.</li>';
echo '<li><strong>Huacas</strong> — sacred objects, places, and beings throughout the landscape. Mountains, rivers, springs, stones could all be huacas requiring propitiation.</li>';
echo '<li><strong>Ancestor veneration</strong> — mummified ancestors (mallquis) were treated as living members of the community, consulted, fed, and carried in processions.</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Capacocha</strong> — child sacrifice at major events (coronation, natural disasters). Children were chosen from elite families, treated as divine, sacrificed on mountain peaks.</li>';
echo '<li><strong>Ceque system</strong> — 41 imaginary lines radiating from Cuzco\'s Coricancha (Temple of the Sun), each containing huacas requiring specific ritual attention</li>';
echo '<li><strong>Coricancha</strong> — the greatest Inca temple, lined with gold, housing golden statues of deities and mummified emperors</li>';
echo '<li><strong>Divination</strong> — reading coca leaves, animal entrails, and the flight of birds</li>';
echo '<li><strong>Reciprocity (Ayni)</strong> — the fundamental Andean principle: humans give to the gods (sacrifice, labor, devotion) and receive in return (rain, harvest, protection)</li>';
echo '</ul>';

// NORSE
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#2d3748;">⊕ Norse / Germanic Religion</h2>';
echo '<p><strong>Region:</strong> Scandinavia, Iceland, Northern Europe | <strong>Period:</strong> c. 200 – 1100 CE | <strong>Status:</strong> Extinct (revived as Ásatrú/Heathenry)</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>Nine Worlds on Yggdrasil</strong> — the cosmos is an immense ash tree (Yggdrasil) connecting nine realms: Asgard (gods), Midgard (humans), Jotunheim (giants), Niflheim (ice/death), Muspelheim (fire), Vanaheim, Alfheim, Svartalfheim, Helheim.</li>';
echo '<li><strong>Fate (Wyrd)</strong> — the Norns (three female beings) weave the fate of gods and humans. Fate is fixed but honorable action matters regardless.</li>';
echo '<li><strong>Ragnarök</strong> — the inevitable destruction of the gods and the world, followed by rebirth. Odin and most gods die in the final battle. A new world emerges.</li>';
echo '<li><strong>Honorable death</strong> — warriors who died in battle went to Valhalla (Odin\'s hall) to feast and prepare for Ragnarök. Those who died of illness or old age went to Hel\'s realm.</li>';
echo '</ul>';
echo '<h3>Major Deities</h3>';
echo '<ul>';
echo '<li><strong>Odin (Allfather)</strong> — god of wisdom, war, death, poetry, magic. Sacrificed an eye for wisdom at Mimir\'s well; hung on Yggdrasil nine days to discover runes.</li>';
echo '<li><strong>Thor</strong> — god of thunder, storms, strength, and the protection of humanity. Wielder of Mjölnir.</li>';
echo '<li><strong>Freya</strong> — goddess of love, fertility, war, and magic (seiðr). Leader of the Valkyries.</li>';
echo '<li><strong>Loki</strong> — trickster god, agent of chaos and transformation. Shape-shifter who eventually betrays the gods.</li>';
echo '<li><strong>Frigg</strong> — Odin\'s wife, goddess of foresight and motherhood.</li>';
echo '<li><strong>Tyr</strong> — god of justice and law. Lost his hand binding the wolf Fenrir.</li>';
echo '<li><strong>Baldr</strong> — god of light and beauty, whose death (engineered by Loki) begins the countdown to Ragnarök.</li>';
echo '</ul>';
echo '<h3>Sacred Texts</h3>';
echo '<ul>';
echo '<li><strong>The Prose Edda</strong> (Snorri Sturluson, c. 1220 CE) — the most comprehensive account of Norse mythology</li>';
echo '<li><strong>The Poetic Edda</strong> (c. 1270 CE manuscript, older oral origins) — mythological and heroic poems</li>';
echo '<li><strong>The Sagas</strong> — historical and legendary narratives preserving pre-Christian practice</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Blót</strong> — seasonal sacrificial feasts offered to the gods; blood was sprinkled on altars and participants</li>';
echo '<li><strong>Seiðr</strong> — shamanic magic practice, associated especially with Freya and Odin; prophecy and spirit journeying</li>';
echo '<li><strong>Runes</strong> — alphabetic system with magical as well as communicative functions; inscribed on objects, weapons, memorial stones</li>';
echo '<li><strong>Ship burial</strong> — elite dead buried with ships, weapons, and grave goods for the afterlife journey</li>';
echo '</ul>';

// DRUIDIC
echo '<hr style="margin:28px 0;border:none;border-top:2px solid #e5e7eb;">';
echo '<h2 style="color:#276749;">⊕ Celtic / Druidic Religion</h2>';
echo '<p><strong>Region:</strong> Western and Central Europe, Britain, Ireland | <strong>Period:</strong> c. 600 BCE – 400 CE | <strong>Status:</strong> Extinct (revived as Neo-Druidism)</p>';
echo '<h3>Core Beliefs</h3>';
echo '<ul>';
echo '<li><strong>The Otherworld (Tír na nÓg)</strong> — a parallel realm coexisting with the physical world, home of gods, ancestors, and magical beings. Entry points at certain places and times (especially Samhain).</li>';
echo '<li><strong>Reincarnation</strong> — Celtic peoples believed in metempsychosis (soul transmigration). Death was not final but a passage to another form of existence, possibly in the Otherworld or in a new body.</li>';
echo '<li><strong>Sacred Nature</strong> — trees (especially oak), water sources, mountains, and certain animals were sacred. The natural world was alive with divine presence.</li>';
echo '<li><strong>The Three Worlds</strong> — Land, Sea, and Sky as three sacred realms each with its divine inhabitants and powers.</li>';
echo '</ul>';
echo '<h3>The Druids</h3>';
echo '<p>Druids were the priestly, scholarly, and judicial class of Celtic society — not just religious leaders but philosophers, judges, historians, astronomers, and educators. They underwent up to twenty years of oral training (nothing was written down — oral transmission was considered superior). They mediated between humans and gods, conducted sacrifices, settled disputes, and preserved tribal history in verse.</p>';
echo '<h3>Major Deities</h3>';
echo '<ul>';
echo '<li><strong>The Dagda</strong> — "the Good God," father figure, associated with abundance, agriculture, seasons, and wisdom. Wielded a club that killed with one end and resurrected with the other. Owned a cauldron of endless food.</li>';
echo '<li><strong>The Morrigan</strong> — goddess of fate, war, and death. Shapeshifter appearing as crow, eel, wolf, cow. Associated with battlefield prophecy.</li>';
echo '<li><strong>Lugh</strong> — god of skill, crafts, and the harvest festival Lughnasadh. The "shining one," associated with the sun.</li>';
echo '<li><strong>Brigid</strong> — goddess of healing, poetry, and smithcraft. One of the most widely worshipped Celtic deities; her attributes were absorbed by St. Brigid of Kildare.</li>';
echo '<li><strong>Cernunnos</strong> — antlered god of the wild, animals, and the underworld. Lord of the Green World.</li>';
echo '<li><strong>Danu</strong> — mother goddess, ancestral deity of the Tuatha Dé Danann (divine race of Ireland).</li>';
echo '</ul>';
echo '<h3>Practices</h3>';
echo '<ul>';
echo '<li><strong>Seasonal festivals</strong> — Samhain (Oct 31), Imbolc (Feb 1), Beltane (May 1), Lughnasadh (Aug 1) — the four great fire festivals marking the Celtic year</li>';
echo '<li><strong>Sacred groves (Nemeton)</strong> — outdoor sanctuaries in forest clearings for ritual and assembly</li>';
echo '<li><strong>Human sacrifice</strong> — documented by Roman sources (whose bias must be acknowledged); the wicker man; ritual killing in bogs</li>';
echo '<li><strong>Oral tradition</strong> — Druids memorized vast amounts of lore, law, and theology in verse form; nothing written</li>';
echo '<li><strong>Head cult</strong> — the head was considered the seat of the soul; severed heads of enemies were preserved as trophies and oracles</li>';
echo '</ul>';

echo '<div style="background:#f0f4ff;border:1px solid #c3d0f7;border-radius:12px;padding:16px;margin:24px 0;">';
echo '<p style="margin:0;"><strong>Note:</strong> This page covers ancient religions. Eastern traditions, Abrahamic religions, African traditions, and modern movements are documented in full in separate sections — see the Overview for the complete map, and the People and Sources pages for founders and sacred texts across all traditions.</p>';
echo '</div>';

echo '<div style="display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 4px;">';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/overview/">Full Map of Religions</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/people/">Founders & Teachers</a>';
echo '<a class="mk-btn mk-btn--ghost" href="/subjects/religion/sources/">Sacred Texts</a>';
echo '</div></div>';
